const errorMessage = {
    // Authentication related
    USERNAME_EXISTED: 'USERNAME_EXISTED',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    INCORRECT_USERNAME_OR_PASSWORD: 'INCORRECT_USERNAME_OR_PASSWORD',
    GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    NO_CREDENTIALS: 'NO_CREDENTIALS',
    NO_PERMISSION: 'NO_PERMISSION',

    // Security related
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    BOT_ACCESS_DENIED: 'BOT_ACCESS_DENIED',

    // Users related
    EMAIL_EXISTED: 'EMAIL_EXISTED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
    ROLE_EXISTED: 'ROLE_EXISTED',
    ROLE_BEING_USED: 'ROLE_BEING_USED',
    ROLE_IS_IMMUTABLE: 'ROLE_IS_IMMUTABLE',
    INVALID_ROLE_SELECTED: 'INVALID_ROLE_SELECTED',
    ADDRESS_EXISTED: 'ADDRESS_EXISTED',
    ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
    CANNOT_DELETE_DEFAULT_ADDRESS: 'CANNOT_DELETE_DEFAULT_ADDRESS',

    // Services related
    UPLOAD_IMAGE_FAILED: 'UPLOAD_IMAGE_FAILED',
    DELETE_IMAGE_FAILED: 'DELETE_IMAGE_FAILED',

    // Application related
    DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
    BLOCKED_BY_CORS_POLICY: 'BLOCKED_BY_CORS_POLICY',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

    // Categories related
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    CATEGORY_EXISTED: 'CATEGORY_EXISTED',
    CATEGORY_BEING_USED: 'CATEGORY_BEING_USED',

    // Brands related
    BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
    BRAND_EXISTED: 'BRAND_EXISTED',
    BRAND_BEING_USED: 'BRAND_BEING_USED',

    // Products related
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_EXISTED: 'PRODUCT_EXISTED',
    PRODUCT_ITEM_NOT_FOUND: 'PRODUCT_ITEM_NOT_FOUND',
    PRODUCT_BEING_USED: 'PRODUCT_BEING_USED',

    // Orders and carts related
    QUANTITY_EXCEED_CURRENT_STOCK: 'QUANTITY_EXCEED_CURRENT_STOCK',
    STOCK_NOT_ENOUGH_FOR_ORDER: 'STOCK_NOT_ENOUGH_FOR_ORDER',
    CART_NOT_FOUND: 'CART_NOT_FOUND',
    CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    INVALID_STATUS_SELECTED: 'INVALID_STATUS_SELECTED',

    // Promotions and coupons related
    PROMOTION_NOT_FOUND: 'PROMOTION_NOT_FOUND',
    PROMOTION_EXISTED: 'PROMOTION_EXISTED',
    PROMOTION_NO_LONGER_AVAILABLE: 'PROMOTION_NO_LONGER_AVAILABLE',
    COUPON_EXISTED: 'COUPON_EXISTED',
    COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
    COUPON_NO_LONGER_AVAILABLE: 'COUPON_NO_LONGER_AVAILABLE',
    COUPON_REACH_MAX_USAGE: 'COUPON_REACH_MAX_USAGE',
    YOU_HAVE_USED_COUPON: 'YOU_HAVE_USED_COUPON'
} as const

export default errorMessage
