const errorMessage = {
    // Authentication related
    USERNAME_EXISTED: 'USERNAME_EXISTED',
    EMAIL_EXISTED: 'EMAIL_EXISTED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
    INCORRECT_USERNAME_OR_PASSWORD: 'INCORRECT_USERNAME_OR_PASSWORD',
    GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    NO_CREDENTIALS: 'NO_CREDENTIALS',
    NO_PERMISSION: 'NO_PERMISSION',

    // Users related
    ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
    ROLE_EXISTED: 'ROLE_EXISTED',
    ROLE_BEING_USED: 'ROLE_BEING_USED',
    INVALID_ROLE_SELECTED: 'INVALID_ROLE_SELECTED',
    ADDRESS_EXISTED: 'ADDRESS_EXISTED',
    ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
    CANNOT_DELETE_DEFAULT_ADDRESS: 'CANNOT_DELETE_DEFAULT_ADDRESS',

    // Services related
    UPLOAD_IMAGE_FAILED: 'UPLOAD_IMAGE_FAILED',
    DELETE_IMAGE_FAILED: 'DELETE_IMAGE_FAILED',

    // Application related
    DATA_VALIDATION_FAILED: 'DATA_VALIDATION_FAILED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    BLOCKED_BY_CORS_POLICY: 'BLOCKED_BY_CORS_POLICY',

    // Categories related
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    CATEGORY_EXISTED: 'CATEGORY_EXISTED',
    CATEGORY_BEING_USED: 'CATEGORY_BEING_USED',

    // Products related
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_EXISTED: 'PRODUCT_EXISTED',
    PRODUCT_ITEM_NOT_FOUND: 'PRODUCT_ITEM_NOT_FOUND',
    PRODUCT_IDS_MISMATCH: 'PRODUCT_IDS_MISMATCH',
    PRODUCT_BEING_USED: 'PRODUCT_BEING_USED',

    // Orders and carts related
    QUANTITY_EXCEED_CURRENT_STOCK: 'QUANTITY_EXCEED_CURRENT_STOCK',
    CART_NOT_FOUND: 'CART_NOT_FOUND',
    CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
    ORDER_SYSTEM_TEMPORARILY_UNAVAILABLE: 'ORDER_SYSTEM_TEMPORARILY_UNAVAILABLE',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    CANNOT_UPDATE_TO_THIS_STATUS: 'CANNOT_UPDATE_TO_THIS_STATUS',

    // Promotions and coupons related
    COUPON_EXISTED: 'COUPON_EXISTED',
    COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
    COUPON_NO_LONGER_AVAILABLE: 'COUPON_NO_LONGER_AVAILABLE',
    COUPON_REACH_MAX_USAGE: 'COUPON_REACH_MAX_USAGE',
    YOU_HAVE_USED_COUPON: 'YOU_HAVE_USED_COUPON',
    PROMOTION_NOT_FOUND: 'PROMOTION_NOT_FOUND',
    PROMOTION_EXISTED: 'PROMOTION_EXISTED',

    // Inventories related
    INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
    INVENTORY_QUANTITY_NOT_ENOUGH: 'INVENTORY_QUANTITY_NOT_ENOUGH',
    PRODUCT_IMPORT_NOT_FOUND: 'PRODUCT_IMPORT_NOT_FOUND',
    PRODUCT_QUANTITY_MISMATCH: 'PRODUCT_QUANTITY_MISMATCH'
} as const

export default errorMessage
