const orderActions = {
    RESERVE_STOCK: 'RESERVE_STOCK',
    RELEASE_STOCK: 'RELEASE_STOCK',
    REDUCE_STOCK: 'REDUCE_STOCK',
    INCREASE_STOCK: 'INCREASE_STOCK',
    MARK_AS_DELIVERED: 'MARK_AS_DELIVERED',
    MARK_AS_REFUNDED: 'MARK_AS_REFUNDED',
    SEND_NOTIFICATION: 'SEND_NOTIFICATION'
} as const

export default orderActions
