const successMessage = {
    LOGIN_SUCCESSFULLY: 'LOGIN_SUCCESSFULLY',
    REGISTER_SUCCESSFULLY: 'REGISTER_SUCCESSFULLY',
    REFRESH_TOKEN_SUCCESSFULLY: 'REFRESH_TOKEN_SUCCESSFULLY',
    CHANGE_PASSWORD_SUCCESSFULLY: 'CHANGE_PASSWORD_SUCCESSFULLY',
    RESET_PASSWORD_EMAIL_SENT: 'RESET_PASSWORD_EMAIL_SENT',
    RESET_PASSWORD_SUCCESSFULLY: 'RESET_PASSWORD_SUCCESSFULLY',
    DEACTIVATE_ACCOUNT_SUCCESSFULLY: 'DEACTIVATE_ACCOUNT_SUCCESSFULLY',
    GOOGLE_AUTH_SUCCESSFULLY: 'GOOGLE_AUTH_SUCCESSFULLY',
    UPLOAD_IMAGE_SUCCESSFULLY: 'UPLOAD_IMAGE_SUCCESSFULLY',
    DELETE_IMAGE_SUCCESSFULLY: 'DELETE_IMAGE_SUCCESSFULLY',
    CHECK_IN_SUCCESSFULLY: 'CHECK_IN_SUCCESSFULLY',
    CHECK_OUT_SUCCESSFULLY: 'CHECK_OUT_SUCCESSFULLY',
    UPDATE_USER_SUCCESSFULLY: 'UPDATE_USER_SUCCESSFULLY',
    CREATE_ADMIN_SUCCESSFULLY: 'CREATE_ADMIN_SUCCESSFULLY',
    CREATE_STAFF_SUCCESSFULLY: 'CREATE_STAFF_SUCCESSFULLY',
    UPDATE_PRICE_SUCCESSFULLY: 'UPDATE_PRICE_SUCCESSFULLY',
    VERIFY_PAYMENT_SUCCESSFULLY: 'VERIFY_PAYMENT_SUCCESSFULLY',
    SELL_TICKETS_SUCCESSFULLY: 'SELL_TICKETS_SUCCESSFULLY'
}

export default successMessage
