const successMessage = {
    // Authentication related
    SIGN_IN_SUCCESSFULLY: 'SIGN_IN_SUCCESSFULLY',
    SIGN_UP_SUCCESSFULLY: 'SIGN_UP_SUCCESSFULLY',
    REFRESH_TOKEN_SUCCESSFULLY: 'REFRESH_TOKEN_SUCCESSFULLY',
    DEACTIVATE_ACCOUNT_SUCCESSFULLY: 'DEACTIVATE_ACCOUNT_SUCCESSFULLY',
    RESET_PASSWORD_EMAIL_SENT: 'RESET_PASSWORD_EMAIL_SENT',
    RESET_PASSWORD_SUCCESSFULLY: 'RESET_PASSWORD_SUCCESSFULLY',
    GOOGLE_AUTH_SUCCESSFULLY: 'GOOGLE_AUTH_SUCCESSFULLY',
    VERIFY_PERMISSION_SUCCESSFULLY: 'VERIFY_PERMISSION_SUCCESSFULLY',

    // Users related
    CHANGE_PASSWORD_SUCCESSFULLY: 'CHANGE_PASSWORD_SUCCESSFULLY',
    UPDATE_USER_SUCCESSFULLY: 'UPDATE_USER_SUCCESSFULLY',
    CREATE_STAFF_SUCCESSFULLY: 'CREATE_STAFF_SUCCESSFULLY',
    CREATE_ROLE_SUCCESSFULLY: 'CREATE_ROLE_SUCCESSFULLY',
    UPDATE_ROLE_SUCCESSFULLY: 'UPDATE_ROLE_SUCCESSFULLY',
    DELETE_ROLE_SUCCESSFULLY: 'DELETE_ROLE_SUCCESSFULLY',
    DEACTIVATE_CUSTOMER_SUCCESSFULLY: 'DEACTIVATE_CUSTOMER_SUCCESSFULLY',
    ADD_ADDRESS_SUCCESSFULLY: 'ADD_ADDRESS_SUCCESSFULLY',
    UPDATE_ADDRESS_SUCCESSFULLY: 'UPDATE_ADDRESS_SUCCESSFULLY',
    DELETE_ADDRESS_SUCCESSFULLY: 'DELETE_ADDRESS_SUCCESSFULLY',

    // Services related
    UPLOAD_IMAGE_SUCCESSFULLY: 'UPLOAD_IMAGE_SUCCESSFULLY',
    DELETE_IMAGE_SUCCESSFULLY: 'DELETE_IMAGE_SUCCESSFULLY',

    // Categories related
    CREATE_CATEGORY_SUCCESSFULLY: 'CREATE_CATEGORY_SUCCESSFULLY',
    UPDATE_CATEGORY_SUCCESSFULLY: 'UPDATE_CATEGORY_SUCCESSFULLY',
    DELETE_CATEGORY_SUCCESSFULLY: 'DELETE_CATEGORY_SUCCESSFULLY',

    // Brands related
    CREATE_BRAND_SUCCESSFULLY: 'CREATE_BRAND_SUCCESSFULLY',
    UPDATE_BRAND_SUCCESSFULLY: 'UPDATE_BRAND_SUCCESSFULLY',
    DELETE_BRAND_SUCCESSFULLY: 'DELETE_BRAND_SUCCESSFULLY',

    // Products related
    CREATE_PRODUCT_SUCCESSFULLY: 'CREATE_PRODUCT_SUCCESSFULLY',
    UPDATE_PRODUCT_SUCCESSFULLY: 'UPDATE_PRODUCT_SUCCESSFULLY',
    DELETE_PRODUCT_SUCCESSFULLY: 'DELETE_PRODUCT_SUCCESSFULLY',

    // Orders and carts related
    ADD_TO_CART_SUCCESSFULLY: 'ADD_TO_CART_SUCCESSFULLY',
    UPDATE_CART_SUCCESSFULLY: 'UPDATE_CART_SUCCESSFULLY',
    RESET_CART_SUCCESSFULLY: 'RESET_CART_SUCCESSFULLY',
    PLACE_ORDER_SUCCESSFULLY: 'PLACE_ORDER_SUCCESSFULLY',
    UPDATE_ORDER_SUCCESSFULLY: 'UPDATE_ORDER_SUCCESSFULLY',

    // Order statuses related
    CREATE_ORDER_STATUS_SUCCESSFULLY: 'CREATE_ORDER_STATUS_SUCCESSFULLY',
    UPDATE_ORDER_STATUS_SUCCESSFULLY: 'UPDATE_ORDER_STATUS_SUCCESSFULLY',
    DELETE_ORDER_STATUS_SUCCESSFULLY: 'DELETE_ORDER_STATUS_SUCCESSFULLY',
    CREATE_TRANSITION_SUCCESSFULLY: 'CREATE_TRANSITION_SUCCESSFULLY',
    DELETE_TRANSITION_SUCCESSFULLY: 'DELETE_TRANSITION_SUCCESSFULLY',

    // Promotions and coupons related
    CREATE_PROMOTION_SUCCESSFULLY: 'CREATE_PROMOTION_SUCCESSFULLY',
    UPDATE_PROMOTION_SUCCESSFULLY: 'UPDATE_PROMOTION_SUCCESSFULLY',
    DISABLE_PROMOTION_SUCCESSFULLY: 'DISABLE_PROMOTION_SUCCESSFULLY',
    CREATE_COUPON_SUCCESSFULLY: 'CREATE_COUPON_SUCCESSFULLY',
    UPDATE_COUPON_SUCCESSFULLY: 'UPDATE_COUPON_SUCCESSFULLY',
    DISABLE_COUPON_SUCCESSFULLY: 'DISABLE_COUPON_SUCCESSFULLY',

    // Inventories related
    UPDATE_INVENTORY_SUCCESSFULLY: 'UPDATE_INVENTORY_SUCCESSFULLY',
    TRACK_IMPORT_SUCCESSFULLY: 'TRACK_IMPORT_SUCCESSFULLY',

    // Reports related
    REPORT_DAMAGE_SUCCESSFULLY: 'REPORT_DAMAGE_SUCCESSFULLY',

    // Conversations and messages related
    SEND_MESSAGE_SUCCESSFULLY: 'SEND_MESSAGE_SUCCESSFULLY'
} as const

export default successMessage
