import { PrismaClient, ShoeGender } from '@prisma/client'
import { generateProductBarcode } from '../../src/utils/stringHelpers'

export const seedProducts = async (prisma: PrismaClient) => {
    // --- Root Products ---
    await prisma.rootProduct.createMany({
        data: [
            {
                brandId: 2,
                name: 'Adidas Japan Wales Bonner - Light Purple',
                slug: 'adidas-japan-wales-bonner-light-purple',
                description:
                    'Adidas Japan Wales Bonner - Light Purple là sự giao thoa tinh tế giữa di sản thể thao và phong cách thời trang cao cấp. Thiết kế lấy cảm hứng từ thập niên 70, kết hợp chất liệu da lộn mềm mại cùng sắc tím nhạt nhẹ nhàng, thanh lịch. Logo 3 gạch kinh điển và chi tiết khâu thủ công tạo điểm nhấn tinh xảo. Một lựa chọn hoàn hảo cho những ai yêu phong cách retro pha lẫn nét sang trọng hiện đại.',
                price: 2600000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 2,
                name: 'Adidas Tokyo - Black',
                slug: 'adidas-tokyo-black',
                description:
                    'Adidas Tokyo - Black mang tinh thần thể thao hiện đại kết hợp phong cách đường phố tối giản. Thiết kế tông đen toàn phần mạnh mẽ, dễ phối đồ, được làm từ chất liệu vải mesh thoáng khí giúp ôm chân nhẹ nhàng và linh hoạt. Đế cao su bền bỉ mang lại độ bám chắc và cảm giác di chuyển êm ái. Một đôi giày lý tưởng cho những ai yêu thích sự năng động, tinh gọn và phong cách chuẩn urban.',
                price: 1200000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 2,
                name: 'Adidas Stan Smith - Cloud White/ Court Green',
                slug: 'adidas-stan-smith-cloud-white-court-green',
                description:
                    'Adidas Stan Smith - Cloud White/Court Green là biểu tượng bất hủ của phong cách tối giản và thanh lịch. Với phần upper da trắng mịn cùng điểm nhấn màu xanh lá ở gót giày, đôi sneaker này toát lên vẻ tinh tế và dễ phối trong mọi outfit. Đế cao su êm ái, bền bỉ mang lại cảm giác thoải mái suốt ngày dài. Một lựa chọn hoàn hảo cho những ai yêu thích sự cổ điển pha chút hiện đại.',
                price: 780000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 2,
                name: 'Adidas Ozmillen - Black',
                slug: 'adidas-ozmillen-black',
                description:
                    'Adidas Ozmillen - Black mang thiết kế tương lai đậm chất Y2K, kết hợp giữa phong cách retro và công nghệ hiện đại. Tông đen huyền bí cùng chi tiết kim loại tạo nên vẻ ngoài mạnh mẽ, cá tính. Phần upper mesh thoáng khí giúp thoải mái khi di chuyển, trong khi đế Adiprene+ êm ái mang lại độ đàn hồi và hỗ trợ tối ưu. Hoàn hảo cho những ai muốn nổi bật với phong cách streetwear hiện đại.',
                price: 1080000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 3,
                name: 'Reebok Answer DMX - White',
                slug: 'reebok-answer-dmx-white',
                description:
                    'Reebok Answer DMX - White là biểu tượng của thời kỳ hoàng kim bóng rổ, gắn liền với huyền thoại Allen Iverson. Thiết kế mang đậm chất retro với phối màu trắng tinh khôi, kết hợp công nghệ đệm DMX huyền thoại cho cảm giác êm ái và phản hồi linh hoạt. Chất liệu da cao cấp cùng đường nét mạnh mẽ tạo nên vẻ ngoài sang trọng, thể thao. Một lựa chọn hoàn hảo cho người yêu phong cách cổ điển và hiệu năng đỉnh cao.',
                price: 2155000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 3,
                name: 'Reebok Court Advance - Midnight Navy / Yellow',
                slug: 'reebok-court-advance-midnight-navy-yellow',
                description:
                    'Reebok Court Advance - Midnight Navy/Yellow mang phong cách cổ điển đậm chất sân đấu, kết hợp giữa nét retro và sự năng động hiện đại. Thân giày làm từ da cao cấp với phối màu xanh navy và vàng nổi bật, tạo điểm nhấn đầy cá tính. Đế cao su bền bỉ cho độ bám chắc, trong khi lớp đệm êm ái giúp di chuyển thoải mái suốt ngày dài. Lý tưởng cho người yêu thời trang vintage và phong cách thể thao tinh tế.',
                price: 500000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 4,
                name: "Giày Tây Biti's Nam Màu Đen BVM002777DEN",
                slug: "giay-tay-biti's-nam-mau-den-bvm002777den",
                description:
                    "Giày Tây Biti's Nam BVM002777DEN mang thiết kế thanh lịch, sang trọng phù hợp cho môi trường công sở và sự kiện trang trọng. Tông màu đen cổ điển dễ phối với nhiều trang phục, chất liệu da tổng hợp cao cấp giúp bền đẹp và dễ vệ sinh. Đế giày êm, chống trơn trượt, mang lại cảm giác thoải mái suốt ngày dài. Lựa chọn hoàn hảo cho quý ông hiện đại yêu sự tinh tế và chỉn chu.",
                price: 845000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Giày Tây Mocassin Biti's Nam Màu Đen BMM001977DEN",
                slug: "giay-tay-mocassin-biti's-nam-mau-den-bmm001977den",
                description:
                    "Giày Tây Mocassin Biti's Nam BMM001977DEN mang phong cách hiện đại pha nét cổ điển, lý tưởng cho quý ông ưa chuộng sự tinh tế và tiện dụng. Thiết kế không dây dễ mang, phần da đen bóng sang trọng cùng đường may tỉ mỉ thể hiện sự đẳng cấp. Đế cao su mềm, chống trơn giúp bước đi êm ái và vững chắc. Phù hợp cho cả môi trường công sở lẫn các dịp trang trọng.",
                price: 715000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Giày Tây Mocasin Biti's Nam Màu Nâu Đậm BMM001677NAD",
                slug: "giay-tay-mocasin-biti's-nam-mau-nau-dam-bmm001677nad",
                description:
                    "Giày Tây Mocasin Biti's Nam BMM001677NAD sở hữu thiết kế tinh tế với gam màu nâu đậm sang trọng, dễ phối cùng nhiều trang phục. Kiểu dáng slip-on tiện lợi, chất liệu da mềm cao cấp mang lại cảm giác thoải mái và thoáng khí. Đế cao su bền bỉ, chống trơn trượt giúp di chuyển tự tin và êm ái. Lý tưởng cho quý ông yêu phong cách lịch lãm, hiện đại và tinh giản.",
                price: 680000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Giày Tây Nam Biti's BMM001477",
                slug: "giay-tay-nam-biti's-bmm001477",
                description:
                    "Giày Tây Nam Biti's BMM001477 mang phong cách sang trọng, hiện đại, phù hợp cho môi trường công sở và các dịp trang trọng. Thiết kế thanh thoát với chất liệu da cao cấp tạo cảm giác mềm mại, bền đẹp theo thời gian. Đế giày chắc chắn, chống trơn hiệu quả, mang lại sự thoải mái và tự tin trong từng bước đi. Lựa chọn lý tưởng cho quý ông yêu sự chỉn chu và tinh tế.",
                price: 733500,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Giày Tây Biti's Nam Màu Đen BVM002477DEN",
                slug: "giay-tay-biti's-nam-mau-den-bvm002477den",
                description:
                    "Giày Tây Biti's Nam BVM002477DEN mang thiết kế cổ điển, thanh lịch với tông đen sang trọng, phù hợp cho công sở và các dịp quan trọng. Chất liệu da tổng hợp cao cấp giúp giày bền, bóng đẹp và dễ vệ sinh. Đế cao su chắc chắn, chống trơn trượt, mang lại cảm giác êm ái và tự tin suốt ngày dài. Lựa chọn hoàn hảo cho quý ông yêu phong cách tinh tế và chuyên nghiệp.",
                price: 845000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Sandal Biti's Hunter Nam Màu Đen HEM000500DEN",
                slug: "sandal-biti's-hunter-nam-mau-den-hem000500den",
                description:
                    "Sandal Biti's Hunter Nam Màu Đen HEM000500DEN mang thiết kế thể thao, năng động với tông đen mạnh mẽ. Chất liệu da tổng hợp bền bỉ kết hợp đế cao su chắc chắn, giúp bạn di chuyển thoải mái và ổn định. Kiểu dáng mở thoáng khí, thích hợp cho các hoạt động ngoài trời hoặc dạo phố. Lựa chọn lý tưởng cho những ai yêu thích sự tiện dụng, thoải mái mà vẫn đảm bảo phong cách thời trang.",
                price: 432450,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 4,
                name: "Sandal Biti's Hunter Sandal - Dune Edition Nam Màu Trắng HEM001300TRG",
                slug: "sandal-biti's-hunter-sandal-dune-edition-nam-mau-trang-hem001300trg",
                description:
                    "Sandal Biti's Hunter Sandal - Dune Edition Nam Màu Trắng HEM001300TRG mang thiết kế thể thao, năng động với tông màu trắng tinh tế. Chất liệu da tổng hợp cao cấp kết hợp đế cao su bền bỉ, mang lại sự thoải mái và độ bám chắc khi di chuyển. Kiểu dáng mở, thoáng khí, lý tưởng cho các hoạt động ngoài trời và dạo phố. Một lựa chọn hoàn hảo cho những ai yêu thích sự trẻ trung, cá tính.",
                price: 439200,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 4,
                name: "Sandal Biti's Hunter Nam Màu Nâu HEM001700NAU",
                slug: "sandal-biti's-hunter-nam-mau-nau-hem001700nau",
                description:
                    "Sandal Biti's Hunter Nam Màu Nâu HEM001700NAU mang thiết kế mạnh mẽ, nam tính với màu nâu ấm áp, dễ phối đồ. Chất liệu da tổng hợp bền bỉ, kết hợp đế cao su chống trơn mang lại cảm giác thoải mái và độ bám chắc khi di chuyển. Kiểu dáng mở thoáng khí, thích hợp cho các hoạt động ngoài trời và dạo phố. Lựa chọn lý tưởng cho những ai yêu thích sự tiện dụng và phong cách thể thao.",
                price: 565000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 4,
                name: "Sandal Biti's Nam Màu Xám BRM002877XAM",
                slug: "sandal-biti's-nam-mau-xam-brm002877xam",
                description:
                    "Sandal Biti's Nam Màu Xám BRM002877XAM mang thiết kế đơn giản nhưng đầy tinh tế với gam màu xám dễ phối đồ. Chất liệu cao cấp, bền bỉ kết hợp đế cao su chắc chắn giúp bạn di chuyển êm ái và ổn định. Kiểu dáng mở thoáng khí, phù hợp cho các hoạt động ngoài trời hoặc dạo phố. Lựa chọn lý tưởng cho những ai yêu thích sự năng động và thoải mái trong từng bước đi.",
                price: 470000,
                isAccessory: false,
                createdBy: 2
            }
        ]
    })

    // --- Product Images ---
    await prisma.productImage.createMany({
        data: [
            { rootProductId: 16, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760150893/product/adidas_japan_wb_1_qrugt1.jpg' },
            { rootProductId: 16, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760150894/product/adidas_japan_wb_2_gjreqs.jpg' },
            { rootProductId: 16, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760150894/product/adidas_japan_wb_3_z6jvvq.jpg' },
            { rootProductId: 16, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760150894/product/adidas_japan_wb_4_wjzrdn.jpg' },
            { rootProductId: 16, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760150895/product/adidas_japan_wb_5_g8trpn.jpg' },
            { rootProductId: 16, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760150895/product/adidas_japan_wb_6_ww4fgh.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153591/product/adidas_tokyo_b_1_tr7qju.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153591/product/adidas_tokyo_b_2_mp5xyq.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153591/product/adidas_tokyo_b_3_sr5ydw.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153591/product/adidas_tokyo_b_4_m4agyr.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153592/product/adidas_tokyo_b_5_upa6yc.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153592/product/adidas_tokyo_b_6_zhwyul.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153592/product/adidas_tokyo_b_7_efqiyh.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153593/product/adidas_tokyo_b_8_agrjv6.jpg' },
            { rootProductId: 17, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760153598/product/adidas_tokyo_b_9_x0agwx.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154409/product/adidasSS_Cloud_White_1_zaknye.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154410/product/adidasSS_Cloud_White_2_wuawcl.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154410/product/adidasSS_Cloud_White_3_sp4x7y.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154410/product/adidasSS_Cloud_White_4_gnswkn.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154410/product/adidasSS_Cloud_White_5_mwqr2r.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154411/product/adidasSS_Cloud_White_6_gjnuyp.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154415/product/adidasSS_Cloud_White_7_ppo60m.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154416/product/adidasSS_Cloud_White_8_z3mw0i.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154420/product/adidasSS_Cloud_White_9_fcin0j.jpg' },
            { rootProductId: 18, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760154418/product/adidasSS_Cloud_White_10_jhjobe.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155122/product/adidas_ozmillen_1_gkblel.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155128/product/adidas_ozmillen_2_kxmcwp.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155122/product/adidas_ozmillen_3_fpi75r.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155122/product/adidas_ozmillen_4_rz63tx.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155123/product/adidas_ozmillen_5_g1wzs8.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155123/product/adidas_ozmillen_6_alhyru.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155125/product/adidas_ozmillen_7_dopexl.jpg' },
            { rootProductId: 19, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155128/product/adidas_ozmillen_8_hndw3e.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155966/product/reebok_answer_dmx_1_i93xc3.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155966/product/reebok_answer_dmx_2_xqchuc.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155967/product/reebok_answer_dmx_3_x8qmlz.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155968/product/reebok_answer_dmx_4_wlrqgy.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155967/product/reebok_answer_dmx_5_qa9vrq.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155972/product/reebok_answer_dmx_6_v9u4mc.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155973/product/reebok_answer_dmx_7_owj2ix.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155974/product/reebok_answer_dmx_8_b6cfou.jpg' },
            { rootProductId: 20, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760155976/product/reebok_answer_dmx_9_fhrg0j.jpg' },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156773/product/reebok_court_advance_midnight_navy_1_hapfbm.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156774/product/reebok_court_advance_midnight_navy_2_k7znsr.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156775/product/reebok_court_advance_midnight_navy_3_blsn3w.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156774/product/reebok_court_advance_midnight_navy_4_bjzbvw.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156776/product/reebok_court_advance_midnight_navy_5_fr1jn8.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156780/product/reebok_court_advance_midnight_navy_6_baoloo.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156782/product/reebok_court_advance_midnight_navy_7_ky8t2f.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156782/product/reebok_court_advance_midnight_navy_8_e0aaid.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156786/product/reebok_court_advance_midnight_navy_9_yxz7zx.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156784/product/reebok_court_advance_midnight_navy_10_iapyg6.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156791/product/reebok_court_advance_midnight_navy_11_m5hs0i.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156786/product/reebok_court_advance_midnight_navy_12_oedzb4.jpg'
            },
            {
                rootProductId: 21,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760156788/product/reebok_court_advance_midnight_navy_13_zyubcz.jpg'
            },
            { rootProductId: 22, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760201404/product/giay_tay_bitis_1_ph01ru.jpg' },
            { rootProductId: 22, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760201404/product/giay_tay_bitis_2_knsc0t.jpg' },
            { rootProductId: 22, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760201404/product/giay_tay_bitis_3_alaieo.jpg' },
            { rootProductId: 22, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760201404/product/giay_tay_bitis_4_a5yomy.jpg' },
            { rootProductId: 22, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760201404/product/giay_tay_bitis_5_rnhpwb.jpg' },
            { rootProductId: 22, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760201405/product/giay_tay_bitis_6_rrbl3z.jpg' },
            { rootProductId: 22, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760201405/product/giay_tay_bitis_7_tw7a1f.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208609/product/giay_tay_mocassin_bitis_1_jx4t9z.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208608/product/giay_tay_mocassin_bitis_2_epsqjv.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208608/product/giay_tay_mocassin_bitis_3_oubwa2.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208608/product/giay_tay_mocassin_bitis_4_vrmont.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208609/product/giay_tay_mocassin_bitis_5_gjaqdf.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208608/product/giay_tay_mocassin_bitis_6_rwkoxs.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208608/product/giay_tay_mocassin_bitis_7_jut2qu.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208609/product/giay_tay_mocassin_bitis_8_zb9t8w.jpg' },
            { rootProductId: 23, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760208609/product/giay_tay_mocassin_bitis_9_gx2ozi.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209277/product/giay-tay-mocasin-bitis_1_xbqnem.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209277/product/giay-tay-mocasin-bitis_2_wl79bn.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209277/product/giay-tay-mocasin-bitis_3_addpzz.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209278/product/giay-tay-mocasin-bitis_4_svm0eu.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209277/product/giay-tay-mocasin-bitis_5_uuqjij.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209278/product/giay-tay-mocasin-bitis_6_uvhd4n.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209278/product/giay-tay-mocasin-bitis_7_wesfkq.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209282/product/giay-tay-mocasin-bitis_8_wmyf27.jpg' },
            { rootProductId: 24, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209286/product/giay-tay-mocasin-bitis_9_bzaeqo.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760209964/product/giay-tay-nam-bitis_1_tqwfqt.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210012/product/giay-tay-nam-bitis_2_rssj58.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210049/product/giay-tay-nam-bitis_3_squcno.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210050/product/giay-tay-nam-bitis_4_ybbdux.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210049/product/giay-tay-nam-bitis_5_quei5s.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210049/product/giay-tay-nam-bitis_6_aoigoi.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210049/product/giay-tay-nam-bitis_7_qmqiyv.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210052/product/giay-tay-nam-bitis_8_fpejm3.jpg' },
            { rootProductId: 25, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210054/product/giay-tay-nam-bitis_9_i60udz.jpg' },
            { rootProductId: 26, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210734/product/bvm002477den__1_rioe30.jpg' },
            { rootProductId: 26, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210734/product/bvm002477den__2_tyrvki.jpg' },
            { rootProductId: 26, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210734/product/bvm002477den__3_xbcpey.jpg' },
            { rootProductId: 26, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210735/product/bvm002477den__4_wmjchr.jpg' },
            { rootProductId: 26, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210735/product/bvm002477den__5_ym0vn0.jpg' },
            { rootProductId: 26, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210736/product/bvm002477den__6_e51oa5.jpg' },
            { rootProductId: 26, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760210741/product/bvm002477den__7_kruhgn.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345382/product/hem000500den__1_vniljd.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345382/product/hem000500den__2_l2mqf4.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345382/product/hem000500den__3_ulzwxv.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345382/product/hem000500den__4_xs8dqd.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345382/product/hem000500den__5_wdkegh.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345382/product/hem000500den__6_cqw7gr.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345382/product/hem000500den__7_eaqhk2.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345383/product/hem000500den__8_dhwtp6.jpg' },
            { rootProductId: 27, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760345383/product/hem000500den__9_eaytbc.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346542/product/hem001300trg_1_ezagic.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346542/product/hem001300trg_2_lrvknl.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346542/product/hem001300trg_3_ws6h1p.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346543/product/hem001300trg_4_wdrqv0.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346543/product/hem001300trg_5_egwbxo.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346543/product/hem001300trg_6_sk06cg.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346544/product/hem001300trg_7_uqyewr.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346543/product/hem001300trg_8_wxmige.jpg' },
            { rootProductId: 28, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760346548/product/hem001300trg_9_ucbgdv.jpg' },
            { rootProductId: 29, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347147/product/hem001700nau__1_sgbwj1.jpg' },
            { rootProductId: 29, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347148/product/hem001700nau__2_esstsv.jpg' },
            { rootProductId: 29, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347148/product/hem001700nau__3_ukuxgi.jpg' },
            { rootProductId: 29, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347148/product/hem001700nau__4_yeqgrk.jpg' },
            { rootProductId: 29, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347148/product/hem001700nau__5_uuuvhh.jpg' },
            { rootProductId: 29, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347149/product/hem001700nau__6_m7haqm.jpg' },
            { rootProductId: 29, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347149/product/hem001700nau__7_vpwnap.jpg' },
            { rootProductId: 30, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347623/product/brm002877xam__1_auqjto.jpg' },
            { rootProductId: 30, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347623/product/brm002877xam__2_kyxbm5.jpg' },
            { rootProductId: 30, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347624/product/brm002877xam__3_vtrg8g.jpg' },
            { rootProductId: 30, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347624/product/brm002877xam__4_smd4i0.jpg' },
            { rootProductId: 30, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347625/product/brm002877xam__5_l0oo7d.jpg' },
            { rootProductId: 30, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347628/product/brm002877xam__6_wf8uvr.jpg' },
            { rootProductId: 30, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760347629/product/brm002877xam__7_mynftx.jpg' }
        ]
    })

    // --- Product Items ---
    await prisma.productItem.createMany({
        data: [
            { rootProductId: 16, size: '41', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 16, size: '42', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 16, size: '43', stock: 28, barcode: generateProductBarcode() },
            { rootProductId: 16, size: '43.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 16, size: '44', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 16, size: '44.5', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 17, size: '38.5', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 17, size: '39', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 17, size: '40', stock: 41, barcode: generateProductBarcode() },
            { rootProductId: 17, size: '40.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 17, size: '41', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 17, size: '42', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '36', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '36.5', stock: 16, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '37', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '38', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '38.5', stock: 14, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '39', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '40', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 18, size: '41', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '38', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '38.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '39', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '40', stock: 19, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '40.5', stock: 23, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '41', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '42', stock: 13, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '42.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 19, size: '43', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '40', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '41', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '42', stock: 17, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '42.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '43', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '44', stock: 18, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '44.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 20, size: '45', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '36', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '36.5', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '37', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '38', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '38.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '39', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '40', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '41', stock: 23, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '42', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 21, size: '43', stock: 13, barcode: generateProductBarcode() },
            { rootProductId: 22, size: '39', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 22, size: '40', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 22, size: '41', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 22, size: '42', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 22, size: '43', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 22, size: '44', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 23, size: '39', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 23, size: '40', stock: 24, barcode: generateProductBarcode() },
            { rootProductId: 23, size: '41', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 23, size: '42', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 23, size: '43', stock: 17, barcode: generateProductBarcode() },
            { rootProductId: 24, size: '38', stock: 28, barcode: generateProductBarcode() },
            { rootProductId: 24, size: '39', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 24, size: '40', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 24, size: '41', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 24, size: '42', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 24, size: '43', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 25, size: '38', stock: 28, barcode: generateProductBarcode() },
            { rootProductId: 25, size: '39', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 25, size: '40', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 25, size: '41', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 25, size: '42', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 25, size: '43', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 26, size: '39', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 26, size: '40', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 26, size: '41', stock: 50, barcode: generateProductBarcode() },
            { rootProductId: 26, size: '42', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 26, size: '43', stock: 23, barcode: generateProductBarcode() },
            { rootProductId: 27, size: '39', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 27, size: '40', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 27, size: '41', stock: 34, barcode: generateProductBarcode() },
            { rootProductId: 27, size: '42', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 27, size: '43', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 27, size: '44', stock: 13, barcode: generateProductBarcode() },
            { rootProductId: 28, size: '39', stock: 31, barcode: generateProductBarcode() },
            { rootProductId: 28, size: '40', stock: 23, barcode: generateProductBarcode() },
            { rootProductId: 28, size: '41', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 28, size: '42', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 28, size: '43', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 28, size: '44', stock: 24, barcode: generateProductBarcode() },
            { rootProductId: 29, size: '39', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 29, size: '40', stock: 23, barcode: generateProductBarcode() },
            { rootProductId: 29, size: '41', stock: 31, barcode: generateProductBarcode() },
            { rootProductId: 29, size: '42', stock: 28, barcode: generateProductBarcode() },
            { rootProductId: 29, size: '43', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 29, size: '44', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 29, size: '45', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 30, size: '39', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 30, size: '40', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 30, size: '41', stock: 11, barcode: generateProductBarcode() },
            { rootProductId: 30, size: '42', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 30, size: '43', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 30, size: '44', stock: 30, barcode: generateProductBarcode() }
        ]
    })

    // --- Shoe Features ---
    await prisma.shoeFeature.createMany({
        data: [
            {
                rootProductId: 16,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da lộn (Suede) cao cấp + Vải dệt thủ công',
                soleMaterial: 'Cao su tự nhiên',
                liningMaterial: 'Vải dệt mềm cao cấp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Phong cách retro Nhật Bản, phối màu Wales Bonner đặc trưng',
                countryOfOrigin: 'Indonesia',
                primaryColor: '#918cc2',
                secondaryColor: '#9f876b',
                heelHeight: 2.7,
                durabilityRating: 4.6,
                releaseYear: 2024
            },
            {
                rootProductId: 17,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Vải dệt Primeknit tái chế',
                soleMaterial: 'Cao su Continental + Bọt Eva',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Rất tốt',
                pattern: 'Thiết kế tối giản lấy cảm hứng từ Tokyo với logo 3 gạch tinh tế',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#000000',
                secondaryColor: '#f5f5f5',
                heelHeight: 3.0,
                durabilityRating: 4.7,
                releaseYear: 2024
            },
            {
                rootProductId: 18,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da tổng hợp + Primegreen tái chế',
                soleMaterial: 'Cao su bền bỉ',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế cổ điển Stan Smith với logo xanh Court Green ở gót',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#ffffff',
                secondaryColor: '#006400',
                heelHeight: 2.5,
                durabilityRating: 4.8,
                releaseYear: 2023
            },
            {
                rootProductId: 19,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Vải lưới tổng hợp + Da PU',
                soleMaterial: 'Cao su + Bọt Eva',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế chunky hiện đại lấy cảm hứng từ Y2K với logo 3 gạch phản quang',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#000000',
                secondaryColor: '#e22523',
                heelHeight: 3.8,
                durabilityRating: 4.6,
                releaseYear: 2024
            },
            {
                rootProductId: 20,
                categoryId: 1,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da thật + Da tổng hợp cao cấp',
                soleMaterial: 'Cao su + Công nghệ đệm DMX',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Khóa kéo và dây buộc ẩn',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Trung bình',
                pattern: 'Thiết kế retro bóng rổ cổ điển với logo Reebok Vector ở hai bên',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#ffffff',
                secondaryColor: '#a32227',
                heelHeight: 3.5,
                durabilityRating: 4.7,
                releaseYear: 2024
            },
            {
                rootProductId: 21,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su lưu hóa',
                liningMaterial: 'Vải dệt',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế cổ điển phong cách sân quần vợt, logo Reebok vàng nổi bật',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#191970',
                secondaryColor: '#ffd700',
                heelHeight: 2.8,
                durabilityRating: 4.5,
                releaseYear: 2024
            },
            {
                rootProductId: 22,
                categoryId: 4,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Da nhân tạo',
                closureType: 'Trượt (Slip-On)',
                toeShape: 'Nhọn vừa',
                waterResistant: 'Có khả năng kháng nước nhẹ',
                breathability: 'Trung bình',
                pattern: 'Thiết kế trơn cổ điển với đường chỉ may tinh tế',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#000000',
                secondaryColor: null,
                heelHeight: 3.0,
                durabilityRating: 4.8,
                releaseYear: 2023
            },
            {
                rootProductId: 23,
                categoryId: 4,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Da nhân tạo',
                closureType: 'Trượt (Slip-On)',
                toeShape: 'Bo tròn kiểu mocassin',
                waterResistant: 'Có khả năng kháng nước nhẹ',
                breathability: 'Tốt',
                pattern: 'Kiểu dáng mocassin cổ điển với đường chỉ nổi thủ công',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#000000',
                secondaryColor: null,
                heelHeight: 2.5,
                durabilityRating: 4.7,
                releaseYear: 2023
            },
            {
                rootProductId: 24,
                categoryId: 4,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Da nhân tạo',
                closureType: 'Trượt (Slip-On)',
                toeShape: 'Bo tròn kiểu mocassin',
                waterResistant: 'Có khả năng kháng nước nhẹ',
                breathability: 'Tốt',
                pattern: 'Thiết kế mocassin cổ điển với đường chỉ nổi màu tương phản',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#4b2e05',
                secondaryColor: null,
                heelHeight: 2.5,
                durabilityRating: 4.7,
                releaseYear: 2023
            },
            {
                rootProductId: 25,
                categoryId: 4,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Da nhân tạo',
                closureType: 'Trượt (Slip-On)',
                toeShape: 'Nhọn vừa cổ điển',
                waterResistant: 'Có khả năng kháng nước nhẹ',
                breathability: 'Trung bình',
                pattern: 'Thiết kế tối giản, đường may tinh tế tạo vẻ sang trọng',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#2b2b2b',
                secondaryColor: null,
                heelHeight: 3.0,
                durabilityRating: 4.8,
                releaseYear: 2023
            },
            {
                rootProductId: 26,
                categoryId: 4,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Da nhân tạo',
                closureType: 'Trượt (Slip-On)',
                toeShape: 'Nhọn vừa sang trọng',
                waterResistant: 'Có khả năng kháng nước nhẹ',
                breathability: 'Trung bình',
                pattern: 'Thiết kế trơn cổ điển, viền chỉ may tinh tế tạo điểm nhấn',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#000000',
                secondaryColor: null,
                heelHeight: 3.0,
                durabilityRating: 4.8,
                releaseYear: 2023
            },
            {
                rootProductId: 27,
                categoryId: 2,
                gender: ShoeGender.MALE,
                upperMaterial: 'Vải Nylon + Da tổng hợp',
                soleMaterial: 'Cao su chống trượt',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây Velcro điều chỉnh được',
                toeShape: 'Mở rộng (Open-Toe)',
                waterResistant: 'Có',
                breathability: 'Tốt',
                pattern: "Thiết kế thể thao, tối giản với logo Biti's Hunter nổi bật",
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#000000',
                secondaryColor: null,
                heelHeight: 2.0,
                durabilityRating: 4.5,
                releaseYear: 2023
            },
            {
                rootProductId: 28,
                categoryId: 2,
                gender: ShoeGender.MALE,
                upperMaterial: 'Vải dệt tổng hợp + Da PU',
                soleMaterial: 'Cao su chống trượt',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây Velcro điều chỉnh được',
                toeShape: 'Mở rộng (Open-Toe)',
                waterResistant: 'Có',
                breathability: 'Tốt',
                pattern: "Thiết kế lấy cảm hứng từ phiên bản Dune với màu sắc tinh tế và logo Biti's Hunter nổi bật",
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#f0f0f0',
                secondaryColor: '#d3d3d3',
                heelHeight: 2.2,
                durabilityRating: 4.6,
                releaseYear: 2023
            },
            {
                rootProductId: 29,
                categoryId: 2,
                gender: ShoeGender.MALE,
                upperMaterial: 'Vải Nylon + Da PU cao cấp',
                soleMaterial: 'Cao su chống trượt với thiết kế rãnh sâu',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây Velcro điều chỉnh dễ dàng',
                toeShape: 'Mở rộng (Open-Toe)',
                waterResistant: 'Có',
                breathability: 'Tốt',
                pattern: "Thiết kế thể thao, phối màu nâu mạnh mẽ với logo Biti's Hunter nổi bật",
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#8b4513',
                secondaryColor: null,
                heelHeight: 2.5,
                durabilityRating: 4.7,
                releaseYear: 2023
            },
            {
                rootProductId: 30,
                categoryId: 2,
                gender: ShoeGender.MALE,
                upperMaterial: 'Vải dệt Nylon + Da tổng hợp cao cấp',
                soleMaterial: 'Cao su chống trượt',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây Velcro điều chỉnh được',
                toeShape: 'Mở rộng (Open-Toe)',
                waterResistant: 'Có',
                breathability: 'Tốt',
                pattern: "Thiết kế tối giản với màu xám tinh tế và logo Biti's Hunter rõ ràng",
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#808080',
                secondaryColor: null,
                heelHeight: 2.0,
                durabilityRating: 4.6,
                releaseYear: 2023
            }
        ]
    })

    // --- Shoe Feature - Occasion Tag ---
    await prisma.shoeFeatureOccasionTag.createMany({
        data: [
            { shoeFeatureId: 11, occasionTagId: 1 },
            { shoeFeatureId: 11, occasionTagId: 2 },
            { shoeFeatureId: 11, occasionTagId: 7 },
            { shoeFeatureId: 11, occasionTagId: 8 },
            { shoeFeatureId: 12, occasionTagId: 1 },
            { shoeFeatureId: 12, occasionTagId: 2 },
            { shoeFeatureId: 12, occasionTagId: 3 },
            { shoeFeatureId: 12, occasionTagId: 7 },
            { shoeFeatureId: 12, occasionTagId: 8 },
            { shoeFeatureId: 13, occasionTagId: 1 },
            { shoeFeatureId: 13, occasionTagId: 2 },
            { shoeFeatureId: 13, occasionTagId: 3 },
            { shoeFeatureId: 13, occasionTagId: 7 },
            { shoeFeatureId: 13, occasionTagId: 8 },
            { shoeFeatureId: 14, occasionTagId: 1 },
            { shoeFeatureId: 14, occasionTagId: 2 },
            { shoeFeatureId: 14, occasionTagId: 5 },
            { shoeFeatureId: 14, occasionTagId: 8 },
            { shoeFeatureId: 15, occasionTagId: 1 },
            { shoeFeatureId: 15, occasionTagId: 2 },
            { shoeFeatureId: 15, occasionTagId: 4 },
            { shoeFeatureId: 15, occasionTagId: 8 },
            { shoeFeatureId: 15, occasionTagId: 9 },
            { shoeFeatureId: 16, occasionTagId: 1 },
            { shoeFeatureId: 16, occasionTagId: 2 },
            { shoeFeatureId: 16, occasionTagId: 5 },
            { shoeFeatureId: 16, occasionTagId: 7 },
            { shoeFeatureId: 16, occasionTagId: 8 },
            { shoeFeatureId: 17, occasionTagId: 3 },
            { shoeFeatureId: 17, occasionTagId: 6 },
            { shoeFeatureId: 17, occasionTagId: 10 },
            { shoeFeatureId: 18, occasionTagId: 3 },
            { shoeFeatureId: 18, occasionTagId: 6 },
            { shoeFeatureId: 18, occasionTagId: 10 },
            { shoeFeatureId: 19, occasionTagId: 3 },
            { shoeFeatureId: 19, occasionTagId: 6 },
            { shoeFeatureId: 19, occasionTagId: 10 },
            { shoeFeatureId: 20, occasionTagId: 3 },
            { shoeFeatureId: 20, occasionTagId: 6 },
            { shoeFeatureId: 20, occasionTagId: 10 },
            { shoeFeatureId: 21, occasionTagId: 3 },
            { shoeFeatureId: 21, occasionTagId: 6 },
            { shoeFeatureId: 21, occasionTagId: 10 },
            { shoeFeatureId: 22, occasionTagId: 1 },
            { shoeFeatureId: 22, occasionTagId: 2 },
            { shoeFeatureId: 22, occasionTagId: 5 },
            { shoeFeatureId: 22, occasionTagId: 7 },
            { shoeFeatureId: 22, occasionTagId: 8 },
            { shoeFeatureId: 22, occasionTagId: 9 },
            { shoeFeatureId: 23, occasionTagId: 1 },
            { shoeFeatureId: 23, occasionTagId: 2 },
            { shoeFeatureId: 23, occasionTagId: 5 },
            { shoeFeatureId: 23, occasionTagId: 7 },
            { shoeFeatureId: 23, occasionTagId: 8 },
            { shoeFeatureId: 23, occasionTagId: 9 },
            { shoeFeatureId: 24, occasionTagId: 1 },
            { shoeFeatureId: 24, occasionTagId: 2 },
            { shoeFeatureId: 24, occasionTagId: 5 },
            { shoeFeatureId: 24, occasionTagId: 7 },
            { shoeFeatureId: 24, occasionTagId: 8 },
            { shoeFeatureId: 24, occasionTagId: 9 },
            { shoeFeatureId: 25, occasionTagId: 1 },
            { shoeFeatureId: 25, occasionTagId: 2 },
            { shoeFeatureId: 25, occasionTagId: 5 },
            { shoeFeatureId: 25, occasionTagId: 7 },
            { shoeFeatureId: 25, occasionTagId: 8 },
            { shoeFeatureId: 25, occasionTagId: 9 }
        ]
    })

    // --- Shoe Feature - Design Tag ---
    await prisma.shoeFeatureDesignTag.createMany({
        data: [
            { shoeFeatureId: 11, designTagId: 1 },
            { shoeFeatureId: 11, designTagId: 2 },
            { shoeFeatureId: 11, designTagId: 3 },
            { shoeFeatureId: 11, designTagId: 4 },
            { shoeFeatureId: 11, designTagId: 7 },
            { shoeFeatureId: 12, designTagId: 2 },
            { shoeFeatureId: 12, designTagId: 3 },
            { shoeFeatureId: 12, designTagId: 5 },
            { shoeFeatureId: 12, designTagId: 6 },
            { shoeFeatureId: 12, designTagId: 10 },
            { shoeFeatureId: 13, designTagId: 1 },
            { shoeFeatureId: 13, designTagId: 2 },
            { shoeFeatureId: 13, designTagId: 3 },
            { shoeFeatureId: 13, designTagId: 5 },
            { shoeFeatureId: 13, designTagId: 6 },
            { shoeFeatureId: 14, designTagId: 3 },
            { shoeFeatureId: 14, designTagId: 5 },
            { shoeFeatureId: 14, designTagId: 6 },
            { shoeFeatureId: 14, designTagId: 8 },
            { shoeFeatureId: 14, designTagId: 10 },
            { shoeFeatureId: 14, designTagId: 11 },
            { shoeFeatureId: 15, designTagId: 1 },
            { shoeFeatureId: 15, designTagId: 5 },
            { shoeFeatureId: 15, designTagId: 6 },
            { shoeFeatureId: 15, designTagId: 8 },
            { shoeFeatureId: 15, designTagId: 9 },
            { shoeFeatureId: 15, designTagId: 11 },
            { shoeFeatureId: 16, designTagId: 1 },
            { shoeFeatureId: 16, designTagId: 2 },
            { shoeFeatureId: 16, designTagId: 5 },
            { shoeFeatureId: 16, designTagId: 6 },
            { shoeFeatureId: 16, designTagId: 11 },
            { shoeFeatureId: 17, designTagId: 2 },
            { shoeFeatureId: 17, designTagId: 3 },
            { shoeFeatureId: 17, designTagId: 4 },
            { shoeFeatureId: 17, designTagId: 7 },
            { shoeFeatureId: 17, designTagId: 12 },
            { shoeFeatureId: 18, designTagId: 1 },
            { shoeFeatureId: 18, designTagId: 2 },
            { shoeFeatureId: 18, designTagId: 3 },
            { shoeFeatureId: 18, designTagId: 4 },
            { shoeFeatureId: 18, designTagId: 7 },
            { shoeFeatureId: 18, designTagId: 12 },
            { shoeFeatureId: 19, designTagId: 2 },
            { shoeFeatureId: 19, designTagId: 3 },
            { shoeFeatureId: 19, designTagId: 4 },
            { shoeFeatureId: 19, designTagId: 7 },
            { shoeFeatureId: 19, designTagId: 12 },
            { shoeFeatureId: 20, designTagId: 2 },
            { shoeFeatureId: 20, designTagId: 3 },
            { shoeFeatureId: 20, designTagId: 4 },
            { shoeFeatureId: 20, designTagId: 7 },
            { shoeFeatureId: 20, designTagId: 12 },
            { shoeFeatureId: 21, designTagId: 1 },
            { shoeFeatureId: 21, designTagId: 2 },
            { shoeFeatureId: 21, designTagId: 4 },
            { shoeFeatureId: 21, designTagId: 7 },
            { shoeFeatureId: 21, designTagId: 12 },
            { shoeFeatureId: 22, designTagId: 3 },
            { shoeFeatureId: 22, designTagId: 5 },
            { shoeFeatureId: 22, designTagId: 6 },
            { shoeFeatureId: 22, designTagId: 10 },
            { shoeFeatureId: 22, designTagId: 11 },
            { shoeFeatureId: 22, designTagId: 12 },
            { shoeFeatureId: 23, designTagId: 3 },
            { shoeFeatureId: 23, designTagId: 5 },
            { shoeFeatureId: 23, designTagId: 6 },
            { shoeFeatureId: 23, designTagId: 10 },
            { shoeFeatureId: 23, designTagId: 11 },
            { shoeFeatureId: 23, designTagId: 12 },
            { shoeFeatureId: 24, designTagId: 3 },
            { shoeFeatureId: 24, designTagId: 5 },
            { shoeFeatureId: 24, designTagId: 6 },
            { shoeFeatureId: 24, designTagId: 10 },
            { shoeFeatureId: 24, designTagId: 11 },
            { shoeFeatureId: 24, designTagId: 12 },
            { shoeFeatureId: 25, designTagId: 3 },
            { shoeFeatureId: 25, designTagId: 5 },
            { shoeFeatureId: 25, designTagId: 6 },
            { shoeFeatureId: 25, designTagId: 10 },
            { shoeFeatureId: 25, designTagId: 11 },
            { shoeFeatureId: 25, designTagId: 12 }
        ]
    })
}
