import { PrismaClient, ShoeGender } from '@prisma/client'
import { generateProductBarcode } from '../../src/utils/stringHelpers'

export const seedProducts = async (prisma: PrismaClient) => {
    // --- Root Products ---
    await prisma.rootProduct.createMany({
        data: [
            {
                brandId: 4,
                name: "Dép Sandal Biti's Nam Màu Nâu BEM002700NAU",
                slug: "dep-sandal-biti's-nam-mau-nau-bem002700nau",
                description:
                    "Dép Sandal Biti's Nam Màu Nâu BEM002700NAU mang thiết kế đơn giản nhưng mạnh mẽ với tông màu nâu ấm áp, dễ dàng kết hợp với nhiều trang phục. Chất liệu cao cấp bền bỉ, cùng đế cao su chống trơn giúp bạn di chuyển thoải mái và tự tin. Kiểu dáng mở thoáng khí, phù hợp cho những ngày hè năng động hoặc dạo phố. Lựa chọn lý tưởng cho phong cách giản dị nhưng vẫn đầy cuốn hút.",
                price: 275000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 1,
                name: 'J Balvin x Air Jordan 1 High',
                slug: 'j-balvin-x-air-jordan-1-high',
                description:
                    'J Balvin x Air Jordan 1 High là sự kết hợp độc đáo giữa phong cách thời trang của J Balvin và huyền thoại Air Jordan. Đôi giày nổi bật với phối màu rực rỡ và chi tiết bắt mắt, mang đậm ảnh hưởng văn hóa Latin. Chất liệu cao cấp, đế Air-Sole đem lại sự thoải mái và độ bền lâu dài. Một đôi giày lý tưởng cho những ai yêu thích sự cá tính, khác biệt và phong cách đường phố.',
                price: 5590000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 2,
                name: 'Adidas Adifom Supernova - Beige',
                slug: 'adidas-adifom-supernova-beige',
                description:
                    'Adidas Adifom Supernova - Beige mang thiết kế hiện đại với sắc beige trung tính, dễ dàng phối hợp với nhiều trang phục. Được làm từ chất liệu cao cấp, giày có phần đệm Eva nhẹ, tạo cảm giác êm ái và thoải mái khi di chuyển. Phần đế cao su bền bỉ giúp tăng độ bám, thích hợp cho các hoạt động thể thao và dạo phố. Một lựa chọn hoàn hảo cho những ai yêu thích sự tối giản nhưng vẫn nổi bật.',
                price: 1190000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 7,
                name: 'New Balance 1906 Utility - Eclipse',
                slug: 'new-balance-1906-utility-eclipse',
                description:
                    'New Balance 1906 Utility - Eclipse mang thiết kế thể thao mạnh mẽ với tông màu Eclipse đen huyền bí, dễ dàng kết hợp với nhiều phong cách. Chất liệu cao cấp cùng đệm ABZORB mang lại sự thoải mái tối đa và giảm chấn hiệu quả. Đế ngoài cao su bền bỉ giúp tăng độ bám, phù hợp cho cả chạy bộ và sử dụng hàng ngày. Lựa chọn lý tưởng cho những ai yêu thích sự kết hợp giữa hiệu năng và thời trang.',
                price: 2250000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 7,
                name: 'New Balance 2002R - Great Plains',
                slug: 'new-balance-2002r-great-plains',
                description:
                    'New Balance 2002R - Great Plains mang thiết kế cổ điển với tông màu ấm áp, lấy cảm hứng từ vẻ đẹp của vùng đất Great Plains. Đôi giày được làm từ chất liệu da và vải lưới cao cấp, kết hợp công nghệ đệm ABZORB và SBS giúp giảm chấn tối ưu, mang lại cảm giác êm ái khi di chuyển. Đế cao su bền bỉ, phù hợp cho cả hoạt động thể thao lẫn dạo phố. Lựa chọn hoàn hảo cho phong cách năng động và thoải mái.',
                price: 2000000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 7,
                name: 'New Balance 2002R - Off White',
                slug: 'new-balance-2002r-off-white',
                description:
                    'New Balance 2002R - Off White sở hữu thiết kế tinh tế với màu sắc trung tính off-white dễ dàng kết hợp cùng nhiều trang phục. Chất liệu da và vải lưới cao cấp kết hợp với công nghệ đệm ABZORB mang đến sự thoải mái và hỗ trợ tối ưu cho đôi chân. Đế cao su bền bỉ, giúp tăng cường độ bám và độ ổn định. Lý tưởng cho những ai yêu thích sự kết hợp giữa phong cách cổ điển và hiện đại.',
                price: 2000000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 7,
                name: 'New Balance 327 - Blue',
                slug: 'new-balance-327-blue',
                description:
                    'New Balance 327 - Blue mang phong cách retro hiện đại với tông xanh nổi bật, lấy cảm hứng từ những đôi giày chạy thập niên 70. Phần upper kết hợp giữa da lộn và vải Nylon nhẹ, mang lại cảm giác thoáng khí và thoải mái. Đế ngoài răng cưa đặc trưng giúp tăng độ bám và tạo điểm nhấn độc đáo. Lựa chọn hoàn hảo cho những ai yêu thích sự năng động, trẻ trung và khác biệt.',
                price: 1450000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 7,
                name: 'New Balance 413 - Navy',
                slug: 'new-balance-413-navy',
                description:
                    'New Balance 413 - Navy mang thiết kế đơn giản, hiện đại với tông xanh navy thanh lịch và dễ phối đồ. Phần upper làm từ vải mesh thoáng khí kết hợp đế đệm Eva nhẹ, mang lại cảm giác êm ái và linh hoạt khi di chuyển. Đế ngoài cao su bền bỉ giúp tăng độ bám và ổn định. Lý tưởng cho những ai yêu thích phong cách thể thao tối giản, thoải mái và năng động mỗi ngày.',
                price: 745000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 7,
                name: 'New Balance 550 - Sea Salt / Multi',
                slug: 'new-balance-550-sea-salt-multi',
                description:
                    'New Balance 550 - Sea Salt / Multi mang phong cách cổ điển pha lẫn hiện đại với phối màu Sea Salt tinh tế cùng điểm nhấn đa sắc trẻ trung. Thân giày làm từ da cao cấp kết hợp lưới thoáng khí, mang lại cảm giác mềm mại và thoải mái. Đế cao su dày dặn, bám chắc, phù hợp cho cả di chuyển hàng ngày lẫn hoạt động năng động. Một lựa chọn hoàn hảo cho những ai yêu phong cách retro tinh tế và cá tính.',
                price: 1150000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 7,
                name: 'New Balance Fresh Foam Arishi v3 Slip Resistant - Magenta',
                slug: 'new-balance-fresh-foam-arishi-v3-slip-resistant-magenta',
                description:
                    'New Balance Fresh Foam Arishi v3 Slip Resistant - Magenta mang thiết kế hiện đại với tông hồng tím nổi bật, đầy năng lượng. Trang bị công nghệ đệm Fresh Foam giúp giảm chấn tối ưu và mang lại cảm giác êm ái suốt ngày dài. Đế ngoài chống trơn trượt, đảm bảo độ bám và an toàn khi di chuyển. Chất liệu lưới thoáng khí giúp chân luôn khô thoáng. Lý tưởng cho phong cách năng động, thoải mái và thời trang.',
                price: 895000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 7,
                name: 'New Balance Fresh Foam ROAV - Black / Light Aluminum',
                slug: 'new-balance-fresh-foam-roav-black-light-aluminum',
                description:
                    'New Balance Fresh Foam ROAV - Black / Light Aluminum mang thiết kế năng động, hiện đại với phối màu đen và xám tinh tế. Phần đệm Fresh Foam nhẹ và êm ái mang lại cảm giác di chuyển mượt mà, giảm chấn hiệu quả trong mỗi bước chạy. Thân giày làm từ vải mesh co giãn, thoáng khí, ôm chân hoàn hảo. Đế ngoài bền bỉ, chống trượt, phù hợp cho cả tập luyện lẫn sử dụng hằng ngày.',
                price: 895000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 7,
                name: 'New Balance FuelCell Rebel v5 - Black / Castlerock / Silver Metallic',
                slug: 'new-balance-fuelcell-rebel-v5-black-castlerock-silver-metallic',
                description:
                    'New Balance FuelCell Rebel v5 - Black / Castlerock / Silver Metallic mang thiết kế hiện đại, tối ưu cho hiệu suất chạy bộ tốc độ cao. Phối màu đen - xám - bạc mạnh mẽ, tôn lên vẻ năng động và thể thao. Công nghệ đệm FuelCell mang lại cảm giác bật nảy, phản hồi nhanh và cực kỳ nhẹ. Phần upper mesh thoáng khí giúp ôm chân thoải mái, hỗ trợ di chuyển linh hoạt. Lựa chọn hoàn hảo cho người yêu tốc độ và phong cách.',
                price: 2400000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 4,
                name: "Giày Cao Gót Biti's Nữ Màu Trắng BFW006888TRG",
                slug: "giay-cao-got-biti's-nu-mau-trang-bfw006888trg",
                description:
                    "Giày Cao Gót Biti's Nữ Màu Trắng BFW006888TRG sở hữu thiết kế mũi nhọn thanh thoát, quai hậu co giãn nhẹ ôm chân vừa vặn, tạo điểm nhấn tinh tế cho đôi chân. Chất liệu PU cao cấp với hoa văn chìm sang trọng, bền màu theo thời gian và dễ vệ sinh. Đế giày cao vừa phải (~5cm), tạo dáng thanh mảnh nhưng vẫn đảm bảo độ vững chắc và êm ái khi sải bước.",
                price: 495000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Sandal Cao Gót Biti's Nữ Màu Đen BFW006188DEN",
                slug: "sandal-cao-got-biti's-nu-mau-den-bfw006188den",
                description:
                    "Giày Sandal Cao Gót Biti's Nữ Màu Đen BFW006188DEN mang thiết kế hiện đại với tông đen cổ điển dễ phối đồ. Điểm nổi bật là quai ngang bản lớn ôm mu chân nhẹ nhàng và gót vuông cao khoảng 5 cm giúp tôn dáng và giữ thăng bằng tốt. Chất liệu da tổng hợp mềm mại cùng đế cao su chống trượt mang lại sự thoải mái và ổn định suốt cả ngày. Ideal cho phong cách công sở và các dịp trang trọng.",
                price: 465000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: 'Giày Thời Trang Nữ Gosto GFW018788',
                slug: 'giay-thoi-trang-nu-gosto-gfw018788',
                description:
                    'Giày Thời Trang Nữ Gosto GFW018788 mang nét hiện đại và thời thượng với thiết kế nâng cấp từ dòng classic. Thân giày được chế tác tinh xảo từ chất liệu da tổng hợp cao cấp, phối hợp đường may tỉ mỉ, tạo sự sang trọng. Màu sắc trẻ trung dễ phối đồ, thích hợp cho cả ngày dài năng động và buổi tối dạo phố. Một lựa chọn hoàn hảo cho cô nàng yêu phong cách khác biệt.',
                price: 599000,
                isAccessory: false,
                createdBy: 2
            }
        ]
    })

    // --- Product Images ---
    await prisma.productImage.createMany({
        data: [
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348366/product/bem002700nau__1_gwsvqj.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348366/product/bem002700nau__2_zrxef1.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348366/product/bem002700nau__3_zejc1o.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348366/product/bem002700nau__4_bjixje.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348370/product/bem002700nau__5_mnydtx.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348370/product/bem002700nau__6_csnccf.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348372/product/bem002700nau__7_v2msfj.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348373/product/bem002700nau__8_oyduah.jpg' },
            { rootProductId: 31, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760348375/product/bem002700nau__9_oa24jw.jpg' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370053/product/j-balvin-x-air-jordan_1_oz4biq.jpg' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370053/product/j-balvin-x-air-jordan_2_tfhrtr.jpg' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370054/product/j-balvin-x-air-jordan_3_l9olrj.jpg' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370054/product/j-balvin-x-air-jordan_4_dt8xya.jpg' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370060/product/j-balvin-x-air-jordan_5_ucppue.jpg' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370057/product/j-balvin-x-air-jordan_6_wsjiv7.jpg' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370064/product/j-balvin-x-air-jordan_7_tjjsju.png' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370059/product/j-balvin-x-air-jordan_8_kxrl1n.png' },
            { rootProductId: 32, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760370059/product/j-balvin-x-air-jordan_9_iqwlws.png' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376538/product/adidas-adifom_1_kwtaa5.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376538/product/adidas-adifom_2_zplnws.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376538/product/adidas-adifom_3_nubdq2.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376538/product/adidas-adifom_4_ardkss.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376538/product/adidas-adifom_5_nggnub.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376539/product/adidas-adifom_6_jivxcj.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376539/product/adidas-adifom_7_w3a2op.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376539/product/adidas-adifom_8_jop6ql.jpg' },
            { rootProductId: 33, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760376547/product/adidas-adifom_9_oqbgfv.jpg' },
            { rootProductId: 34, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760457476/product/new-balance-1906_1_swxqzh.jpg' },
            { rootProductId: 34, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760457525/product/new-balance-1906_2_bew7dw.jpg' },
            { rootProductId: 34, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760457525/product/new-balance-1906_3_wo7bde.jpg' },
            { rootProductId: 34, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760457526/product/new-balance-1906_4_zsi6hc.jpg' },
            { rootProductId: 34, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760457526/product/new-balance-1906_5_hbkcti.jpg' },
            { rootProductId: 35, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760458583/product/new-balance-2002r_1_xxcpyp.jpg' },
            { rootProductId: 35, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760458584/product/new-balance-2002r_2_sssmh9.jpg' },
            { rootProductId: 35, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760458583/product/new-balance-2002r_3_jysxqx.jpg' },
            { rootProductId: 35, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760458583/product/new-balance-2002r_4_ebzvz2.jpg' },
            { rootProductId: 35, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760458584/product/new-balance-2002r_5_q7tbhr.jpg' },
            { rootProductId: 36, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760460268/product/new-balance-2002r_w_1_d7fx4h.jpg' },
            { rootProductId: 36, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760460268/product/new-balance-2002r_w_2_d5lmbe.jpg' },
            { rootProductId: 36, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760460269/product/new-balance-2002r_w_3_g0fyuu.jpg' },
            { rootProductId: 36, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760460269/product/new-balance-2002r_w_4_qjcetp.jpg' },
            { rootProductId: 36, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760460269/product/new-balance-2002r_w_5_ki9kym.jpg' },
            { rootProductId: 36, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760460271/product/new-balance-2002r_w_6_rnwa5j.jpg' },
            { rootProductId: 36, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760460274/product/new-balance-2002r_w_7_uce88e.jpg' },
            { rootProductId: 37, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493025/product/new-balance-327_1_bca76z.jpg' },
            { rootProductId: 37, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493025/product/new-balance-327_2_fat7hl.jpg' },
            { rootProductId: 37, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493025/product/new-balance-327_3_msq9fb.jpg' },
            { rootProductId: 37, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493025/product/new-balance-327_4_sahmng.jpg' },
            { rootProductId: 37, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493025/product/new-balance-327_5_tplyoh.jpg' },
            { rootProductId: 37, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493025/product/new-balance-327_6_lhsl1t.jpg' },
            { rootProductId: 38, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493814/product/new-balance-413_1_xntsss.jpg' },
            { rootProductId: 38, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493814/product/new-balance-413_2_capyuy.jpg' },
            { rootProductId: 38, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493821/product/new-balance-413_3_qqovtw.jpg' },
            { rootProductId: 38, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493814/product/new-balance-413_4_w8ezav.jpg' },
            { rootProductId: 38, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493814/product/new-balance-413_5_gsgfzp.jpg' },
            { rootProductId: 38, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760493815/product/new-balance-413_6_qflmgr.jpg' },
            { rootProductId: 39, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760494484/product/new-balance-550_1_rzudhk.jpg' },
            { rootProductId: 39, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760494483/product/new-balance-550_2_bvnngd.jpg' },
            { rootProductId: 39, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760494484/product/new-balance-550_3_ecbyng.jpg' },
            { rootProductId: 39, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760494484/product/new-balance-550_4_ypxpoj.jpg' },
            { rootProductId: 39, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760494484/product/new-balance-550_5_ncyhii.jpg' },
            { rootProductId: 39, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760494484/product/new-balance-550_6_mcdiqj.jpg' },
            {
                rootProductId: 40,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760495349/product/new-balance-fresh-foam-arish_1_hvripf.jpg'
            },
            {
                rootProductId: 40,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760495358/product/new-balance-fresh-foam-arish_2_eu1klw.jpg'
            },
            {
                rootProductId: 40,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760495359/product/new-balance-fresh-foam-arish_3_vmvlcf.jpg'
            },
            {
                rootProductId: 40,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760495359/product/new-balance-fresh-foam-arish_4_hyy42m.jpg'
            },
            {
                rootProductId: 40,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760495360/product/new-balance-fresh-foam-arish_5_cc4pux.jpg'
            },
            {
                rootProductId: 40,
                url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760495360/product/new-balance-fresh-foam-arish_6_bhmbgl.jpg'
            },
            { rootProductId: 41, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496227/product/new-balance-fresh-foam_1_riozis.jpg' },
            { rootProductId: 41, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496227/product/new-balance-fresh-foam_2_ctufvb.jpg' },
            { rootProductId: 41, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496228/product/new-balance-fresh-foam_3_mcq9kk.jpg' },
            { rootProductId: 41, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496228/product/new-balance-fresh-foam_4_pzo9g0.jpg' },
            { rootProductId: 41, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496229/product/new-balance-fresh-foam_5_a8197s.jpg' },
            { rootProductId: 42, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496962/product/new-balance-fuelcell_1_dytxlw.jpg' },
            { rootProductId: 42, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496962/product/new-balance-fuelcell_2_nhgec9.jpg' },
            { rootProductId: 42, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496963/product/new-balance-fuelcell_3_wwou80.jpg' },
            { rootProductId: 42, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496963/product/new-balance-fuelcell_4_gy4nnv.jpg' },
            { rootProductId: 42, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496963/product/new-balance-fuelcell_5_koi6ao.jpg' },
            { rootProductId: 42, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760496967/product/new-balance-fuelcell_6_wgoawx.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225798/product/bfw006888trg__1_tmnawe.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225797/product/bfw006888trg__2_vbgnj6.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225799/product/bfw006888trg__3_uwfx5e.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225797/product/bfw006888trg__4_jyhsbi.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225798/product/bfw006888trg__5_rm6sck.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225799/product/bfw006888trg__6_fss1nh.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225797/product/bfw006888trg__7_mdshfu.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225798/product/bfw006888trg__8_djhb31.jpg' },
            { rootProductId: 43, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761225798/product/bfw006888trg__9_c03tml.jpg' },
            { rootProductId: 44, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761226774/product/sandal-caogot-bitis_1_zgifln.jpg' },
            { rootProductId: 44, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761226774/product/sandal-caogot-bitis_2_ryvxbc.jpg' },
            { rootProductId: 44, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761226775/product/sandal-caogot-bitis_3_wrhv0g.jpg' },
            { rootProductId: 44, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761226775/product/sandal-caogot-bitis_4_gxrkwk.jpg' },
            { rootProductId: 44, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761226777/product/sandal-caogot-bitis_5_kkjxhj.jpg' },
            { rootProductId: 44, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761226775/product/sandal-caogot-bitis_6_vtehhe.jpg' },
            { rootProductId: 44, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761226776/product/sandal-caogot-bitis_7_rqjyli.jpg' },
            { rootProductId: 45, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761227784/product/giay-gosto-1_ppc43l.jpg' },
            { rootProductId: 45, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761227784/product/giay-gosto-2_nikoud.jpg' },
            { rootProductId: 45, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761227784/product/giay-gosto-3_exagu6.jpg' },
            { rootProductId: 45, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761227784/product/giay-gosto-4_uuijva.jpg' },
            { rootProductId: 45, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1761227785/product/giay-gosto-5_kcfymw.jpg' }
        ]
    })

    // --- Product Items ---
    await prisma.productItem.createMany({
        data: [
            { rootProductId: 31, size: '39', stock: 20, barcode: '2038070324755' },
            { rootProductId: 31, size: '40', stock: 23, barcode: '2090821148317' },
            { rootProductId: 31, size: '41', stock: 30, barcode: '2027918539734' },
            { rootProductId: 31, size: '42', stock: 24, barcode: '2004254291298' },
            { rootProductId: 31, size: '43', stock: 25, barcode: '2018258431758' },
            { rootProductId: 31, size: '44', stock: 20, barcode: '2096051674244' },
            { rootProductId: 32, size: '40', stock: 12, barcode: '2066685285932' },
            { rootProductId: 32, size: '41', stock: 20, barcode: '2023756856712' },
            { rootProductId: 32, size: '42', stock: 26, barcode: '2068909850162' },
            { rootProductId: 32, size: '42.5', stock: 10, barcode: '2052796056813' },
            { rootProductId: 32, size: '43', stock: 21, barcode: '2054213859298' },
            { rootProductId: 33, size: '39', stock: 20, barcode: '2082960910474' },
            { rootProductId: 33, size: '40.5', stock: 21, barcode: '2011012706475' },
            { rootProductId: 33, size: '41', stock: 11, barcode: '2057857163660' },
            { rootProductId: 33, size: '42', stock: 20, barcode: '2021466881857' },
            { rootProductId: 33, size: '43', stock: 14, barcode: '2015290729249' },
            { rootProductId: 33, size: '44', stock: 22, barcode: '2029187034873' },
            { rootProductId: 33, size: '44.5', stock: 5, barcode: '2034950670851' },
            { rootProductId: 34, size: '39', stock: 24, barcode: '2029361805640' },
            { rootProductId: 34, size: '40', stock: 16, barcode: '2066584530225' },
            { rootProductId: 34, size: '40.5', stock: 25, barcode: '2053405196425' },
            { rootProductId: 34, size: '41', stock: 25, barcode: '2022534801425' },
            { rootProductId: 34, size: '42', stock: 30, barcode: '2018806399387' },
            { rootProductId: 35, size: '38.5', stock: 20, barcode: '2045413874297' },
            { rootProductId: 35, size: '39', stock: 30, barcode: '2051824072665' },
            { rootProductId: 35, size: '40', stock: 10, barcode: '2071641716054' },
            { rootProductId: 35, size: '40.5', stock: 15, barcode: '2080897455990' },
            { rootProductId: 35, size: '41', stock: 20, barcode: '2042095959861' },
            { rootProductId: 35, size: '42', stock: 23, barcode: '2014262287343' },
            { rootProductId: 35, size: '42.5', stock: 10, barcode: '2001556232080' },
            { rootProductId: 35, size: '43', stock: 19, barcode: '2008762498736' },
            { rootProductId: 35, size: '44', stock: 20, barcode: '2081962286655' },
            { rootProductId: 35, size: '45', stock: 10, barcode: '2029972447017' },
            { rootProductId: 36, size: '38.5', stock: 15, barcode: '2001559939788' },
            { rootProductId: 36, size: '39', stock: 20, barcode: '2015382912993' },
            { rootProductId: 36, size: '40', stock: 30, barcode: '2065498624440' },
            { rootProductId: 36, size: '40.5', stock: 10, barcode: '2045240082360' },
            { rootProductId: 36, size: '41', stock: 20, barcode: '2065081753243' },
            { rootProductId: 36, size: '42', stock: 25, barcode: '2009503301261' },
            { rootProductId: 36, size: '43', stock: 25, barcode: '2041865084925' },
            { rootProductId: 37, size: '38', stock: 20, barcode: '2041636595353' },
            { rootProductId: 37, size: '39', stock: 28, barcode: '2006310050436' },
            { rootProductId: 37, size: '39.5', stock: 20, barcode: '2014864363377' },
            { rootProductId: 37, size: '40', stock: 30, barcode: '2046249508820' },
            { rootProductId: 37, size: '41', stock: 25, barcode: '2088716735636' },
            { rootProductId: 37, size: '41.5', stock: 15, barcode: '2088366334500' },
            { rootProductId: 37, size: '42', stock: 17, barcode: '2012656179694' },
            { rootProductId: 38, size: '36.5', stock: 20, barcode: '2010313170084' },
            { rootProductId: 38, size: '37', stock: 25, barcode: '2092177188641' },
            { rootProductId: 38, size: '37.5', stock: 29, barcode: '2086496255771' },
            { rootProductId: 38, size: '38', stock: 21, barcode: '2035929357377' },
            { rootProductId: 38, size: '39', stock: 20, barcode: '2045520269658' },
            { rootProductId: 38, size: '40', stock: 30, barcode: '2043190939659' },
            { rootProductId: 39, size: '35', stock: 20, barcode: '2088123077190' },
            { rootProductId: 39, size: '36', stock: 30, barcode: '2082598892098' },
            { rootProductId: 39, size: '36.5', stock: 30, barcode: '2030768705365' },
            { rootProductId: 39, size: '37', stock: 20, barcode: '2011641847525' },
            { rootProductId: 39, size: '37.5', stock: 14, barcode: '2096740844798' },
            { rootProductId: 39, size: '38', stock: 30, barcode: '2064399349063' },
            { rootProductId: 39, size: '38.5', stock: 22, barcode: '2003748297099' },
            { rootProductId: 39, size: '39', stock: 10, barcode: '2013887281576' },
            { rootProductId: 39, size: '40', stock: 24, barcode: '2060652471618' },
            { rootProductId: 39, size: '41', stock: 21, barcode: '2096337677518' },
            { rootProductId: 40, size: '36', stock: 20, barcode: '2000484079965' },
            { rootProductId: 40, size: '37', stock: 30, barcode: '2027504282228' },
            { rootProductId: 40, size: '38', stock: 10, barcode: '2004881426094' },
            { rootProductId: 40, size: '39', stock: 15, barcode: '2055919968437' },
            { rootProductId: 40, size: '40', stock: 20, barcode: '2018012875880' },
            { rootProductId: 40, size: '41', stock: 10, barcode: '2060405057977' },
            { rootProductId: 41, size: '36', stock: 20, barcode: '2074726944823' },
            { rootProductId: 41, size: '36.5', stock: 10, barcode: '2012479113646' },
            { rootProductId: 41, size: '37', stock: 30, barcode: '2092624710869' },
            { rootProductId: 41, size: '37.5', stock: 25, barcode: '2028753550762' },
            { rootProductId: 41, size: '38', stock: 30, barcode: '2001322259433' },
            { rootProductId: 41, size: '39', stock: 20, barcode: '2034993656812' },
            { rootProductId: 41, size: '40', stock: 15, barcode: '2055546658169' },
            { rootProductId: 41, size: '40.5', stock: 10, barcode: '2089127882230' },
            { rootProductId: 41, size: '41', stock: 20, barcode: '2042285950807' },
            { rootProductId: 41, size: '42', stock: 15, barcode: '2082313355167' },
            { rootProductId: 41, size: '43', stock: 25, barcode: '2039149750741' },
            { rootProductId: 41, size: '44', stock: 20, barcode: '2026272725920' },
            { rootProductId: 42, size: '39', stock: 10, barcode: '2075481323892' },
            { rootProductId: 42, size: '40', stock: 30, barcode: '2008372171326' },
            { rootProductId: 42, size: '41', stock: 25, barcode: '2016050886820' },
            { rootProductId: 42, size: '42', stock: 30, barcode: '2080398731210' },
            { rootProductId: 42, size: '43', stock: 18, barcode: '2084482138794' },
            { rootProductId: 42, size: '44', stock: 20, barcode: '2075639377876' },
            { rootProductId: 43, size: '35', stock: 20, barcode: '2080057372136' },
            { rootProductId: 43, size: '36', stock: 30, barcode: '2029474281881' },
            { rootProductId: 43, size: '37', stock: 25, barcode: '2051197894352' },
            { rootProductId: 43, size: '38', stock: 18, barcode: '2039266242051' },
            { rootProductId: 43, size: '39', stock: 15, barcode: '2069852018975' },
            { rootProductId: 43, size: '40', stock: 20, barcode: '2051949924030' },
            { rootProductId: 44, size: '35', stock: 25, barcode: '2023288907753' },
            { rootProductId: 44, size: '36', stock: 25, barcode: '2028031578389' },
            { rootProductId: 44, size: '37', stock: 30, barcode: '2083304632267' },
            { rootProductId: 44, size: '38', stock: 25, barcode: '2092249759366' },
            { rootProductId: 44, size: '39', stock: 30, barcode: '2090948521185' },
            { rootProductId: 44, size: '40', stock: 10, barcode: '2013590786634' },
            { rootProductId: 45, size: '35', stock: 20, barcode: '2008913428773' },
            { rootProductId: 45, size: '36', stock: 30, barcode: '2018840252211' },
            { rootProductId: 45, size: '37', stock: 25, barcode: '2016474602624' },
            { rootProductId: 45, size: '38', stock: 20, barcode: '2096904449760' },
            { rootProductId: 45, size: '39', stock: 20, barcode: '2008333301205' }
        ]
    })

    // --- Shoe Features ---
    await prisma.shoeFeature.createMany({
        data: [
            {
                rootProductId: 31,
                categoryId: 2,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su chống trượt với thiết kế rãnh sâu',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây quai xỏ',
                toeShape: 'Mở rộng (Open-Toe)',
                waterResistant: 'Có',
                breathability: 'Tốt',
                pattern: 'Thiết kế đơn giản, phối màu nâu sang trọng với logo Biti’s ở quai',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#6b4f2d',
                secondaryColor: null,
                heelHeight: 2.2,
                durabilityRating: 4.7,
                releaseYear: 2023
            },
            {
                rootProductId: 32,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Vải Canvas Tie-Dye với các lớp da cắt răng cưa',
                soleMaterial: 'Cao su màu hồng nhạt',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế cầu vồng với các chi tiết cắt rách và đường viền lởm chởm, logo mặt cười thay thế Jumpman',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#1bb13d',
                secondaryColor: '#ff0000',
                heelHeight: 3.0,
                durabilityRating: 4.5,
                releaseYear: 2020
            },
            {
                rootProductId: 33,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Foam + Vải kỹ thuật tái chế',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Trượt (Slip-On)',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế tối giản lấy cảm hứng từ giày chạy, chi tiết 3-Stripes đúc',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#f5f0e6',
                secondaryColor: null,
                heelHeight: 2.5,
                durabilityRating: 4.3,
                releaseYear: 2025
            },
            {
                rootProductId: 34,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da lộn (Suede) + Vải tổng hợp',
                soleMaterial: 'Cao su chống trượt với công nghệ N-ergy và ABZORB SBS',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Có',
                breathability: 'Tốt',
                pattern: 'Thiết kế tối giản với phối màu đen và xanh đậm, logo N-Lock đặc trưng',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#23253a',
                secondaryColor: '#2a2a2a',
                heelHeight: 3.0,
                durabilityRating: 4.7,
                releaseYear: 2025
            },
            {
                rootProductId: 35,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da lộn (Suede) + Mesh + Da tổng hợp',
                soleMaterial: 'Cao su chống trượt với công nghệ N-ergy và ABZORB SBS',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế phối màu đất, lấy cảm hứng từ vùng đồng bằng Bắc Mỹ',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#9e7b5e',
                secondaryColor: '#6e6e6e',
                heelHeight: 3.0,
                durabilityRating: 4.7,
                releaseYear: 2025
            },
            {
                rootProductId: 36,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da lộn (Suede) + Mesh',
                soleMaterial: 'Cao su chống trượt với công nghệ N-ergy và ABZORB',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế tối giản với phối màu trắng ngà, logo N nổi bật',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#f5f5f5',
                secondaryColor: '#d3d3d3',
                heelHeight: 3.0,
                durabilityRating: 4.8,
                releaseYear: 2022
            },
            {
                rootProductId: 37,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da lộn (Suede) + Mesh',
                soleMaterial: 'Cao su + Đệm Eva',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: "Thiết kế retro lấy cảm hứng từ dòng 70's, logo N lớn giữa thân",
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#8cafc3',
                secondaryColor: '#ffffff',
                heelHeight: 3.5,
                durabilityRating: 4.5,
                releaseYear: 2020
            },
            {
                rootProductId: 38,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Lưới Mesh + Sợi tổng hợp',
                soleMaterial: 'Cao su + Đệm Eva (Fresh Foam / DynaSoft tùy phiên bản)',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế thể thao tối giản, phối màu navy với điểm nhấn logo N trắng',
                countryOfOrigin: 'Việt Nam / Trung Quốc',
                primaryColor: '#000080',
                secondaryColor: '#ffffff',
                heelHeight: 2.8,
                durabilityRating: 4.4,
                releaseYear: 2024
            },
            {
                rootProductId: 39,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da tổng hợp + Da lộn (Suede)',
                soleMaterial: 'Cao su + Đệm Eva',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế phối màu Sea Salt / Multi với chi tiết da lộn xám và điểm nhấn màu sắc nhẹ',
                countryOfOrigin: 'Việt Nam / Trung Quốc',
                primaryColor: '#f5f5f5',
                secondaryColor: '#a0a0a0',
                heelHeight: 3.0,
                durabilityRating: 4.6,
                releaseYear: 2025
            },
            {
                rootProductId: 40,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Lưới kỹ thuật + Lưới tổng hợp (Engineered Mesh / Synthetic)',
                soleMaterial: 'Cao su chống trượt + Midsole Foam (Fresh Foam)',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế slip-resistant với phối màu Magenta và chi tiết sắc tím / hồng đậm',
                countryOfOrigin: 'Việt Nam / Trung Quốc',
                primaryColor: '#d1351f',
                secondaryColor: '#800080',
                heelHeight: 2.8,
                durabilityRating: 4.5,
                releaseYear: 2023
            },
            {
                rootProductId: 41,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Lưới tổng hợp + Vải kỹ thuật (Synthetic Mesh / Textile)',
                soleMaterial: 'Cao su + Đệm Fresh Foam',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế hiện đại, phối màu Black / Light Aluminum',
                countryOfOrigin: 'Việt Nam / Trung Quốc',
                primaryColor: '#000000',
                secondaryColor: '#d3d3d3',
                heelHeight: 3.0,
                durabilityRating: 4.6,
                releaseYear: 2024
            },
            {
                rootProductId: 42,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Lưới kỹ thuật (Engineered Mesh) + Lưới ôm sát FantomFit Overlay',
                soleMaterial: 'Cao su + Đệm FuelCell (Peba / Eva Blend)',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế phối màu Black / Castlerock / Silver với các chi tiết phản quang và cấu trúc futurist',
                countryOfOrigin: 'Việt Nam / Trung Quốc',
                primaryColor: '#000000',
                secondaryColor: '#a9a9a9',
                heelHeight: 3.5,
                durabilityRating: 4.6,
                releaseYear: 2025
            },
            {
                rootProductId: 43,
                categoryId: 5,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'PU cao cấp với hoa văn chìm tinh tế',
                soleMaterial: 'Cao su bền chắc',
                liningMaterial: 'Da tổng hợp mềm mại',
                closureType: 'Quai sau co giãn',
                toeShape: 'Mũi nhọn',
                waterResistant: 'Không',
                breathability: 'Trung bình',
                pattern: 'Bề mặt trơn bóng với hoa văn chìm nhẹ nhàng',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#ffffff',
                secondaryColor: null,
                heelHeight: 5.0,
                durabilityRating: 4.5,
                releaseYear: 2025
            },
            {
                rootProductId: 44,
                categoryId: 5,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da tổng hợp cao cấp',
                soleMaterial: 'Cao su tổng hợp chống trượt',
                liningMaterial: 'Da nhân tạo mềm mại',
                closureType: 'Quai ngang bản lớn',
                toeShape: 'Mở (open-toe)',
                waterResistant: 'Không',
                breathability: 'Trung bình',
                pattern: 'Thiết kế tối giản, quai bản lớn ôm mu bàn chân, gót vuông cao khoảng 5 cm',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#000000',
                secondaryColor: null,
                heelHeight: 5.0,
                durabilityRating: 4.4,
                releaseYear: 2024
            },
            {
                rootProductId: 45,
                categoryId: 7,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da tổng hợp cao cấp bóng nhẹ',
                soleMaterial: 'Cao su chống trượt',
                liningMaterial: 'Vải tổng hợp mềm mại',
                closureType: 'Dây buộc',
                toeShape: 'Mũi nhọn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Thiết kế thanh lịch với phần gót ống cao và bề mặt da bóng',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#000000',
                secondaryColor: null,
                heelHeight: 6.0,
                durabilityRating: 4.3,
                releaseYear: 2024
            }
        ]
    })

    // --- Shoe Feature - Occasion Tag ---
    await prisma.shoeFeatureOccasionTag.createMany({
        data: [
            { shoeFeatureId: 26, occasionTagId: 1 },
            { shoeFeatureId: 26, occasionTagId: 2 },
            { shoeFeatureId: 26, occasionTagId: 5 },
            { shoeFeatureId: 26, occasionTagId: 7 },
            { shoeFeatureId: 26, occasionTagId: 8 },
            { shoeFeatureId: 26, occasionTagId: 9 },
            { shoeFeatureId: 27, occasionTagId: 1 },
            { shoeFeatureId: 27, occasionTagId: 2 },
            { shoeFeatureId: 27, occasionTagId: 8 },
            { shoeFeatureId: 28, occasionTagId: 1 },
            { shoeFeatureId: 28, occasionTagId: 2 },
            { shoeFeatureId: 28, occasionTagId: 4 },
            { shoeFeatureId: 28, occasionTagId: 5 },
            { shoeFeatureId: 28, occasionTagId: 9 },
            { shoeFeatureId: 29, occasionTagId: 1 },
            { shoeFeatureId: 29, occasionTagId: 2 },
            { shoeFeatureId: 29, occasionTagId: 4 },
            { shoeFeatureId: 29, occasionTagId: 5 },
            { shoeFeatureId: 29, occasionTagId: 8 },
            { shoeFeatureId: 29, occasionTagId: 9 },
            { shoeFeatureId: 30, occasionTagId: 1 },
            { shoeFeatureId: 30, occasionTagId: 2 },
            { shoeFeatureId: 30, occasionTagId: 4 },
            { shoeFeatureId: 30, occasionTagId: 5 },
            { shoeFeatureId: 30, occasionTagId: 8 },
            { shoeFeatureId: 30, occasionTagId: 9 },
            { shoeFeatureId: 31, occasionTagId: 1 },
            { shoeFeatureId: 31, occasionTagId: 2 },
            { shoeFeatureId: 31, occasionTagId: 4 },
            { shoeFeatureId: 31, occasionTagId: 5 },
            { shoeFeatureId: 31, occasionTagId: 8 },
            { shoeFeatureId: 31, occasionTagId: 9 },
            { shoeFeatureId: 32, occasionTagId: 1 },
            { shoeFeatureId: 32, occasionTagId: 2 },
            { shoeFeatureId: 32, occasionTagId: 4 },
            { shoeFeatureId: 32, occasionTagId: 5 },
            { shoeFeatureId: 32, occasionTagId: 8 },
            { shoeFeatureId: 32, occasionTagId: 9 },
            { shoeFeatureId: 33, occasionTagId: 1 },
            { shoeFeatureId: 33, occasionTagId: 2 },
            { shoeFeatureId: 33, occasionTagId: 4 },
            { shoeFeatureId: 33, occasionTagId: 5 },
            { shoeFeatureId: 33, occasionTagId: 8 },
            { shoeFeatureId: 33, occasionTagId: 9 },
            { shoeFeatureId: 34, occasionTagId: 1 },
            { shoeFeatureId: 34, occasionTagId: 2 },
            { shoeFeatureId: 34, occasionTagId: 4 },
            { shoeFeatureId: 34, occasionTagId: 5 },
            { shoeFeatureId: 34, occasionTagId: 8 },
            { shoeFeatureId: 34, occasionTagId: 9 },
            { shoeFeatureId: 35, occasionTagId: 1 },
            { shoeFeatureId: 35, occasionTagId: 2 },
            { shoeFeatureId: 35, occasionTagId: 4 },
            { shoeFeatureId: 35, occasionTagId: 5 },
            { shoeFeatureId: 35, occasionTagId: 8 },
            { shoeFeatureId: 35, occasionTagId: 9 },
            { shoeFeatureId: 36, occasionTagId: 1 },
            { shoeFeatureId: 36, occasionTagId: 2 },
            { shoeFeatureId: 36, occasionTagId: 4 },
            { shoeFeatureId: 36, occasionTagId: 5 },
            { shoeFeatureId: 36, occasionTagId: 8 },
            { shoeFeatureId: 36, occasionTagId: 9 },
            { shoeFeatureId: 37, occasionTagId: 4 },
            { shoeFeatureId: 37, occasionTagId: 5 },
            { shoeFeatureId: 37, occasionTagId: 8 },
            { shoeFeatureId: 37, occasionTagId: 9 },
            { shoeFeatureId: 38, occasionTagId: 3 },
            { shoeFeatureId: 38, occasionTagId: 6 },
            { shoeFeatureId: 38, occasionTagId: 10 },
            { shoeFeatureId: 39, occasionTagId: 3 },
            { shoeFeatureId: 39, occasionTagId: 6 },
            { shoeFeatureId: 39, occasionTagId: 10 },
            { shoeFeatureId: 40, occasionTagId: 2 },
            { shoeFeatureId: 40, occasionTagId: 3 },
            { shoeFeatureId: 40, occasionTagId: 6 },
            { shoeFeatureId: 40, occasionTagId: 10 }
        ]
    })

    // --- Shoe Feature - Design Tag ---
    await prisma.shoeFeatureDesignTag.createMany({
        data: [
            { shoeFeatureId: 26, designTagId: 3 },
            { shoeFeatureId: 26, designTagId: 5 },
            { shoeFeatureId: 26, designTagId: 6 },
            { shoeFeatureId: 26, designTagId: 10 },
            { shoeFeatureId: 26, designTagId: 11 },
            { shoeFeatureId: 26, designTagId: 12 },
            { shoeFeatureId: 27, designTagId: 3 },
            { shoeFeatureId: 27, designTagId: 5 },
            { shoeFeatureId: 27, designTagId: 6 },
            { shoeFeatureId: 27, designTagId: 8 },
            { shoeFeatureId: 27, designTagId: 10 },
            { shoeFeatureId: 27, designTagId: 11 },
            { shoeFeatureId: 28, designTagId: 2 },
            { shoeFeatureId: 28, designTagId: 3 },
            { shoeFeatureId: 28, designTagId: 8 },
            { shoeFeatureId: 28, designTagId: 9 },
            { shoeFeatureId: 28, designTagId: 10 },
            { shoeFeatureId: 28, designTagId: 11 },
            { shoeFeatureId: 29, designTagId: 3 },
            { shoeFeatureId: 29, designTagId: 5 },
            { shoeFeatureId: 29, designTagId: 6 },
            { shoeFeatureId: 29, designTagId: 9 },
            { shoeFeatureId: 29, designTagId: 10 },
            { shoeFeatureId: 29, designTagId: 11 },
            { shoeFeatureId: 29, designTagId: 12 },
            { shoeFeatureId: 30, designTagId: 3 },
            { shoeFeatureId: 30, designTagId: 5 },
            { shoeFeatureId: 30, designTagId: 6 },
            { shoeFeatureId: 30, designTagId: 9 },
            { shoeFeatureId: 30, designTagId: 10 },
            { shoeFeatureId: 30, designTagId: 11 },
            { shoeFeatureId: 30, designTagId: 12 },
            { shoeFeatureId: 31, designTagId: 3 },
            { shoeFeatureId: 31, designTagId: 5 },
            { shoeFeatureId: 31, designTagId: 6 },
            { shoeFeatureId: 31, designTagId: 9 },
            { shoeFeatureId: 31, designTagId: 10 },
            { shoeFeatureId: 31, designTagId: 11 },
            { shoeFeatureId: 31, designTagId: 12 },
            { shoeFeatureId: 32, designTagId: 1 },
            { shoeFeatureId: 32, designTagId: 2 },
            { shoeFeatureId: 32, designTagId: 5 },
            { shoeFeatureId: 32, designTagId: 6 },
            { shoeFeatureId: 32, designTagId: 9 },
            { shoeFeatureId: 32, designTagId: 10 },
            { shoeFeatureId: 33, designTagId: 2 },
            { shoeFeatureId: 33, designTagId: 3 },
            { shoeFeatureId: 33, designTagId: 5 },
            { shoeFeatureId: 33, designTagId: 6 },
            { shoeFeatureId: 33, designTagId: 9 },
            { shoeFeatureId: 33, designTagId: 10 },
            { shoeFeatureId: 34, designTagId: 1 },
            { shoeFeatureId: 34, designTagId: 2 },
            { shoeFeatureId: 34, designTagId: 3 },
            { shoeFeatureId: 34, designTagId: 5 },
            { shoeFeatureId: 34, designTagId: 6 },
            { shoeFeatureId: 34, designTagId: 9 },
            { shoeFeatureId: 34, designTagId: 10 },
            { shoeFeatureId: 34, designTagId: 11 },
            { shoeFeatureId: 35, designTagId: 3 },
            { shoeFeatureId: 35, designTagId: 5 },
            { shoeFeatureId: 35, designTagId: 6 },
            { shoeFeatureId: 35, designTagId: 9 },
            { shoeFeatureId: 35, designTagId: 10 },
            { shoeFeatureId: 35, designTagId: 11 },
            { shoeFeatureId: 36, designTagId: 3 },
            { shoeFeatureId: 36, designTagId: 5 },
            { shoeFeatureId: 36, designTagId: 6 },
            { shoeFeatureId: 36, designTagId: 8 },
            { shoeFeatureId: 36, designTagId: 9 },
            { shoeFeatureId: 36, designTagId: 10 },
            { shoeFeatureId: 36, designTagId: 11 },
            { shoeFeatureId: 37, designTagId: 3 },
            { shoeFeatureId: 37, designTagId: 5 },
            { shoeFeatureId: 37, designTagId: 6 },
            { shoeFeatureId: 37, designTagId: 8 },
            { shoeFeatureId: 37, designTagId: 9 },
            { shoeFeatureId: 37, designTagId: 10 },
            { shoeFeatureId: 37, designTagId: 11 },
            { shoeFeatureId: 38, designTagId: 2 },
            { shoeFeatureId: 38, designTagId: 3 },
            { shoeFeatureId: 38, designTagId: 4 },
            { shoeFeatureId: 38, designTagId: 7 },
            { shoeFeatureId: 38, designTagId: 12 },
            { shoeFeatureId: 39, designTagId: 2 },
            { shoeFeatureId: 39, designTagId: 3 },
            { shoeFeatureId: 39, designTagId: 4 },
            { shoeFeatureId: 39, designTagId: 7 },
            { shoeFeatureId: 39, designTagId: 12 },
            { shoeFeatureId: 40, designTagId: 3 },
            { shoeFeatureId: 40, designTagId: 4 },
            { shoeFeatureId: 40, designTagId: 6 },
            { shoeFeatureId: 40, designTagId: 7 },
            { shoeFeatureId: 40, designTagId: 12 }
        ]
    })
}
