import { PrismaClient, ShoeGender } from '@prisma/client'
import { generateProductBarcode } from '../../src/utils/stringHelpers'

export const seedProducts = async (prisma: PrismaClient) => {
    // --- Root Products ---
    await prisma.rootProduct.createMany({
        data: [
            {
                brandId: 8,
                name: 'Túi Xách Nhỏ JUNO TXN937 Heart Shaped Ivy',
                slug: 'tui-xach-nho-juno-txn937-heart-shaped-ivy',
                description:
                    'Túi Xách Nhỏ Heart Shaped Ivy từ JUNO - Thiết kế hình trái tim độc đáo, mang phong cách ngọt ngào và nữ tính. Chất liệu da tổng hợp cao cấp, bề mặt mịn đẹp và dễ bảo quản. Dây đeo dài linh hoạt - vừa có thể đeo chéo, vừa có thể xách tay. Nội thất nhỏ gọn nhưng đủ ngăn để đựng điện thoại, ví mini và vật dụng cá nhân thiết yếu. Phù hợp cho cả buổi hẹn hò nhẹ nhàng hoặc dạo phố sành điệu.',
                price: 749000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 8,
                name: 'Mắt Kính JUNO MK126 Circa',
                slug: 'mat-kinh-juno-mk126-circa',
                description:
                    'Mắt kính Circa từ JUNO - Thiết kế kim loại trẻ trung, cá tính với gọng chắc chắn, phù hợp để sử dụng khi dạo phố, du lịch hay các hoạt động ngoài trời. Sản phẩm mang tông màu nâu đen huyền bí, không chỉ toát nên sự quý phái mà còn thể hiện gu thời trang đẳng cấp. Sản phẩm được đi kèm hộp kính da PU chống nước và khăn lau tiện dụng.',
                price: 549000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 8,
                name: 'Giày Cao Gót JUNO CG07169 Phối Dây Đá Nhỏ',
                slug: 'giay-cao-got-juno-cg07169-phoi-day-da-nho',
                description:
                    'Giày cao gót JUNO CG07169 "Phối Dây Đá Nhỏ" - Thật không quá khi nói đây là đôi giày nổi bật với vẻ thanh lịch và sang trọng! Với quai đính đá nhỏ lấp lánh tinh tế. Gót cao vừa phải giúp tôn dáng nhưng vẫn thoải mái khi di chuyển, chất liệu da tổng hợp bền đẹp và dễ bảo quản. Lý tưởng để diện dự tiệc, công sở hoặc các buổi dạo phố thanh lịch.',
                price: 599000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 8,
                name: 'Giày Cao Gót JUNO CG05152 Mules Đắp Mũi Chéo',
                slug: 'giay-cao-got-juno-cg05152-mules-dap-mui-cheo',
                description:
                    'Giày cao gót JUNO CG05152 "Mules Đắp Mũi Chéo" - thiết kế mules hiện đại với phần mũi giày chéo tạo điểm nhấn thời trang. Gót cao nhẹ giúp tôn dáng nhưng vẫn giữ được sự thoải mái khi di chuyển. Chất liệu da tổng hợp cao cấp, bề mặt mịn, dễ phối trang phục đi làm, dạo phố hay dự tiệc.',
                price: 549000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 8,
                name: 'Giày Búp Bê JUNO BB03137 Thắt Eo',
                slug: 'giay-bup-be-juno-bb03137-that-eo',
                description:
                    'Giày búp bê JUNO BB03137 "Thắt Eo" - thiết kế nữ tính với phần eo thắt nhẹ mang lại điểm nhấn thanh lịch. Chất liệu da bền bỉ, bề mặt mịn màng và form ôm chân nhẹ nhàng. Đế thấp phù hợp mang cả ngày, dễ phối cùng trang phục công sở, dạo phố hay dự tiệc nhẹ nhàng.',
                price: 549000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 12,
                name: 'Giày Clog Unisex Crocs Echo Gum RO - Pink Caramel',
                slug: 'giay-clog-unisex-crocs-echo-gum-ro-pink-caramel',
                description:
                    'Crocs Echo Gum RO Clog - Pink Caramel: Đôi clog unisex siêu nhẹ với thân đúc bằng Croslite, đệm LiteRide mềm mại và đế cao su rắn chắc giúp tăng độ bám. Thiết kế độc đáo, thể thao, phù hợp mang mọi lúc với khả năng kháng nước và dễ vệ sinh. Màu Pink Caramel ngọt ngào nhưng vẫn cá tính, dễ phối đồ phong cách streetwear hoặc casual.',
                price: 2395000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 12,
                name: 'Giày Clog Unisex Crocs Classic Pokemon',
                slug: 'giay-clog-unisex-crocs-classic-pokemon',
                description:
                    'Crocs Classic Pokémon Clog - phiên bản hợp tác độc đáo giữa Crocs và Pokemon: mang họa tiết toàn bộ các nhân vật như Pikachu, Squirtle, Charmander và Bulbasaur; đi kèm charm Jibbitz đặc biệt. Thiết kế vẫn giữ nguyên đế Crocs nhẹ, thân chống nước, dễ vệ sinh và có dây gót xoay linh hoạt cho cảm giác ôm chân thoải mái.',
                price: 1995000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 12,
                name: 'Giày Clog Trẻ Em Crocs Classic Zootopia',
                slug: 'giay-clog-tre-em-crocs-classic-zootopia',
                description:
                    'Crocs Classic Zootopia Kids Clog - Đôi clog trẻ em siêu nhẹ với thiết kế lấy cảm hứng từ Zootopia 2, trang bị phụ kiện charm Jibbitz Judy Hopps & Nick Wilde sinh động. Quai gót xoay linh hoạt giúp cố định khi chạy nhảy, kết hợp công nghệ Iconic Crocs Comfort êm ái 360 độ - tuyệt vời cho những cuộc phiêu lưu năng động của bé.',
                price: 1695000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 12,
                name: 'Giày Clog Trẻ Em Crocs Toddler Classic Star Sparkle Shaker - Pink Milk',
                slug: 'giay-clog-tre-em-crocs-toddler-classic-star-sparkle-shaker-pink-milk',
                description:
                    'Crocs Toddler Classic Star Sparkle Shaker Clog - Pink Milk - Đôi clog trẻ em siêu nhẹ, thiết kế đế trong suốt chứa kim tuyến lắc theo bước đi, kết hợp chi tiết cầu vồng và ngôi sao đầy màu sắc. Quai gót xoay linh hoạt giúp cố định chắc chắn, lỗ thoáng khí tăng khả năng thở, và công nghệ Iconic Crocs Comfort mang lại sự êm ái toàn diện.',
                price: 1095000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 12,
                name: 'Set Jibbitz Charm Smurfs (5 chiếc)',
                slug: 'set-jibbitz-charm-smurfs-5-chiec',
                description:
                    'Set Jibbitz Charm Smurfs - Bộ charm trang trí chính hãng Crocs lấy cảm hứng từ “Xì-Trum” (Smurfs), gồm nhiều nhân vật biểu tượng như Papa Smurf, Smurfette, Handy Smurf… Thiết kế nhỏ gọn, dễ gắn vào các lỗ trên dép Crocs Classic - giúp cá nhân hóa giày theo phong cách vui nhộn, hoài niệm.',
                price: 725000,
                isAccessory: true,
                createdBy: 2
            },
            {
                brandId: 12,
                name: 'Set Jibbitz Charm Tom and Jerry (5 chiếc)',
                slug: 'set-jibbitz-charm-tom-and-jerry-5-chiec',
                description:
                    'Set Jibbitz Charm Tom and Jerry - bộ charm trang trí chính hãng Crocs lấy cảm hứng từ bộ phim hoạt hình kinh điển Tom & Jerry. Gồm các hình Tom, Jerry cùng các chi tiết vui nhộn như pho mát và tiếng "meo - gừ", được làm từ nhựa cao cấp, bền bỉ và an toàn khi gắn vào lỗ của dép Crocs. Thích hợp để cá nhân hóa Crocs theo phong cách retro, hài hước và năng động.',
                price: 725000,
                isAccessory: true,
                createdBy: 2
            },
            {
                brandId: 12,
                name: 'Set Jibbitz Charm The Simpsons (5 chiếc)',
                slug: 'set-jibbitz-charm-the-simpsons-5-chiec',
                description:
                    'Set Jibbitz Charm The Simpsons - Bộ charm trang trí chính hãng Crocs mang chủ đề The Simpsons với các hình icon của gia đình Simpson cùng các chi tiết vui nhộn. Thiết kế nhẹ, làm bằng nhựa bền, dễ gắn lên các lỗ trên giày Crocs Classic để cá nhân hóa phong cách theo cách "cartoon" cá tính và đáng yêu.',
                price: 725000,
                isAccessory: true,
                createdBy: 2
            },
            {
                brandId: 11,
                name: 'Converse Chuck Taylor All Star 1970s Hi Top - Đen',
                slug: 'converse-chuck-taylor-all-star-1970s-hi-top-den',
                description:
                    'Đôi sneaker cổ điển lấy cảm hứng từ thiết kế Chuck Taylor thập niên 70, được nâng cấp với chất liệu canvas dày hơn, đế cao su ngà mang hơi hướng vintage, và lót OrthoLite êm ái - mang lại cảm giác thoải mái hơn rất nhiều so với dòng All Star truyền thống. Form chắc chắn, đường may tỉ mỉ, thích hợp phối đồ retro hoặc streetwear năng động.',
                price: 1800000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 11,
                name: 'Converse Chuck Taylor All Star 1970s Hi Top - Trắng',
                slug: 'converse-chuck-taylor-all-star-1970s-hi-top-trang',
                description:
                    'Đôi sneaker cổ điển lấy cảm hứng từ thiết kế Chuck Taylor thập niên 70, được nâng cấp với chất liệu canvas dày hơn, đế cao su ngà mang hơi hướng vintage, và lót OrthoLite êm ái - mang lại cảm giác thoải mái hơn rất nhiều so với dòng All Star truyền thống. Form chắc chắn, đường may tỉ mỉ, thích hợp phối đồ retro hoặc streetwear năng động.',
                price: 1800000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 11,
                name: 'Converse Chuck Taylor All Star Classic Low Top - Xanh Navy',
                slug: 'converse-chuck-taylor-all-star-classic-low-top-xanh-navy',
                description:
                    'Đôi sneaker cổ thấp kinh điển với phần upper làm từ vải canvas xanh navy thanh lịch, lót OrthoLite mang lại độ êm và thoáng khí. Đế cao su hình kim cương không trượt, logo "All Star" truyền thống ở gót tạo dấu ấn nhận diện. Thiết kế unisex, dễ phối với nhiều phong cách từ streetwear đến casual hàng ngày.',
                price: 1400000,
                isAccessory: false,
                createdBy: 1
            }
        ]
    })

    // --- Product Images ---
    await prisma.productImage.createMany({
        data: [
            { rootProductId: 61, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763915970/product/heart_shaped_ivy_1_sdnmoq.jpg' },
            { rootProductId: 61, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763915970/product/heart_shaped_ivy_2_x3nln4.jpg' },
            { rootProductId: 61, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763915970/product/heart_shaped_ivy_3_kb7a0b.jpg' },
            { rootProductId: 61, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763915970/product/heart_shaped_ivy_4_tjztuq.jpg' },
            { rootProductId: 61, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763915970/product/heart_shaped_ivy_5_v9fu1n.jpg' },
            { rootProductId: 61, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763915970/product/heart_shaped_ivy_6_sq2f5w.jpg' },
            { rootProductId: 62, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763919397/product/mk_circa_1_jittlj.jpg' },
            { rootProductId: 62, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763919398/product/mk_circa_2_xpidds.jpg' },
            { rootProductId: 62, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763919424/product/mk_circa_3_lqcmfp.jpg' },
            { rootProductId: 62, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763919965/product/mk_circa_4_jrgr2z.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923236/product/gcg_juno_phoi_day_da_nho_1_qjd7wq.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923171/product/gcg_juno_phoi_day_da_nho_2_dtbivj.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923171/product/gcg_juno_phoi_day_da_nho_3_o0faac.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923236/product/gcg_juno_phoi_day_da_nho_4_gsh334.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923171/product/gcg_juno_phoi_day_da_nho_5_ztpeer.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923213/product/gcg_juno_phoi_day_da_nho_6_ja4fxu.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923171/product/gcg_juno_phoi_day_da_nho_7_jrwvjl.jpg' },
            { rootProductId: 63, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763923171/product/gcg_juno_phoi_day_da_nho_8_him995.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763924501/product/gcg_juno_mules_1_zoocgt.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763924502/product/gcg_juno_mules_2_jjbv5h.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763924501/product/gcg_juno_mules_3_zxu0xh.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763924502/product/gcg_juno_mules_4_a6qftm.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764101901/product/gcg_juno_mules_5_zz84cp.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763924503/product/gcg_juno_mules_6_bv8bo7.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763924506/product/gcg_juno_mules_7_yvhp7z.jpg' },
            { rootProductId: 64, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763924505/product/gcg_juno_mules_8_s45aot.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925550/product/gbb_that_eo_1_zcxdmh.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925550/product/gbb_that_eo_2_vuqrhe.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925551/product/gbb_that_eo_3_w5fnga.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925550/product/gbb_that_eo_5_gcidze.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925550/product/gbb_that_eo_4_cetsed.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925551/product/gbb_that_eo_6_zz00k8.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925552/product/gbb_that_eo_7_vkuurx.jpg' },
            { rootProductId: 65, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763925555/product/gbb_that_eo_8_t2cidz.jpg' },
            { rootProductId: 66, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763937303/product/clog_echo_gum_1_nwygkj.png' },
            { rootProductId: 66, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763937303/product/clog_echo_gum_2_nnbfld.png' },
            { rootProductId: 66, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763936676/product/clog_echo_gum_3_l18mrx.png' },
            { rootProductId: 66, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763936676/product/clog_echo_gum_4_bcdhjs.png' },
            { rootProductId: 66, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763936677/product/clog_echo_gum_5_rc7op8.png' },
            { rootProductId: 66, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763936681/product/clog_echo_gum_6_mz4f4h.png' },
            { rootProductId: 66, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763937303/product/clog_echo_gum_7_chcdqj.png' },
            { rootProductId: 67, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763938425/product/clog_pokemon_1_ptp8vi.png' },
            { rootProductId: 67, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763938375/product/clog_pokemon_2_vklhmu.png' },
            { rootProductId: 67, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763938375/product/clog_pokemon_3_zdll8p.png' },
            { rootProductId: 67, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763938378/product/clog_pokemon_4_f0wvgp.png' },
            { rootProductId: 67, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763938379/product/clog_pokemon_5_o0d1mi.png' },
            { rootProductId: 67, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763938381/product/clog_pokemon_6_my24xn.png' },
            { rootProductId: 67, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763938382/product/clog_pokemon_7_bhwpnp.png' },
            { rootProductId: 68, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940170/product/clog_zootopia_1_qbuiig.png' },
            { rootProductId: 68, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940170/product/clog_zootopia_2_f3j1uc.png' },
            { rootProductId: 68, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940169/product/clog_zootopia_3_flpcgf.png' },
            { rootProductId: 68, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940176/product/clog_zootopia_4_tonh6u.png' },
            { rootProductId: 68, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940177/product/clog_zootopia_5_hh0k87.png' },
            { rootProductId: 68, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940179/product/clog_zootopia_6_jjy2hk.png' },
            { rootProductId: 68, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940180/product/clog_zootopia_7_na5e6c.png' },
            { rootProductId: 69, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940111/product/clog_toddler_1_v794xn.png' },
            { rootProductId: 69, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940146/product/clog_toddler_2_srggkf.png' },
            { rootProductId: 69, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940147/product/clog_toddler_3_rjk0xd.png' },
            { rootProductId: 69, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940147/product/clog_toddler_4_oiwwun.png' },
            { rootProductId: 69, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940149/product/clog_toddler_5_bfep8q.png' },
            { rootProductId: 69, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940152/product/clog_toddler_6_nxpyxa.png' },
            { rootProductId: 69, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763940154/product/clog_toddler_7_nxhlov.png' },
            { rootProductId: 70, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987537/product/charm_smurfs_1_orkft0.png' },
            { rootProductId: 70, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987537/product/charm_smurfs_2_rwbawn.png' },
            { rootProductId: 70, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987538/product/charm_smurfs_3_uri5g4.png' },
            { rootProductId: 70, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987538/product/charm_smurfs_4_vxs7mq.png' },
            { rootProductId: 71, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987578/product/charm_tom_jerry_1_igbuvr.png' },
            { rootProductId: 71, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987579/product/charm_tom_jerry_2_gvoygp.png' },
            { rootProductId: 71, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987578/product/charm_tom_jerry_3_zqfaxo.png' },
            { rootProductId: 71, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987579/product/charm_tom_jerry_4_hntzli.png' },
            { rootProductId: 72, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987618/product/charm_simpsons_1_bsxziy.png' },
            { rootProductId: 72, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987618/product/charm_simpsons_2_drdgqp.png' },
            { rootProductId: 72, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987617/product/charm_simpsons_3_ehzxwd.png' },
            { rootProductId: 72, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763987617/product/charm_simpsons_4_akevst.png' },
            { rootProductId: 73, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989147/product/chuck_70_1_s7srzw.png' },
            { rootProductId: 73, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989146/product/chuck_70_2_sl9f1j.jpg' },
            { rootProductId: 73, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989146/product/chuck_70_3_zvud9f.jpg' },
            { rootProductId: 73, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989128/product/chuck_70_4_rj0tk7.jpg' },
            { rootProductId: 73, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989112/product/chuck_70_5_u3u5ii.jpg' },
            { rootProductId: 73, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989112/product/chuck_70_6_xcsunv.jpg' },
            { rootProductId: 74, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989754/product/chuck_70_white_1_sgwhnl.jpg' },
            { rootProductId: 74, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989753/product/chuck_70_white_2_de30g4.jpg' },
            { rootProductId: 74, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989633/product/chuck_70_white_3_l7dkq8.jpg' },
            { rootProductId: 74, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989633/product/chuck_70_white_4_nfavch.jpg' },
            { rootProductId: 74, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763989633/product/chuck_70_white_5_kkjk0h.jpg' },
            { rootProductId: 75, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763990583/product/chuck_classic_1_hug2wx.jpg' },
            { rootProductId: 75, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763990583/product/chuck_classic_2_py1eoa.jpg' },
            { rootProductId: 75, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763990583/product/chuck_classic_3_l4otho.jpg' },
            { rootProductId: 75, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763990582/product/chuck_classic_4_lm6o6f.jpg' },
            { rootProductId: 75, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763990582/product/chuck_classic_5_gd6ntg.jpg' },
            { rootProductId: 75, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763990582/product/chuck_classic_6_imxkki.jpg' }
        ]
    })

    // --- Product Items ---
    await prisma.productItem.createMany({
        data: [
            { rootProductId: 61, stock: 12, barcode: '2049369509920' },
            { rootProductId: 62, stock: 18, barcode: '2065012449108' },
            { rootProductId: 63, size: '35', stock: 12, barcode: '2074193956138' },
            { rootProductId: 63, size: '36', stock: 15, barcode: '2003496084385' },
            { rootProductId: 63, size: '37', stock: 20, barcode: '2052594282322' },
            { rootProductId: 63, size: '38', stock: 18, barcode: '2006557486159' },
            { rootProductId: 63, size: '39', stock: 10, barcode: '2029001789286' },
            { rootProductId: 64, size: '35', stock: 11, barcode: '2069090718903' },
            { rootProductId: 64, size: '36', stock: 12, barcode: '2075812567896' },
            { rootProductId: 64, size: '37', stock: 22, barcode: '2005839865019' },
            { rootProductId: 64, size: '38', stock: 28, barcode: '2041470583615' },
            { rootProductId: 64, size: '39', stock: 18, barcode: '2035616707706' },
            { rootProductId: 65, size: '35', stock: 12, barcode: '2054302445913' },
            { rootProductId: 65, size: '36', stock: 15, barcode: '2080969724580' },
            { rootProductId: 65, size: '37', stock: 20, barcode: '2059640542959' },
            { rootProductId: 65, size: '38', stock: 18, barcode: '2015506561533' },
            { rootProductId: 65, size: '39', stock: 10, barcode: '2023404513936' },
            { rootProductId: 66, size: '35', stock: 5, barcode: '2097847350861' },
            { rootProductId: 66, size: '36', stock: 8, barcode: '2055128433160' },
            { rootProductId: 66, size: '37', stock: 10, barcode: '2002425247433' },
            { rootProductId: 66, size: '38~39', stock: 10, barcode: '2002633305963' },
            { rootProductId: 66, size: '40~41', stock: 10, barcode: '2026269472974' },
            { rootProductId: 66, size: '42', stock: 8, barcode: '2013337414714' },
            { rootProductId: 66, size: '43', stock: 5, barcode: '2053561885270' },
            { rootProductId: 67, size: '35', stock: 7, barcode: '2037909905714' },
            { rootProductId: 67, size: '36', stock: 12, barcode: '2031020584872' },
            { rootProductId: 67, size: '37', stock: 14, barcode: '2073247142725' },
            { rootProductId: 67, size: '38~39', stock: 15, barcode: '2069300769183' },
            { rootProductId: 67, size: '40~41', stock: 15, barcode: '2027235051773' },
            { rootProductId: 67, size: '42', stock: 12, barcode: '2069124065034' },
            { rootProductId: 67, size: '43', stock: 8, barcode: '2008500993899' },
            { rootProductId: 67, size: '44', stock: 7, barcode: '2045443457132' },
            { rootProductId: 67, size: '45', stock: 5, barcode: '2054428669613' },
            { rootProductId: 68, size: '28', stock: 6, barcode: '2029762236067' },
            { rootProductId: 68, size: '29~30', stock: 11, barcode: '2041992225925' },
            { rootProductId: 68, size: '31', stock: 13, barcode: '2008452470288' },
            { rootProductId: 68, size: '32', stock: 17, barcode: '2077114409041' },
            { rootProductId: 68, size: '33', stock: 12, barcode: '2007104007445' },
            { rootProductId: 68, size: '34', stock: 7, barcode: '2085468659241' },
            { rootProductId: 69, size: '21~22', stock: 5, barcode: '2013688515573' },
            { rootProductId: 69, size: '23', stock: 12, barcode: '2025530910290' },
            { rootProductId: 69, size: '24', stock: 17, barcode: '2042966050628' },
            { rootProductId: 69, size: '25', stock: 14, barcode: '2096613691016' },
            { rootProductId: 69, size: '26~27', stock: 10, barcode: '2085940627072' },
            { rootProductId: 70, stock: 15, barcode: '2096449228691' },
            { rootProductId: 71, stock: 15, barcode: '2059046211015' },
            { rootProductId: 72, stock: 15, barcode: '2085850551511' },
            { rootProductId: 73, size: '37', stock: 5, barcode: '2028460119429' },
            { rootProductId: 73, size: '38', stock: 13, barcode: '2089847511946' },
            { rootProductId: 73, size: '39', stock: 12, barcode: '2023208403129' },
            { rootProductId: 73, size: '40', stock: 20, barcode: '2025748380373' },
            { rootProductId: 73, size: '41', stock: 22, barcode: '2059286276065' },
            { rootProductId: 73, size: '42', stock: 18, barcode: '2069039021736' },
            { rootProductId: 73, size: '43', stock: 12, barcode: '2055611401850' },
            { rootProductId: 73, size: '44', stock: 5, barcode: '2041251538261' },
            { rootProductId: 74, size: '37', stock: 5, barcode: '2096511263278' },
            { rootProductId: 74, size: '38', stock: 13, barcode: '2060976490425' },
            { rootProductId: 74, size: '39', stock: 12, barcode: '2078632014656' },
            { rootProductId: 74, size: '40', stock: 20, barcode: '2043576207471' },
            { rootProductId: 74, size: '41', stock: 22, barcode: '2006813481348' },
            { rootProductId: 74, size: '42', stock: 18, barcode: '2079733889877' },
            { rootProductId: 74, size: '43', stock: 12, barcode: '2087776616244' },
            { rootProductId: 74, size: '44', stock: 5, barcode: '2021288495935' },
            { rootProductId: 75, size: '37', stock: 5, barcode: '2026739323263' },
            { rootProductId: 75, size: '38', stock: 13, barcode: '2085170008610' },
            { rootProductId: 75, size: '39', stock: 12, barcode: '2054207371706' },
            { rootProductId: 75, size: '40', stock: 20, barcode: '2061880766828' },
            { rootProductId: 75, size: '41', stock: 22, barcode: '2013964005996' },
            { rootProductId: 75, size: '42', stock: 18, barcode: '2018486292916' },
            { rootProductId: 75, size: '43', stock: 12, barcode: '2060999064801' },
            { rootProductId: 75, size: '44', stock: 5, barcode: '2048715395910' }
        ]
    })

    // --- Shoe Features ---
    await prisma.shoeFeature.createMany({
        data: [
            {
                rootProductId: 63,
                categoryId: 5,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Si mờ tổng hợp',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải tổng hợp mềm',
                closureType: 'Khóa gài (Mary Jane Strap)',
                toeShape: 'Mũi nhọn',
                waterResistant: 'Thấp',
                breathability: 'Trung bình',
                pattern: 'Phối dây đá nhỏ lấp lánh, thiết kế sang trọng và nữ tính',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#cbccca',
                secondaryColor: null,
                heelHeight: 7.0,
                durabilityRating: 4.0,
                releaseYear: 2023
            },
            {
                rootProductId: 64,
                categoryId: 5,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da tổng hợp (Si mờ trơn)',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Vải tổng hợp mềm',
                closureType: 'Slip-on (xỏ không quai hậu)',
                toeShape: 'Mũi nhọn',
                waterResistant: 'Thấp',
                breathability: 'Trung bình thấp',
                pattern: 'Đắp mũi chéo phối 2 chất liệu, thiết kế thanh lịch',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#eed8cc',
                secondaryColor: '#7f5e3f',
                heelHeight: 5.0,
                durabilityRating: 4.0,
                releaseYear: 2023
            },
            {
                rootProductId: 65,
                categoryId: 6,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da tổng hợp (Si mờ vân)',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Vải tổng hợp mềm',
                closureType: 'Slip-on (không dây, không quai)',
                toeShape: 'Mũi nhọn',
                waterResistant: 'Thấp',
                breathability: 'Trung bình',
                pattern: 'Điểm nhấn nằm ở quai ngang mảnh "thắt eo" cách điệu, tạo kiểu dáng thanh lịch',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#e9e2d8',
                secondaryColor: null,
                heelHeight: 1.0,
                durabilityRating: 4.0,
                releaseYear: 2023
            },
            {
                rootProductId: 66,
                categoryId: 10,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Croslite nguyên khối',
                soleMaterial: 'Cao su + Croslite',
                liningMaterial: 'LiteRide foam đệm lót',
                closureType: 'Slip-on (quai sau co dãn)',
                toeShape: 'Mũi tròn (clog truyền thống)',
                waterResistant: 'Tốt',
                breathability: 'Trung bình',
                pattern: 'Tông Pink Caramel - thiết kế bo cong thể thao, streetwear',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#ccb8aa',
                secondaryColor: '#685030',
                heelHeight: 3.5,
                durabilityRating: 8.0,
                releaseYear: 2024
            },
            {
                rootProductId: 67,
                categoryId: 10,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Croslite nguyên khối',
                soleMaterial: 'Cao su + Croslite',
                liningMaterial: 'Vật liệu Croslite tự thân mềm',
                closureType: 'Quai gót xoay (pivot strap)',
                toeShape: 'Mũi tròn (clog truyền thống)',
                waterResistant: 'Tốt',
                breathability: 'Trung bình',
                pattern: 'In toàn thân Pokemon (Pikachu, Bulbasaur, Charmander, Squirtle), cùng charm Jibbitz Pokemon đi kèm',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#323337',
                secondaryColor: '#9a1e17',
                heelHeight: 3.0,
                durabilityRating: 8.0,
                releaseYear: 2023
            },
            {
                rootProductId: 68,
                categoryId: 10,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Croslite nguyên khối',
                soleMaterial: 'Cao su + Croslite',
                liningMaterial: 'Vật liệu Croslite tự thân mềm',
                closureType: 'Quai gót xoay (pivot strap)',
                toeShape: 'Mũi tròn (clog truyền thống)',
                waterResistant: 'Tốt',
                breathability: 'Trung bình',
                pattern: 'Nổi bật với loạt phụ kiện charm Jibbitz Zootopia 2 (Judy Hopps, Nick Wilde)',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#b3c9f3',
                secondaryColor: '#0c2556',
                heelHeight: 3.0,
                durabilityRating: 8.0,
                releaseYear: 2023
            },
            {
                rootProductId: 69,
                categoryId: 10,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Croslite nguyên khối',
                soleMaterial: 'Cao su + Croslite',
                liningMaterial: 'Vật liệu Croslite tự thân mềm',
                closureType: 'Quai gót xoay (pivot strap)',
                toeShape: 'Mũi tròn (clog truyền thống)',
                waterResistant: 'Tốt',
                breathability: 'Trung bình',
                pattern: 'Đế giày với bên trong chứa kim tuyến có thể lắc, điểm xuyến thêm họa tiết cầu vồng và ngôi sao đầy màu sắc',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#f2e7eb',
                secondaryColor: '#d471a1',
                heelHeight: 3.0,
                durabilityRating: 8.0,
                releaseYear: 2023
            },
            {
                rootProductId: 73,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Canvas dày',
                soleMaterial: 'Cao su',
                liningMaterial: 'Lót vải mỏng + Ortholite',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Kém',
                breathability: 'Tốt',
                pattern: 'Thiết kế cổ điển, stitching đôi, form vintage 1970s',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#0e0d12',
                secondaryColor: '#f6f5f2',
                heelHeight: 3.5,
                durabilityRating: 6.0,
                releaseYear: 2013
            },
            {
                rootProductId: 74,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Canvas dày',
                soleMaterial: 'Cao su',
                liningMaterial: 'Lót vải mỏng + Ortholite',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Kém',
                breathability: 'Tốt',
                pattern: 'Thiết kế cổ điển, stitching đôi, form vintage 1970s',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#edebec',
                secondaryColor: '#f6f5f2',
                heelHeight: 3.5,
                durabilityRating: 6.0,
                releaseYear: 2013
            },
            {
                rootProductId: 75,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Canvas dày',
                soleMaterial: 'Cao su',
                liningMaterial: 'Lót vải mỏng + Ortholite',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Kém',
                breathability: 'Tốt',
                pattern: 'Thiết kế cổ điển đơn giản, stitching truyền thống All Star',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#393e5e',
                secondaryColor: '#f6f5f2',
                heelHeight: 2.5,
                durabilityRating: 6.0,
                releaseYear: 2013
            }
        ]
    })

    // --- Shoe Feature - Occasion Tag ---
    await prisma.shoeFeatureOccasionTag.createMany({
        data: [
            { shoeFeatureId: 49, occasionTagId: 3 },
            { shoeFeatureId: 49, occasionTagId: 6 },
            { shoeFeatureId: 49, occasionTagId: 10 },
            { shoeFeatureId: 50, occasionTagId: 3 },
            { shoeFeatureId: 50, occasionTagId: 6 },
            { shoeFeatureId: 50, occasionTagId: 10 },
            { shoeFeatureId: 51, occasionTagId: 1 },
            { shoeFeatureId: 51, occasionTagId: 2 },
            { shoeFeatureId: 51, occasionTagId: 3 },
            { shoeFeatureId: 51, occasionTagId: 6 },
            { shoeFeatureId: 51, occasionTagId: 8 },
            { shoeFeatureId: 51, occasionTagId: 10 },
            { shoeFeatureId: 52, occasionTagId: 1 },
            { shoeFeatureId: 52, occasionTagId: 2 },
            { shoeFeatureId: 52, occasionTagId: 7 },
            { shoeFeatureId: 52, occasionTagId: 8 },
            { shoeFeatureId: 52, occasionTagId: 9 },
            { shoeFeatureId: 53, occasionTagId: 1 },
            { shoeFeatureId: 53, occasionTagId: 2 },
            { shoeFeatureId: 53, occasionTagId: 7 },
            { shoeFeatureId: 53, occasionTagId: 8 },
            { shoeFeatureId: 53, occasionTagId: 9 },
            { shoeFeatureId: 54, occasionTagId: 1 },
            { shoeFeatureId: 54, occasionTagId: 2 },
            { shoeFeatureId: 54, occasionTagId: 7 },
            { shoeFeatureId: 54, occasionTagId: 8 },
            { shoeFeatureId: 54, occasionTagId: 9 },
            { shoeFeatureId: 55, occasionTagId: 1 },
            { shoeFeatureId: 55, occasionTagId: 2 },
            { shoeFeatureId: 55, occasionTagId: 7 },
            { shoeFeatureId: 55, occasionTagId: 8 },
            { shoeFeatureId: 55, occasionTagId: 9 },
            { shoeFeatureId: 56, occasionTagId: 1 },
            { shoeFeatureId: 56, occasionTagId: 2 },
            { shoeFeatureId: 56, occasionTagId: 3 },
            { shoeFeatureId: 56, occasionTagId: 7 },
            { shoeFeatureId: 56, occasionTagId: 8 },
            { shoeFeatureId: 56, occasionTagId: 9 },
            { shoeFeatureId: 57, occasionTagId: 1 },
            { shoeFeatureId: 57, occasionTagId: 2 },
            { shoeFeatureId: 57, occasionTagId: 3 },
            { shoeFeatureId: 57, occasionTagId: 7 },
            { shoeFeatureId: 57, occasionTagId: 8 },
            { shoeFeatureId: 57, occasionTagId: 9 },
            { shoeFeatureId: 58, occasionTagId: 1 },
            { shoeFeatureId: 58, occasionTagId: 2 },
            { shoeFeatureId: 58, occasionTagId: 3 },
            { shoeFeatureId: 58, occasionTagId: 7 },
            { shoeFeatureId: 58, occasionTagId: 8 },
            { shoeFeatureId: 58, occasionTagId: 9 }
        ]
    })

    // --- Shoe Feature - Design Tag ---
    await prisma.shoeFeatureDesignTag.createMany({
        data: [
            { shoeFeatureId: 49, designTagId: 2 },
            { shoeFeatureId: 49, designTagId: 3 },
            { shoeFeatureId: 49, designTagId: 4 },
            { shoeFeatureId: 49, designTagId: 7 },
            { shoeFeatureId: 49, designTagId: 12 },
            { shoeFeatureId: 50, designTagId: 2 },
            { shoeFeatureId: 50, designTagId: 3 },
            { shoeFeatureId: 50, designTagId: 4 },
            { shoeFeatureId: 50, designTagId: 7 },
            { shoeFeatureId: 50, designTagId: 12 },
            { shoeFeatureId: 51, designTagId: 2 },
            { shoeFeatureId: 51, designTagId: 4 },
            { shoeFeatureId: 51, designTagId: 7 },
            { shoeFeatureId: 52, designTagId: 2 },
            { shoeFeatureId: 52, designTagId: 3 },
            { shoeFeatureId: 52, designTagId: 5 },
            { shoeFeatureId: 52, designTagId: 6 },
            { shoeFeatureId: 52, designTagId: 8 },
            { shoeFeatureId: 52, designTagId: 11 },
            { shoeFeatureId: 53, designTagId: 2 },
            { shoeFeatureId: 53, designTagId: 3 },
            { shoeFeatureId: 53, designTagId: 5 },
            { shoeFeatureId: 53, designTagId: 6 },
            { shoeFeatureId: 53, designTagId: 8 },
            { shoeFeatureId: 53, designTagId: 11 },
            { shoeFeatureId: 54, designTagId: 2 },
            { shoeFeatureId: 54, designTagId: 3 },
            { shoeFeatureId: 54, designTagId: 5 },
            { shoeFeatureId: 54, designTagId: 6 },
            { shoeFeatureId: 54, designTagId: 8 },
            { shoeFeatureId: 54, designTagId: 11 },
            { shoeFeatureId: 55, designTagId: 2 },
            { shoeFeatureId: 55, designTagId: 3 },
            { shoeFeatureId: 55, designTagId: 5 },
            { shoeFeatureId: 55, designTagId: 6 },
            { shoeFeatureId: 55, designTagId: 8 },
            { shoeFeatureId: 55, designTagId: 11 },
            { shoeFeatureId: 56, designTagId: 1 },
            { shoeFeatureId: 56, designTagId: 2 },
            { shoeFeatureId: 56, designTagId: 5 },
            { shoeFeatureId: 56, designTagId: 6 },
            { shoeFeatureId: 56, designTagId: 10 },
            { shoeFeatureId: 56, designTagId: 11 },
            { shoeFeatureId: 57, designTagId: 1 },
            { shoeFeatureId: 57, designTagId: 2 },
            { shoeFeatureId: 57, designTagId: 5 },
            { shoeFeatureId: 57, designTagId: 6 },
            { shoeFeatureId: 57, designTagId: 10 },
            { shoeFeatureId: 57, designTagId: 11 },
            { shoeFeatureId: 58, designTagId: 1 },
            { shoeFeatureId: 58, designTagId: 2 },
            { shoeFeatureId: 58, designTagId: 5 },
            { shoeFeatureId: 58, designTagId: 6 },
            { shoeFeatureId: 58, designTagId: 10 },
            { shoeFeatureId: 58, designTagId: 11 }
        ]
    })
}
