import { PrismaClient, ShoeGender } from '@prisma/client'
import { generateProductBarcode } from '../../src/utils/stringHelpers'

export const seedProducts = async (prisma: PrismaClient) => {
    // --- Root Products ---
    await prisma.rootProduct.createMany({
        data: [
            {
                brandId: 1,
                name: 'Nike V2K Run - Vintage Green',
                slug: 'nike-v2k-run-vintage-green',
                description:
                    'Tiến lên? Quay lại? Không quan trọng - đôi giày này đưa phong cách retro bước vào tương lai. V2K tái hiện tất cả những gì bạn yêu thích ở Vomero trong một diện mạo như được lấy thẳng từ catalog giày chạy bộ đầu những năm 2000. Thiết kế được xếp lớp với sự kết hợp của các chi tiết kim loại nổi bật, nhựa mang tính hoài niệm và phần đế giữa mang đậm vẻ cổ điển. Gót giày dày đảm bảo dù bạn đi đâu cũng luôn thoải mái.',
                price: 1760000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 6,
                name: 'Túi Clutch Da KENZO Logo Size Lớn - Black / Yellow',
                slug: 'tui-clutch-da-kenzo-logo-size-lon-black-yellow',
                description:
                    'Túi clutch hiện nay không chỉ gói gọn dành cho phái đẹp mà còn là lựa chọn hoàn hảo cho các quý ông hiện đại. Túi Clutch KENZO Logo size lớn với thiết kế hiện đại, gam màu đen - vàng nổi bật cùng logo thương hiệu cá tính. Kiểu dáng thanh lịch, dễ dàng phối hợp cho nhiều phong cách từ sang trọng đến năng động.',
                price: 3260000,
                isAccessory: true,
                createdBy: 2
            },
            {
                brandId: 2,
                name: 'Ba Lô Adidas City Xplorer - Olive',
                slug: 'ba-lo-adidas-city-xplorer-olive',
                description:
                    'Ba lô Adidas City Xplorer màu Olive mang thiết kế hiện đại, trẻ trung với tông màu xanh rêu thời thượng. Được làm từ chất liệu bền chắc, chống thấm nhẹ, ba lô có nhiều ngăn tiện dụng giúp sắp xếp đồ đạc gọn gàng, từ laptop, sách vở cho đến phụ kiện cá nhân. Quai đeo êm ái, dễ dàng điều chỉnh, mang lại sự thoải mái suốt cả ngày. Lựa chọn lý tưởng cho học tập, làm việc hay những chuyến dã ngoại.',
                price: 1200000,
                isAccessory: true,
                createdBy: 2
            },
            {
                brandId: 1,
                name: 'Air Jordan 1 Mid Kid - Electro Orange',
                slug: 'air-jordan-1-mid-kid-electro-orange',
                description:
                    'Air Jordan 1 Mid Kid - Electro Orange mang đến diện mạo nổi bật với sự kết hợp tươi mới giữa sắc cam điện, trắng tinh tế và điểm nhấn đen cá tính. Thiết kế cổ trung đặc trưng giúp hỗ trợ cổ chân, đi kèm chất liệu da tổng hợp bền đẹp, dễ vệ sinh. Đế cao su chắc chắn cho độ bám tốt, mang lại cảm giác thoải mái khi vận động. Một lựa chọn hoàn hảo cho các bạn nhỏ yêu thích phong cách năng động và thời trang.',
                price: 1450000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 5,
                name: 'Giày Gót Trụ Mary Jane Cut-Out - BMN 0734 - Màu Kem',
                slug: 'giay-got-tru-mary-jane-cut-out-bmn-0734-mau-kem',
                description:
                    'Giày Gót Trụ Mary Jane Cut-Out - BMN 0734 mang đến vẻ đẹp thanh lịch và hiện đại cho phái nữ. Thiết kế Mary Jane cổ điển được biến tấu với chi tiết cut-out tinh tế, vừa tạo điểm nhấn độc đáo vừa tôn lên sự duyên dáng cho đôi chân. Gam màu kem trang nhã, dễ dàng phối hợp cùng nhiều phong cách trang phục từ công sở, dạo phố cho đến dự tiệc. Đây chắc chắn sẽ là lựa chọn hoàn hảo cho những cô nàng yêu thích sự tinh tế, thanh lịch nhưng vẫn muốn khẳng định dấu ấn riêng.',
                price: 935000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 5,
                name: 'Thắt Lưng Dây Bản Nhấn Chỉ Nổi - WAI 0041 - Màu Đen',
                slug: 'that-lung-day-ban-nhan-chi-noi-wai-0041-mau-den',
                description:
                    'Thắt Lưng Dây Bản Nhấn Chỉ Nổi - WAI 0041 sở hữu thiết kế tối giản nhưng tinh tế, với điểm nhấn đường chỉ nổi nổi bật trên nền da đen sang trọng. Kiểu dáng bản vừa hiện đại, dễ dàng kết hợp cùng nhiều trang phục từ quần jeans, quần tây cho đến đầm liền, giúp tôn dáng và tạo điểm nhấn thanh lịch. Sản phẩm không chỉ là phụ kiện thời trang mà còn mang lại sự tiện dụng và phong cách, phù hợp cho cả môi trường công sở lẫn những buổi dạo phố.',
                price: 339000,
                isAccessory: true,
                createdBy: 2
            },
            {
                brandId: 5,
                name: 'Kính Mát Dáng Tròn Margot - SRP 0001 - Màu Be',
                slug: 'kinh-mat-dang-tron-margot-srp-0001-mau-be',
                description:
                    'Kính Mát Dáng Tròn Margot - SRP 0001 mang hơi thở cổ điển pha lẫn hiện đại, với gọng tròn thanh lịch giúp tôn lên đường nét gương mặt. Tông màu be trang nhã, dễ phối hợp cùng nhiều phong cách khác nhau, từ trẻ trung năng động đến sang trọng tinh tế. Chất liệu gọng bền nhẹ, tròng kính chống nắng hiệu quả, bảo vệ đôi mắt tối ưu mà vẫn giữ được vẻ thời thượng. Đây là phụ kiện không thể thiếu để hoàn thiện phong cách cho những tín đồ yêu thời trang.',
                price: 725000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Charm Trang Trí Giày Dép Biti's Màu Vàng AAUH04900VAG",
                slug: "charm-trang-tri-giay-dep-biti's-mau-vang-aauh04900vag",
                description:
                    "Charm Giày Dép Hình Ong Vàng - Biti's là phụ kiện nhỏ xinh giúp đôi giày thêm phần nổi bật và cá tính. Thiết kế hình ong đáng yêu với gam vàng nổi bật mang đến điểm nhấn trẻ trung, năng động và dễ thương. Phù hợp cho nhiều loại giày dép không chỉ riêng Biti's, charm ong vàng không chỉ làm đẹp mà còn thể hiện phong cách riêng, giúp bạn tự tin khẳng định cá tính ở bất cứ đâu.",
                price: 60000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Giày Thể Thao Biti's Hunter X Nữ Màu Hồng HSW011700HOG",
                slug: "giay-the-thao-biti's-hunter-x-nu-mau-hong-hsw011700hog",
                description:
                    "Biti's Hunter HSW011700 màu Hồng mang đến sự kết hợp hoàn hảo giữa thiết kế nữ tính và tính năng vận động tối ưu. Thân giày làm từ vải lưới thoáng khí kết hợp da tổng hợp mềm mại, giúp tạo cảm giác thoáng mát, đồng thời ôm sát bàn chân một cách vừa vặn. Đế Eva nguyên khối siêu nhẹ hỗ trợ giảm áp lực lên bàn chân, cho từng bước di chuyển trở nên nhẹ nhàng và linh hoạt. Gam màu hồng pastel tinh tế, phối cùng tông trắng nhẹ nhàng, mang lại vẻ ngọt ngào nhưng vẫn năng động.",
                price: 955000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 4,
                name: "Giày Thể Thao Biti's Hunter Phiên Bản Đặc Biệt 2/9 Nam Màu Kem Lợt HSM013500KEL",
                slug: "giay-the-thao-biti's-hunter-phien-ban-dac-biet-29-nam-mau-kem-lot-hsm013500kel",
                description:
                    'Giày thể thao Biti\'s Hunter Nam Kem Lợt - Phiên Bản Đặc Biệt 2/9 được thiết kế dành riêng cho phái mạnh yêu thích phong cách khỏe khoắn và ý nghĩa tinh thần dân tộc. Phối màu kem lợt sang trọng kết hợp điểm nhấn đỏ - vàng - xanh quân đội, cùng họa tiết ngôi sao vàng và chữ "HẠNH PHÚC" tạo nên diện mạo đậm chất tự hào Việt Nam. Điểm đặc biệt nằm ở tag kim loại khắc "Celebrating Vietnam" và mốc thời gian lịch sử 02.09.1945 - 02.09.2025, như một lời nhắc nhở và tôn vinh niềm tự hào dân tộc.',
                price: 1095000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 3,
                name: 'Reebok Classic Leather Legacy - White / Black',
                slug: 'reebok-classic-leather-legacy-white-black',
                description:
                    'Reebok Classic Leather Legacy - White / Black mang phong cách cổ điển pha chút hiện đại, hoàn hảo cho những ai yêu thích sự tối giản nhưng vẫn nổi bật. Thiết kế da cao cấp kết hợp tông trắng - đen tinh tế mang đến vẻ ngoài thời thượng và dễ phối đồ. Đế Eva êm ái giúp di chuyển nhẹ nhàng, thoải mái suốt cả ngày. Một lựa chọn lý tưởng cho phong cách năng động và cá tính.',
                price: 1500000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 1,
                name: 'Nike Pegasus 41 - Ole Miss',
                slug: 'nike-pegasus-41-ole-miss',
                description:
                    'Nike Pegasus 41 - Ole Miss là phiên bản đặc biệt mang đậm tinh thần thể thao và niềm tự hào đại học Ole Miss. Đôi giày kết hợp giữa hiệu năng vượt trội và phong cách cổ điển, trang bị đệm ZoomX + React cho cảm giác êm ái, phản hồi nhanh nhạy. Thiết kế phối màu xanh - đỏ - trắng đặc trưng giúp nổi bật trên mọi cung đường, lý tưởng cho cả chạy bộ lẫn sử dụng hằng ngày.',
                price: 1915000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 1,
                name: 'Nike Sabrina 3 - Mint Foam',
                slug: 'nike-sabrina-3-mint-foam',
                description:
                    'Nike Sabrina 3 - Mint Foam là đôi giày bóng rổ thế hệ mới được thiết kế cho tốc độ, sự linh hoạt và kiểm soát tối đa. Phần upper nhẹ, ôm chân hoàn hảo, kết hợp hệ thống Zoom Air mang lại độ bật và phản hồi cực nhanh. Màu Mint Foam tươi mát tạo điểm nhấn hiện đại, vừa tinh tế vừa năng động. Lý tưởng cho các vận động viên muốn thống trị sân đấu với phong cách và hiệu suất đỉnh cao.',
                price: 2300000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 2,
                name: 'Adidas Italia 70s - Brown',
                slug: 'adidas-italia-70s-brown',
                description:
                    'Adidas Italia 70s Brown mang đậm dấu ấn retro từ thập niên 1970, kết hợp giữa phong cách cổ điển và sự tinh tế hiện đại. Thân giày làm từ da lộn cao cấp cùng tông nâu ấm áp, tạo cảm giác sang trọng và dễ phối đồ. Đế cao su bám tốt, mang lại sự thoải mái cho cả ngày dài. Một lựa chọn hoàn hảo cho những ai yêu thích vẻ đẹp hoài niệm và chất thời trang tinh giản.',
                price: 1500000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 2,
                name: 'Adidas Adistar 4 - Navy',
                slug: 'adidas-adistar-4-navy',
                description:
                    'Adidas Adistar 4 - Navy là đôi giày chạy bộ cao cấp hướng đến sự bền bỉ và thoải mái trên mọi quãng đường. Thiết kế tối giản với tông xanh navy sang trọng, kết hợp chất liệu lưới thoáng khí và lớp đệm Eva êm ái giúp giảm chấn hiệu quả. Đế ngoài bám chắc mang lại độ ổn định tuyệt vời. Hoàn hảo cho người yêu chạy bộ muốn cân bằng giữa hiệu suất, phong cách và độ bền vượt trội.',
                price: 2100000,
                isAccessory: false,
                createdBy: 1
            }
        ]
    })

    // --- Product Images ---
    await prisma.productImage.createMany({
        data: [
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964861/product/nike_v2k_run_1_v5fill.jpg' },
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964859/product/nike_v2k_run_2_oatjvh.jpg' },
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964857/product/nike_v2k_run_3_zwepzz.jpg' },
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964855/product/nike_v2k_run_4_ur99h3.jpg' },
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964854/product/nike_v2k_run_5_dcmdrl.jpg' },
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964851/product/nike_v2k_run_6_xasu62.jpg' },
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964859/product/nike_v2k_run_7_iloajh.jpg' },
            { rootProductId: 1, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758964850/product/nike_v2k_run_8_vcuxe2.jpg' },
            { rootProductId: 2, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758988465/product/kenzo_clutch_3_pu0ghn.jpg' },
            { rootProductId: 2, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758988467/product/kenzo_clutch_2_rrrnq8.jpg' },
            { rootProductId: 2, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758988468/product/kenzo_clutch_1_cbkm1t.jpg' },
            { rootProductId: 2, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758988469/product/kenzo_clutch_4_neqseg.jpg' },
            { rootProductId: 3, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989279/product/adidas_city_xplorer_1_ywrack.jpg' },
            { rootProductId: 3, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989278/product/adidas_city_xplorer_2_pbmx0r.jpg' },
            { rootProductId: 3, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989276/product/adidas_city_xplorer_3_h6pfyt.jpg' },
            { rootProductId: 3, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989274/product/adidas_city_xplorer_4_u8sa0i.jpg' },
            { rootProductId: 3, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989278/product/adidas_city_xplorer_5_wwiczh.jpg' },
            { rootProductId: 3, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989273/product/adidas_city_xplorer_6_gf98tg.jpg' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989789/product/aj1_mid_kid_1_qnyuve.png' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989787/product/aj1_mid_kid_2_a3imwk.png' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989785/product/aj1_mid_kid_3_mxreem.png' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989784/product/aj1_mid_kid_4_izgtio.png' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989781/product/aj1_mid_kid_5_wli2h1.png' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989731/product/aj1_mid_kid_6_avn4my.png' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989730/product/aj1_mid_kid_7_ugy182.png' },
            { rootProductId: 4, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758989738/product/aj1_mid_kid_8_kbm5s7.png' },
            { rootProductId: 5, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758994247/product/mary_jane_1_sodssh.jpg' },
            { rootProductId: 5, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758994207/product/mary_jane_2_w766eo.jpg' },
            { rootProductId: 5, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758994202/product/mary_jane_3_ax0agp.jpg' },
            { rootProductId: 5, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758994204/product/mary_jane_4_ps8mar.jpg' },
            { rootProductId: 5, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758994203/product/mary_jane_5_kscwxa.jpg' },
            { rootProductId: 6, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995708/product/that_lung_wai_1_foc64y.jpg' },
            { rootProductId: 6, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995704/product/that_lung_wai_2_r9358b.jpg' },
            { rootProductId: 6, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995705/product/that_lung_wai_3_zg6wxf.jpg' },
            { rootProductId: 6, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995704/product/that_lung_wai_4_uxwh2q.jpg' },
            { rootProductId: 7, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995710/product/margot_be_1_ep6fpt.jpg' },
            { rootProductId: 7, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995712/product/margot_be_2_v1d98m.jpg' },
            { rootProductId: 7, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995714/product/margot_be_3_fx7kyn.jpg' },
            { rootProductId: 7, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758995716/product/margot_be_4_n5k5nk.jpg' },
            { rootProductId: 8, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758996264/product/charm_bee_1_dd6kbr.jpg' },
            { rootProductId: 8, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758996264/product/charm_bee_2_z6xetr.jpg' },
            { rootProductId: 8, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758996264/product/charm_bee_3_e6pfs3.jpg' },
            { rootProductId: 9, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997072/product/HSW011700HOG_1_hgbsta.jpg' },
            { rootProductId: 9, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997072/product/HSW011700HOG_2_yb9mvb.jpg' },
            { rootProductId: 9, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997071/product/HSW011700HOG_3_fbdwgh.jpg' },
            { rootProductId: 9, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997071/product/HSW011700HOG_4_ykbkwo.jpg' },
            { rootProductId: 9, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997071/product/HSW011700HOG_5_awo38y.jpg' },
            { rootProductId: 9, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997071/product/HSW011700HOG_6_o8v35v.jpg' },
            { rootProductId: 9, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997071/product/HSW011700HOG_7_bhdoko.jpg' },
            { rootProductId: 10, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997001/product/HSM013500KEL_1_qnjetz.jpg' },
            { rootProductId: 10, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997000/product/HSM013500KEL_2_giw7s0.jpg' },
            { rootProductId: 10, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997000/product/HSM013500KEL_3_z4sy3p.jpg' },
            { rootProductId: 10, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997000/product/HSM013500KEL_4_beoij6.jpg' },
            { rootProductId: 10, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997001/product/HSM013500KEL_5_bgf3rh.jpg' },
            { rootProductId: 10, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997000/product/HSM013500KEL_6_iqp5nq.jpg' },
            { rootProductId: 10, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1758997000/product/HSM013500KEL_7_pe2b0n.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768208/product/rebook_club_1_f6zxob.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768207/product/rebook_club_2_eqckmf.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768207/product/rebook_club_3_yvnflt.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768207/product/rebook_club_4_hxnzoz.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768209/product/rebook_club_5_nqxbml.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768202/product/rebook_club_6_uoqxhb.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768207/product/rebook_club_7_xxgt5n.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768203/product/rebook_club_8_lcqjhb.jpg' },
            { rootProductId: 11, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1759768202/product/rebook_club_9_slxz8f.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037403/product/nike_pegasus_1_zw3yb7.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037403/product/nike_pegasus_2_c2rkua.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037403/product/nike_pegasus_3_yawx1w.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037403/product/nike_pegasus_4_hf81y2.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037404/product/nike_pegasus_5_g6nr4r.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037403/product/nike_pegasus_6_apjgit.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037403/product/nike_pegasus_7_ftttxu.jpg' },
            { rootProductId: 12, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760037404/product/nike_pegasus_8_e92ha6.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147873/product/nike_sabrina_1_nv1owq.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147868/product/nike_sabrina_2_zifmfr.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147867/product/nike_sabrina_3_unzdf9.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147868/product/nike_sabrina_4_tj71ci.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147868/product/nike_sabrina_5_asvabl.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147868/product/nike_sabrina_6_ull5io.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147870/product/nike_sabrina_7_e59g89.jpg' },
            { rootProductId: 13, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760147870/product/nike_sabrina_8_tp3peh.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149005/product/adidas_italia_70s_1_aa1hyy.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149006/product/adidas_italia_70s_2_yrk1yh.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149007/product/adidas_italia_70s_3_d3xwjx.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149006/product/adidas_italia_70s_4_gmkhmc.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149006/product/adidas_italia_70s_5_tmmsux.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149006/product/adidas_italia_70s_6_frdst0.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149006/product/adidas_italia_70s_7_slrfw2.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149007/product/adidas_italia_70s_8_pewkkv.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149009/product/adidas_italia_70s_9_otcdig.jpg' },
            { rootProductId: 14, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149011/product/adidas_italia_70s_10_xw27ds.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149909/product/adidas_adistar_1_tadywm.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149909/product/adidas_adistar_2_hhhyxl.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149909/product/adidas_adistar_3_kjm9ck.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149909/product/adidas_adistar_4_nou14n.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149910/product/adidas_adistar_5_ccpnuu.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149909/product/adidas_adistar_6_gyys23.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149910/product/adidas_adistar_7_j8hxge.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149910/product/adidas_adistar_8_l5nifa.jpg' },
            { rootProductId: 15, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1760149910/product/adidas_adistar_9_xy1xds.jpg' }
        ]
    })

    // --- Product Items ---
    await prisma.productItem.createMany({
        data: [
            { rootProductId: 1, size: '38.5', stock: 5, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '39', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '40', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '40.5', stock: 3, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '41', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '42', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '42.5', stock: 5, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '43', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 1, size: '44', stock: 9, barcode: generateProductBarcode() },
            { rootProductId: 2, stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 3, stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 4, size: '29.5', stock: 5, barcode: generateProductBarcode() },
            { rootProductId: 4, size: '31', stock: 7, barcode: generateProductBarcode() },
            { rootProductId: 4, size: '32', stock: 7, barcode: generateProductBarcode() },
            { rootProductId: 4, size: '33', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 4, size: '33.5', stock: 5, barcode: generateProductBarcode() },
            { rootProductId: 4, size: '34', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 4, size: '35', stock: 8, barcode: generateProductBarcode() },
            { rootProductId: 5, size: '35', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 5, size: '36', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 5, size: '37', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 5, size: '38', stock: 18, barcode: generateProductBarcode() },
            { rootProductId: 5, size: '39', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 6, stock: 40, barcode: generateProductBarcode() },
            { rootProductId: 7, stock: 17, barcode: generateProductBarcode() },
            { rootProductId: 8, stock: 50, barcode: generateProductBarcode() },
            { rootProductId: 9, size: '35', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 9, size: '36', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 9, size: '37', stock: 28, barcode: generateProductBarcode() },
            { rootProductId: 9, size: '38', stock: 28, barcode: generateProductBarcode() },
            { rootProductId: 9, size: '39', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 10, size: '40', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 10, size: '41', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 10, size: '42', stock: 18, barcode: generateProductBarcode() },
            { rootProductId: 10, size: '43', stock: 18, barcode: generateProductBarcode() },
            { rootProductId: 10, size: '44', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 11, size: '42', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 11, size: '42.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 11, size: '43', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 11, size: '44', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 11, size: '44.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 12, size: '42', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 12, size: '43', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 12, size: '44', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 12, size: '44.5', stock: 16, barcode: generateProductBarcode() },
            { rootProductId: 13, size: '40', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 13, size: '40.5', stock: 13, barcode: generateProductBarcode() },
            { rootProductId: 13, size: '41', stock: 28, barcode: generateProductBarcode() },
            { rootProductId: 13, size: '42', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 13, size: '42.5', stock: 10, barcode: generateProductBarcode() },
            { rootProductId: 14, size: '38.5', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 14, size: '39', stock: 24, barcode: generateProductBarcode() },
            { rootProductId: 14, size: '40', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 14, size: '40.5', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 15, size: '41', stock: 24, barcode: generateProductBarcode() },
            { rootProductId: 15, size: '42', stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 15, size: '42.5', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 15, size: '43', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 15, size: '44', stock: 30, barcode: generateProductBarcode() }
        ]
    })

    // --- Shoe Features ---
    await prisma.shoeFeature.createMany({
        data: [
            {
                rootProductId: 1,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Lưới + Da tổng hợp',
                soleMaterial: 'Đệm foam + Đế cao su',
                liningMaterial: 'Vải dệt',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Phối kim loại bóng và chi tiết xếp lớp',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#253230',
                secondaryColor: '#bbc1c7',
                heelHeight: 4.0,
                durabilityRating: 8.5,
                releaseYear: 2024
            },
            {
                rootProductId: 4,
                categoryId: 9,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp + Da thật',
                soleMaterial: 'Đệm air + Đế cao su',
                liningMaterial: 'Vải dệt',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Không',
                breathability: 'Trung bình',
                pattern: 'Phối màu cam, đen và trắng nổi bật',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#eb704c',
                secondaryColor: '#e3e3e3',
                heelHeight: 3.0,
                durabilityRating: 9.0,
                releaseYear: 2021
            },
            {
                rootProductId: 5,
                categoryId: 5,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da tổng hợp',
                soleMaterial: 'Cao su',
                liningMaterial: 'Da tổng hợp',
                closureType: 'Khóa gài (Mary Jane Strap)',
                toeShape: 'Mũi tròn',
                waterResistant: 'Không',
                breathability: 'Trung bình',
                pattern: 'Trơn, cut-out tinh tế',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#dec9b1',
                heelHeight: 7.0,
                durabilityRating: 8.0,
                releaseYear: 2023
            },
            {
                rootProductId: 9,
                categoryId: 1,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Vải lưới + Da tổng hợp',
                soleMaterial: 'Eva nguyên khối',
                liningMaterial: 'Vải + Lớp lót êm',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Không',
                breathability: 'Cao',
                pattern: 'Phối hồng pastel - trắng',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#cfbab4',
                secondaryColor: '#c7c0b7',
                heelHeight: 3.5,
                durabilityRating: 8.0,
                releaseYear: 2025
            },
            {
                rootProductId: 10,
                categoryId: 1,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải + Lót êm',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Không',
                breathability: 'Trung bình',
                pattern: 'Phối kem lợt - đỏ - vàng - xanh quân đội',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#cfcfcf',
                secondaryColor: '#5a5d4c',
                heelHeight: 4.0,
                durabilityRating: 8.5,
                releaseYear: 2025
            },
            {
                rootProductId: 11,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da tổng hợp',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải dệt',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Tốt',
                pattern: 'Trơn, điểm nhấn logo Reebok',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#d6d7d9',
                secondaryColor: '#43504b',
                heelHeight: 2.5,
                durabilityRating: 4.5,
                releaseYear: 2023
            },
            {
                rootProductId: 12,
                categoryId: 1,
                gender: ShoeGender.MALE,
                upperMaterial: 'Lưới kỹ thuật (Engineered Mesh)',
                soleMaterial: 'Cao su + Bọt ReactX',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Rất tốt',
                pattern: 'Phối màu Ole Miss (Xanh navy - Đỏ - Trắng) cùng logo Nike Swoosh',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#1a2b57',
                secondaryColor: '#c8102e',
                heelHeight: 3.2,
                durabilityRating: 4.5,
                releaseYear: 2024
            },
            {
                rootProductId: 13,
                categoryId: 1,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Lưới dệt tổng hợp (Engineered Mesh) + Fuse hỗ trợ',
                soleMaterial: 'Cao su + Zoom Air + Bọt React',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Rất tốt',
                pattern: 'Trơn với điểm nhấn logo Swoosh và chi tiết chữ ký Sabrina Ionescu',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#b4e1d0',
                secondaryColor: '#ffffff',
                heelHeight: 3.0,
                durabilityRating: 4.7,
                releaseYear: 2024
            },
            {
                rootProductId: 14,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Da lộn (Suede) cao cấp',
                soleMaterial: 'Cao su nguyên khối',
                liningMaterial: 'Vải dệt mềm',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Trung bình',
                pattern: 'Phong cách retro với 3 gạch Adidas cổ điển',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#6b4f36',
                secondaryColor: '#000000',
                heelHeight: 2.8,
                durabilityRating: 4.6,
                releaseYear: 2024
            },
            {
                rootProductId: 15,
                categoryId: 1,
                gender: ShoeGender.MALE,
                upperMaterial: 'Lưới kỹ thuật (Engineered Mesh) tái chế',
                soleMaterial: 'Cao su Continental + Bọt Repetitor 2.0',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Tròn',
                waterResistant: 'Không',
                breathability: 'Rất tốt',
                pattern: 'Thiết kế hiện đại, phối 3 gạch Adidas phản quang',
                countryOfOrigin: 'Trung Quốc',
                primaryColor: '#1a2b57',
                secondaryColor: '#d3d3d3',
                heelHeight: 3.5,
                durabilityRating: 4.8,
                releaseYear: 2024
            }
        ]
    })

    // --- Shoe Feature - Occasion Tag ---
    await prisma.shoeFeatureOccasionTag.createMany({
        data: [
            { shoeFeatureId: 1, occasionTagId: 1 },
            { shoeFeatureId: 1, occasionTagId: 2 },
            { shoeFeatureId: 1, occasionTagId: 4 },
            { shoeFeatureId: 1, occasionTagId: 5 },
            { shoeFeatureId: 1, occasionTagId: 7 },
            { shoeFeatureId: 1, occasionTagId: 8 },
            { shoeFeatureId: 1, occasionTagId: 9 },
            { shoeFeatureId: 2, occasionTagId: 1 },
            { shoeFeatureId: 2, occasionTagId: 2 },
            { shoeFeatureId: 2, occasionTagId: 3 },
            { shoeFeatureId: 2, occasionTagId: 4 },
            { shoeFeatureId: 2, occasionTagId: 7 },
            { shoeFeatureId: 2, occasionTagId: 8 },
            { shoeFeatureId: 2, occasionTagId: 9 },
            { shoeFeatureId: 3, occasionTagId: 1 },
            { shoeFeatureId: 3, occasionTagId: 2 },
            { shoeFeatureId: 3, occasionTagId: 3 },
            { shoeFeatureId: 3, occasionTagId: 6 },
            { shoeFeatureId: 3, occasionTagId: 8 },
            { shoeFeatureId: 3, occasionTagId: 10 },
            { shoeFeatureId: 4, occasionTagId: 1 },
            { shoeFeatureId: 4, occasionTagId: 2 },
            { shoeFeatureId: 4, occasionTagId: 4 },
            { shoeFeatureId: 4, occasionTagId: 5 },
            { shoeFeatureId: 4, occasionTagId: 7 },
            { shoeFeatureId: 4, occasionTagId: 8 },
            { shoeFeatureId: 4, occasionTagId: 9 },
            { shoeFeatureId: 5, occasionTagId: 1 },
            { shoeFeatureId: 5, occasionTagId: 2 },
            { shoeFeatureId: 5, occasionTagId: 3 },
            { shoeFeatureId: 5, occasionTagId: 4 },
            { shoeFeatureId: 5, occasionTagId: 7 },
            { shoeFeatureId: 5, occasionTagId: 8 },
            { shoeFeatureId: 5, occasionTagId: 9 },
            { shoeFeatureId: 6, occasionTagId: 1 },
            { shoeFeatureId: 6, occasionTagId: 2 },
            { shoeFeatureId: 6, occasionTagId: 4 },
            { shoeFeatureId: 6, occasionTagId: 5 },
            { shoeFeatureId: 6, occasionTagId: 7 },
            { shoeFeatureId: 6, occasionTagId: 8 },
            { shoeFeatureId: 6, occasionTagId: 9 },
            { shoeFeatureId: 7, occasionTagId: 1 },
            { shoeFeatureId: 7, occasionTagId: 2 },
            { shoeFeatureId: 7, occasionTagId: 4 },
            { shoeFeatureId: 7, occasionTagId: 5 },
            { shoeFeatureId: 7, occasionTagId: 7 },
            { shoeFeatureId: 8, occasionTagId: 1 },
            { shoeFeatureId: 8, occasionTagId: 2 },
            { shoeFeatureId: 8, occasionTagId: 4 },
            { shoeFeatureId: 8, occasionTagId: 5 },
            { shoeFeatureId: 8, occasionTagId: 7 },
            { shoeFeatureId: 8, occasionTagId: 8 },
            { shoeFeatureId: 8, occasionTagId: 9 },
            { shoeFeatureId: 9, occasionTagId: 1 },
            { shoeFeatureId: 9, occasionTagId: 2 },
            { shoeFeatureId: 9, occasionTagId: 3 },
            { shoeFeatureId: 9, occasionTagId: 7 },
            { shoeFeatureId: 9, occasionTagId: 10 },
            { shoeFeatureId: 10, occasionTagId: 1 },
            { shoeFeatureId: 10, occasionTagId: 2 },
            { shoeFeatureId: 10, occasionTagId: 4 },
            { shoeFeatureId: 10, occasionTagId: 8 },
            { shoeFeatureId: 10, occasionTagId: 9 }
        ]
    })

    // --- Shoe Feature - Design Tag ---
    await prisma.shoeFeatureDesignTag.createMany({
        data: [
            { shoeFeatureId: 1, designTagId: 3 },
            { shoeFeatureId: 1, designTagId: 5 },
            { shoeFeatureId: 1, designTagId: 6 },
            { shoeFeatureId: 1, designTagId: 9 },
            { shoeFeatureId: 1, designTagId: 10 },
            { shoeFeatureId: 1, designTagId: 11 },
            { shoeFeatureId: 2, designTagId: 3 },
            { shoeFeatureId: 2, designTagId: 5 },
            { shoeFeatureId: 2, designTagId: 6 },
            { shoeFeatureId: 2, designTagId: 9 },
            { shoeFeatureId: 2, designTagId: 11 },
            { shoeFeatureId: 3, designTagId: 2 },
            { shoeFeatureId: 3, designTagId: 4 },
            { shoeFeatureId: 3, designTagId: 7 },
            { shoeFeatureId: 3, designTagId: 11 },
            { shoeFeatureId: 4, designTagId: 3 },
            { shoeFeatureId: 4, designTagId: 5 },
            { shoeFeatureId: 4, designTagId: 6 },
            { shoeFeatureId: 4, designTagId: 9 },
            { shoeFeatureId: 4, designTagId: 10 },
            { shoeFeatureId: 4, designTagId: 11 },
            { shoeFeatureId: 5, designTagId: 3 },
            { shoeFeatureId: 5, designTagId: 5 },
            { shoeFeatureId: 5, designTagId: 6 },
            { shoeFeatureId: 5, designTagId: 9 },
            { shoeFeatureId: 5, designTagId: 11 },
            { shoeFeatureId: 6, designTagId: 2 },
            { shoeFeatureId: 6, designTagId: 3 },
            { shoeFeatureId: 6, designTagId: 5 },
            { shoeFeatureId: 6, designTagId: 6 },
            { shoeFeatureId: 6, designTagId: 9 },
            { shoeFeatureId: 7, designTagId: 1 },
            { shoeFeatureId: 7, designTagId: 5 },
            { shoeFeatureId: 7, designTagId: 6 },
            { shoeFeatureId: 7, designTagId: 9 },
            { shoeFeatureId: 7, designTagId: 10 },
            { shoeFeatureId: 8, designTagId: 3 },
            { shoeFeatureId: 8, designTagId: 5 },
            { shoeFeatureId: 8, designTagId: 6 },
            { shoeFeatureId: 8, designTagId: 9 },
            { shoeFeatureId: 8, designTagId: 11 },
            { shoeFeatureId: 9, designTagId: 1 },
            { shoeFeatureId: 9, designTagId: 2 },
            { shoeFeatureId: 9, designTagId: 4 },
            { shoeFeatureId: 9, designTagId: 7 },
            { shoeFeatureId: 10, designTagId: 3 },
            { shoeFeatureId: 10, designTagId: 5 },
            { shoeFeatureId: 10, designTagId: 6 },
            { shoeFeatureId: 10, designTagId: 8 },
            { shoeFeatureId: 10, designTagId: 9 },
            { shoeFeatureId: 10, designTagId: 10 },
            { shoeFeatureId: 10, designTagId: 11 },
            { shoeFeatureId: 10, designTagId: 12 }
        ]
    })
}
