import { PrismaClient, ShoeGender } from '@prisma/client'
import { generateProductBarcode } from '../../src/utils/stringHelpers'

export const seedProducts = async (prisma: PrismaClient) => {
    // --- Root Products ---
    await prisma.rootProduct.createMany({
        data: [
            {
                brandId: 6,
                name: 'KENZO Hawaiian Graffiti Bucket Hat - Vanilla',
                slug: 'kenzo-hawaiian-graffiti-bucket-hat-vanilla',
                description:
                    'KENZO Hawaiian Graffiti Bucket Hat - Vanilla - Mũ bucket unisex của KENZO được làm từ nylon nhẹ, in họa tiết "Hawaiian Graffiti" rực rỡ gợi nhớ phong cách nhiệt đới của thập niên 90. Logo Kenzo nổi bật phía trước tạo điểm nhấn thời trang, phù hợp cho những ngày nắng hoặc mang làm phụ kiện statement cho phong cách du lịch, dạo phố.',
                price: 1500000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 2,
                name: 'Adidas Resort Cord Strapback Hat - Shadow Brown',
                slug: 'adidas-resort-cord-strapback-hat-shadow-brown',
                description:
                    'Adidas Resort Cord Strapback Hat - Shadow Brown - Mũ strapback unisex mang phong cách retro với chất liệu corduroy nâu trầm nhẹ nhàng nhưng rất thời trang. Thiết kế 5 panel thoải mái, lưỡi mũ cong, cùng khóa điều chỉnh phía sau giúp phù hợp nhiều kích cỡ đầu. Logo Adidas nhỏ gọn tạo điểm nhấn tinh tế - lý tưởng để phối cùng trang phục casual hoặc phong cách dạo phố.',
                price: 450000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 5,
                name: 'Combat Boots Cao Cổ Đế Chunky - BOT 0932 - Màu Đen',
                slug: 'combat-boots-cao-co-de-chunky-bot-0932-mau-den',
                description:
                    'Giày boots Vascara Combat cao cổ đế chunky - BOT 0932 - Một đôi combat boots cá tính và mạnh mẽ: phần cổ cao bảo vệ mắt cá chân, chất liệu da nhân tạo bóng sang trọng, đế chunky cao vừa phải mang đến cảm giác vừa chắc chắn nhưng cũng không kém phần hiện đại. Thiết kế mũi tròn, dây buộc cổ điển phù hợp cho cả dạo phố, đi làm hay phong cách streetwear.',
                price: 1245000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 5,
                name: 'Giày Boots Đệm Vải Dáng Chelsea - BOT 0949 - Màu Nâu Đậm',
                slug: 'giay-boots-dem-vai-dang-chelsea-bot-0949-mau-nau-dam',
                description:
                    'Giày boots Vascara Chelsea BOT 0949 có thiết kế cổ cao nhẹ theo phong cách Chelsea truyền thống, mang lại vẻ tinh tế và dễ phối đồ. Thân giày bằng vải kết hợp da tổng hợp giúp tạo sự mềm mại và thoáng hơn, trong khi phần đệm lót êm hỗ trợ sự thoải mái khi mang cả ngày. Đế cao su chắc chắn, bền bỉ, tích hợp đường viền tinh tế, phù hợp cho phong cách công sở hoặc dạo phố lịch sự nhưng vẫn rất năng động.',
                price: 1795000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 5,
                name: 'Guốc Mules Phối Nơ Trang Trí - GNN 0229 - Màu Kem',
                slug: 'guoc-mules-phoi-no-trang-tri-gnn-0229-mau-kem',
                description:
                    'Guốc Mules Vascara GNN 0229 - màu kem mang thiết kế nữ tính với quai nơ trang trí tinh tế, mang lại vẻ thanh lịch nhưng vẫn trẻ trung. Chất liệu da tổng hợp mịn màng, đế cao vừa phải giúp tôn dáng mà vẫn thoải mái khi di chuyển. Lý tưởng để diện đi làm, dạo phố hoặc dự tiệc nhẹ nhàng.',
                price: 875000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 5,
                name: 'Guốc Mary Janes Mũi Vuông - GNN 0200 - Màu Be',
                slug: 'guoc-mary-janes-mui-vuong-gnn-0200-mau-be',
                description:
                    'Guốc Mary Janes Vascara GNN 0200 mang trong mình thiết kế cổ điển Mary Janes và mũi vuông thời thượng, đôi guốc này mang đến phong cách nữ tính nhưng vẫn rất thanh lịch. Chất liệu da tổng hợp cao cấp, quai thắt chắc chắn tạo cảm giác vừa vặn. Đế cao và đệm êm giúp tôn dáng mà vẫn thoải mái khi mang cả ngày. Phù hợp cho nhiều phong cách - từ công sở đến dạo phố nhẹ nhàng.',
                price: 765000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 10,
                name: 'Ananas "Copy" Store Bag 001 - Black',
                slug: 'ananas-copy-store-bag-001-black',
                description:
                    'Hướng đến sức chịu đựng và độ lì lợm cao làm cốt lõi. Ananas "Copy" Store Bag 001 được thiết kế cực kì căn bản, tiết chế hoàn toàn các chi tiết cộng thêm khác để sự đặc biệt tập trung hoàn toàn vào chất liệu chính. Túi sử dụng Canvas cao cấp với định lượng lên đến 365 gsm, có tính năng trượt nước, chấp hết các thể loại xuyên thủng từ kim loại đến chất lỏng nếu đặt dưới một cường độ tác động không quá lớn.',
                price: 200000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 10,
                name: 'Die-cut Insoles - Ananas Ortholite 7mm RF - White Asparagus',
                slug: 'die-cut-insoles-ananas-ortholite-7mm-rf-white-asparagus',
                description:
                    'Ananas Ortholite 7mm RF là lựa chọn bổ sung hoàn hảo khi trải nghiệm cùng những đôi giày Vulcanized nhà Ananas, giúp giày lên chân với cảm giác nhẹ hơn, thoáng khí hơn; rất phù nếu bạn đang có một tính chất công việc phải di chuyển nhiều. Màu sắc tươi tắn, ngẫu nhiên từ vật liệu Foam với 100% thành phần tái chế từ cao su và Foam thừa trong quá trình sản xuất, đóng góp nho nhỏ trong việc giảm rác thải ra môi trường. Sản phẩm vẫn phù hợp với những đôi giày của các thương hiệu khác, nhưng bạn cần chú ý về độ dày phù hợp và sử dụng chúng đúng cách.',
                price: 69000,
                isAccessory: true,
                createdBy: 1
            },
            {
                brandId: 10,
                name: 'Track 6 Fold-over Tongue - The Team - Low Top - Caviar Black',
                slug: 'track-6-fold-over-tongue-the-team-low-top-caviar-black',
                description:
                    'Ananas Track 6 Fold-over Tongue "The Team" Low Top - Caviar Black - Đôi sneaker nam mang đậm phong cách retro, với phần upper làm từ C-Leather bền bỉ và sang trọng. Thiết kế "fold-over tongue" độc đáo tạo điểm nhấn cá tính, kết hợp đế cao su chắc chắn mang lại độ bền và độ bám tốt. Phù hợp để phối cùng trang phục streetwear, vintage hoặc phong cách năng động hàng ngày.',
                price: 1090000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 10,
                name: 'Vintas Denim - Low Top - Night Sky',
                slug: 'vintas-denim-low-top-night-sky',
                description:
                    'Vintas Denim - Low Top "Night Sky" - Đôi sneaker nam mang phong cách trẻ trung với phần upper làm từ denim bền bỉ, phối tông màu “Night Sky” tối giản nhưng cá tính. Đế cao su chắc chắn mang lại độ bám tốt và sản phẩm còn có nhiều kích cỡ đa dạng. Một lựa chọn linh hoạt, dễ phối với trang phục jean hoặc streetwear hàng ngày.',
                price: 650000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 10,
                name: "Vintas Nauda EXT - High Top - Monk's Robe",
                slug: 'vintas-nauda-ext-high-top-monks-robe',
                description:
                    'Vintas Nauda EXT - High Top "Monk\'s Robe" - Đôi sneaker nam mang phong cách vintage nhẹ nhàng. Thân giày kết hợp canvas và suede cao cấp, màu nâu nhẹ trầm ấm, tạo cảm giác cổ điển nhưng vẫn thời trang. Đế cao su vulcanized bền bỉ cùng nhiều kích cỡ đa dạng, phù hợp cho đa dạng đối tượng khách hàng. Một lựa chọn lý tưởng cho ai yêu thích vẻ đẹp giản dị mà tinh tế.',
                price: 720000,
                isAccessory: false,
                createdBy: 1
            },
            {
                brandId: 10,
                name: 'Basas Bumper Gum EXT NE - Low Top - Offwhite/Gum',
                slug: 'basas-bumper-gum-ext-ne-low-top-offwhite-gum',
                description:
                    'Basas Bumper Gum EXT NE - Low Top - Offwhite/Gum - Đôi sneaker unisex mang phong cách retro streetwear nhẹ nhàng. Thân giày bằng canvas NE dày dặn, phối cùng chi tiết suede tạo điểm nhấn thanh lịch và bền bỉ. Màu "Offwhite" nhẹ nhàng kết hợp đế cao su gum mềm dẻo mang lại cảm giác êm ái và độ bám tốt. Thiết kế năng động, lý tưởng cho cả việc đi dạo phố hay sử dụng hàng ngày.',
                price: 580000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 10,
                name: 'Vintas Public 2000s - Low Top - Insignia Blue',
                slug: 'vintas-public-2000s-low-top-insignia-blue',
                description:
                    'Vintas Public 2000s - Low Top "Insignia Blue" - Đôi sneaker nữ mang phong cách retro với tông xanh biển "Insignia Blue" nhẹ nhàng nhưng không kém phần nổi bật. Thân giày bằng canvas dày bền bỉ, phối cùng chi tiết đế cao su chắc chắn giúp mang lâu mà vẫn thoải mái. Thiết kế cổ thấp linh hoạt, lý tưởng để phối cùng trang phục streetwear, jean hay phong cách hàng ngày năng động.',
                price: 620000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 4,
                name: "Dép Biti's Nam Màu Xanh Nhớt BTM001877XNH",
                slug: 'dep-bitis-nam-mau-xanh-nhot-btm001877xnh',
                description:
                    "Một đôi dép kẹp nam thanh thoát và thời trang từ Biti's, nổi bật với tông xanh nhớt khỏe khoắn, dễ phối cùng quần jean hay quần shorts hàng ngày. Quai dép làm từ da PU tổng hợp mềm mại, không thấm nước, đế EVA nhẹ và êm giúp giảm áp lực khi di chuyển. Thiết kế tối giản, ôm chân, có độ bám sàn tốt và chống trượt, rất phù hợp để dùng hàng ngày - từ đi học, đi làm đến du lịch, dạo phố.",
                price: 445000,
                isAccessory: false,
                createdBy: 2
            },
            {
                brandId: 4,
                name: "Dép Biti's Nam Màu Nâu BXM005200NAU",
                slug: 'dep-bitis-nam-mau-nau-bxm005200nau',
                description:
                    "Dép Biti's Nam BXM005200NAU - Màu nâu - Đôi dép nam đơn giản và dễ phối hợp trang phục với sắc nâu trung tính. Thiết kế nhẹ, thoáng, phù hợp sử dụng hàng ngày - từ đi học, đi làm đến du lịch, dạo phố. Đế và quai dép chắc chắn, giúp bước đi ổn định và thoải mái.",
                price: 255000,
                isAccessory: false,
                createdBy: 2
            }
        ]
    })

    // --- Product Images ---
    await prisma.productImage.createMany({
        data: [
            { rootProductId: 76, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992254/product/kenzo_graffiti_1_hojsxe.jpg' },
            { rootProductId: 76, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992253/product/kenzo_graffiti_2_uklmkv.jpg' },
            { rootProductId: 76, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992254/product/kenzo_graffiti_3_yoaxmu.jpg' },
            { rootProductId: 76, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992256/product/kenzo_graffiti_4_wmxujg.jpg' },
            { rootProductId: 77, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992292/product/adidas_resort_1_srkyxr.jpg' },
            { rootProductId: 77, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992273/product/adidas_resort_2_hbnxtr.jpg' },
            { rootProductId: 77, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992270/product/adidas_resort_3_vzkvuz.jpg' },
            { rootProductId: 77, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1763992270/product/adidas_resort_4_csnk8q.jpg' },
            { rootProductId: 78, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764001833/product/boots_chunky_1_bfxwk4.jpg' },
            { rootProductId: 78, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764001833/product/boots_chunky_2_jmyjhh.jpg' },
            { rootProductId: 78, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764001833/product/boots_chunky_3_kjbsox.jpg' },
            { rootProductId: 78, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764001838/product/boots_chunky_4_xp5cva.jpg' },
            { rootProductId: 78, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764001833/product/boots_chunky_5_r8zatq.jpg' },
            { rootProductId: 78, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764001833/product/boots_chunky_6_lcufjj.jpg' },
            { rootProductId: 79, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764002725/product/boots_chelsea_1_z0r2hl.jpg' },
            { rootProductId: 79, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764002724/product/boots_chelsea_2_vx8jhs.jpg' },
            { rootProductId: 79, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764002722/product/boots_chelsea_3_x2rusk.jpg' },
            { rootProductId: 79, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764002719/product/boots_chelsea_4_niwmz2.jpg' },
            { rootProductId: 79, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764002718/product/boots_chelsea_5_xqvbbm.jpg' },
            { rootProductId: 79, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764002718/product/boots_chelsea_6_azlu7k.jpg' },
            { rootProductId: 80, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764008146/product/mules_no_1_n13wzc.jpg' },
            { rootProductId: 80, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764008147/product/mules_no_2_ff6zuz.jpg' },
            { rootProductId: 80, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764008146/product/mules_no_3_aw9ybx.jpg' },
            { rootProductId: 80, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764008147/product/mules_no_4_zlgjel.jpg' },
            { rootProductId: 80, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764008151/product/mules_no_5_mjhvv1.jpg' },
            { rootProductId: 80, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764008152/product/mules_no_6_q3lvd7.jpg' },
            { rootProductId: 81, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764009372/product/guoc_mary_janes_1_qplbam.jpg' },
            { rootProductId: 81, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764009369/product/guoc_mary_janes_2_h6abty.jpg' },
            { rootProductId: 81, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764009369/product/guoc_mary_janes_3_jsfoat.jpg' },
            { rootProductId: 81, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764009368/product/guoc_mary_janes_4_lduatg.jpg' },
            { rootProductId: 81, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764009372/product/guoc_mary_janes_5_wemfeh.jpg' },
            { rootProductId: 81, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764009368/product/guoc_mary_janes_6_dad8ah.jpg' },
            { rootProductId: 82, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011778/product/ananas_bag_1_xumctf.jpg' },
            { rootProductId: 82, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011773/product/ananas_bag_2_ujsrja.jpg' },
            { rootProductId: 82, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011773/product/ananas_bag_3_pwqzxn.jpg' },
            { rootProductId: 82, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011772/product/ananas_bag_4_ujarz0.jpg' },
            { rootProductId: 82, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011772/product/ananas_bag_5_n2t2in.jpg' },
            { rootProductId: 83, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764012075/product/ananas_insole_1_iik9x6.jpg' },
            { rootProductId: 83, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764012073/product/ananas_insole_2_fwmysk.jpg' },
            { rootProductId: 83, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764012071/product/ananas_insole_3_hve1fy.jpg' },
            { rootProductId: 83, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764012070/product/ananas_insole_4_qd8krv.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096166/product/track_6_fold_1_hm5fv1.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096166/product/track_6_fold_2_cawu7m.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096165/product/track_6_fold_3_nyvi1o.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096165/product/track_6_fold_4_thzkfv.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096166/product/track_6_fold_5_qdlpby.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096165/product/track_6_fold_6_bqgz1k.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096165/product/track_6_fold_7_tgc9un.jpg' },
            { rootProductId: 84, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764096165/product/track_6_fold_8_bdfh9q.jpg' },
            { rootProductId: 85, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097306/product/vintas_denim_1_ceweny.jpg' },
            { rootProductId: 85, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097306/product/vintas_denim_2_c8c34e.jpg' },
            { rootProductId: 85, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097305/product/vintas_denim_3_m12vsf.jpg' },
            { rootProductId: 85, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097306/product/vintas_denim_4_qcflfp.jpg' },
            { rootProductId: 85, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097305/product/vintas_denim_5_bmzcpq.jpg' },
            { rootProductId: 85, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097305/product/vintas_denim_6_fe7otb.jpg' },
            { rootProductId: 85, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097305/product/vintas_denim_7_b74ch0.jpg' },
            { rootProductId: 86, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097797/product/vintas_nauda_ext_1_iihabg.jpg' },
            { rootProductId: 86, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097798/product/vintas_nauda_ext_2_fkncdp.jpg' },
            { rootProductId: 86, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097798/product/vintas_nauda_ext_3_tyv5u8.jpg' },
            { rootProductId: 86, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097798/product/vintas_nauda_ext_4_ssvl0p.jpg' },
            { rootProductId: 86, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097798/product/vintas_nauda_ext_5_ztdsaq.jpg' },
            { rootProductId: 86, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764097798/product/vintas_nauda_ext_6_lw3ckk.jpg' },
            { rootProductId: 87, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764098622/product/basas_bumper_1_pxkgqq.jpg' },
            { rootProductId: 87, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764098623/product/basas_bumper_2_kurszk.jpg' },
            { rootProductId: 87, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764098622/product/basas_bumper_3_ax3pqu.jpg' },
            { rootProductId: 87, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764098624/product/basas_bumper_4_nivpiz.jpg' },
            { rootProductId: 87, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764098622/product/basas_bumper_5_taykik.jpg' },
            { rootProductId: 87, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764098623/product/basas_bumper_6_uxxvgd.jpg' },
            { rootProductId: 87, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764098623/product/basas_bumper_7_ctcod5.jpg' },
            { rootProductId: 88, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764099558/product/vintas_public_1_y2lgkc.jpg' },
            { rootProductId: 88, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764099558/product/vintas_public_2_mraulb.jpg' },
            { rootProductId: 88, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764099558/product/vintas_public_3_kggfl3.jpg' },
            { rootProductId: 88, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764099559/product/vintas_public_4_gdlt2h.jpg' },
            { rootProductId: 88, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764099559/product/vintas_public_5_yxpgd2.jpg' },
            { rootProductId: 88, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764099560/product/vintas_public_6_utzttz.jpg' },
            { rootProductId: 89, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011052/product/bitis_xanh_nhot_1_ph4fpv.jpg' },
            { rootProductId: 89, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011063/product/bitis_xanh_nhot_2_esqqai.jpg' },
            { rootProductId: 89, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011063/product/bitis_xanh_nhot_3_wvbqwc.jpg' },
            { rootProductId: 89, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011061/product/bitis_xanh_nhot_4_dveuuz.jpg' },
            { rootProductId: 89, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011060/product/bitis_xanh_nhot_5_xc2rdy.jpg' },
            { rootProductId: 90, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011180/product/bitis_nau_1_th8a87.jpg' },
            { rootProductId: 90, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011179/product/bitis_nau_2_kychza.jpg' },
            { rootProductId: 90, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011176/product/bitis_nau_3_f9lpsw.jpg' },
            { rootProductId: 90, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011177/product/bitis_nau_4_ahxo4k.jpg' },
            { rootProductId: 90, url: 'https://res.cloudinary.com/dagaqa0ly/image/upload/v1764011174/product/bitis_nau_5_asn5bj.jpg' }
        ]
    })

    // --- Product Items ---
    await prisma.productItem.createMany({
        data: [
            { rootProductId: 76, stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 77, stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 78, size: '35', stock: 7, barcode: generateProductBarcode() },
            { rootProductId: 78, size: '36', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 78, size: '37', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 78, size: '38', stock: 24, barcode: generateProductBarcode() },
            { rootProductId: 78, size: '39', stock: 11, barcode: generateProductBarcode() },
            { rootProductId: 79, size: '35', stock: 3, barcode: generateProductBarcode() },
            { rootProductId: 79, size: '36', stock: 14, barcode: generateProductBarcode() },
            { rootProductId: 79, size: '37', stock: 19, barcode: generateProductBarcode() },
            { rootProductId: 79, size: '38', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 79, size: '39', stock: 8, barcode: generateProductBarcode() },
            { rootProductId: 80, size: '35', stock: 7, barcode: generateProductBarcode() },
            { rootProductId: 80, size: '36', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 80, size: '37', stock: 20, barcode: generateProductBarcode() },
            { rootProductId: 80, size: '38', stock: 24, barcode: generateProductBarcode() },
            { rootProductId: 80, size: '39', stock: 11, barcode: generateProductBarcode() },
            { rootProductId: 81, size: '35', stock: 3, barcode: generateProductBarcode() },
            { rootProductId: 81, size: '36', stock: 14, barcode: generateProductBarcode() },
            { rootProductId: 81, size: '37', stock: 19, barcode: generateProductBarcode() },
            { rootProductId: 81, size: '38', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 81, size: '39', stock: 8, barcode: generateProductBarcode() },
            { rootProductId: 82, stock: 30, barcode: generateProductBarcode() },
            { rootProductId: 83, stock: 50, barcode: generateProductBarcode() },
            { rootProductId: 84, size: '39', stock: 14, barcode: generateProductBarcode() },
            { rootProductId: 84, size: '40', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 84, size: '41', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 84, size: '42', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 84, size: '43', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 84, size: '44', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 85, size: '39', stock: 17, barcode: generateProductBarcode() },
            { rootProductId: 85, size: '40', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 85, size: '41', stock: 19, barcode: generateProductBarcode() },
            { rootProductId: 85, size: '42', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 85, size: '43', stock: 27, barcode: generateProductBarcode() },
            { rootProductId: 85, size: '44', stock: 8, barcode: generateProductBarcode() },
            { rootProductId: 86, size: '39', stock: 14, barcode: generateProductBarcode() },
            { rootProductId: 86, size: '40', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 86, size: '41', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 86, size: '42', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 86, size: '43', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 86, size: '44', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '37', stock: 8, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '38', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '39', stock: 17, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '40', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '41', stock: 19, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '42', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '43', stock: 27, barcode: generateProductBarcode() },
            { rootProductId: 87, size: '44', stock: 8, barcode: generateProductBarcode() },
            { rootProductId: 88, size: '37', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 88, size: '38', stock: 18, barcode: generateProductBarcode() },
            { rootProductId: 88, size: '39', stock: 27, barcode: generateProductBarcode() },
            { rootProductId: 88, size: '40', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 88, size: '41', stock: 9, barcode: generateProductBarcode() },
            { rootProductId: 89, size: '39', stock: 17, barcode: generateProductBarcode() },
            { rootProductId: 89, size: '40', stock: 21, barcode: generateProductBarcode() },
            { rootProductId: 89, size: '41', stock: 19, barcode: generateProductBarcode() },
            { rootProductId: 89, size: '42', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 89, size: '43', stock: 27, barcode: generateProductBarcode() },
            { rootProductId: 89, size: '44', stock: 12, barcode: generateProductBarcode() },
            { rootProductId: 89, size: '45', stock: 8, barcode: generateProductBarcode() },
            { rootProductId: 90, size: '39', stock: 14, barcode: generateProductBarcode() },
            { rootProductId: 90, size: '40', stock: 22, barcode: generateProductBarcode() },
            { rootProductId: 90, size: '41', stock: 25, barcode: generateProductBarcode() },
            { rootProductId: 90, size: '42', stock: 15, barcode: generateProductBarcode() },
            { rootProductId: 90, size: '43', stock: 11, barcode: generateProductBarcode() }
        ]
    })

    // --- Shoe Features ---
    await prisma.shoeFeature.createMany({
        data: [
            {
                rootProductId: 78,
                categoryId: 7,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da nhân tạo',
                soleMaterial: 'Cao su hoặc đế tổng hợp chunky',
                liningMaterial: 'Vải tổng hợp mềm (giả định vì Vascara không nêu rõ)',
                closureType: 'Dây buộc cao cổ (combat style)',
                toeShape: 'Mũi tròn',
                waterResistant: 'Trung bình',
                breathability: 'Trung bình',
                pattern: 'Bề mặt bóng, đế chunky mạnh mẽ, phong cách quân đội thời trang',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#202020',
                secondaryColor: null,
                heelHeight: 5.0,
                durabilityRating: 4.1,
                releaseYear: 2023
            },
            {
                rootProductId: 79,
                categoryId: 7,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Microfiber vải tổng hợp',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải đệm mềm',
                closureType: 'Slip-on (Chelsea, không dây), có chun hông để dễ xỏ',
                toeShape: 'Mũi tròn (bít mũi)',
                waterResistant: 'Trung bình',
                breathability: 'Trung bình',
                pattern: 'Màu nâu đậm trơn, phong cách Chelsea cổ điển',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#7a5a49',
                secondaryColor: null,
                heelHeight: 6.0,
                durabilityRating: 4.2,
                releaseYear: 2023
            },
            {
                rootProductId: 80,
                categoryId: 8,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da nhân tạo tổng hợp (PU)',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Vải tổng hợp + da PU mềm',
                closureType: 'Slip-on (mules)',
                toeShape: 'Mũi tròn oval',
                waterResistant: 'Thấp',
                breathability: 'Trung bình',
                pattern: 'Màu kem truyền thống và nữ tính, phối nơ trang trí cách điệu',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#f1e9db',
                secondaryColor: null,
                heelHeight: 4.5,
                durabilityRating: 4.0,
                releaseYear: 2024
            },
            {
                rootProductId: 81,
                categoryId: 8,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Da nhân tạo',
                soleMaterial: 'Cao su hoặc tổng hợp',
                liningMaterial: 'Vải hoặc PU nhẹ',
                closureType: 'Slip-on (mule Mary Janes)',
                toeShape: 'Mũi vuông',
                waterResistant: 'Thấp',
                breathability: 'Trung bình',
                pattern: 'Màu be trơn, thiết kế Mary Janes cổ điển với mũi vuông',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#ceb59a',
                secondaryColor: null,
                heelHeight: 5.5,
                durabilityRating: 4.0,
                releaseYear: 2024
            },
            {
                rootProductId: 84,
                categoryId: 1,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da tổng hợp C-Leather',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải tổng hợp + Textile mềm',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Trung bình',
                breathability: 'Trung bình',
                pattern: 'Màu Caviar Black, lưỡi gà gập (fold-over tongue), phong cách retro',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#3c3c3c',
                secondaryColor: '#c6c1b6',
                heelHeight: 3.0,
                durabilityRating: 7.2,
                releaseYear: 2023
            },
            {
                rootProductId: 85,
                categoryId: 1,
                gender: ShoeGender.MALE,
                upperMaterial: 'Denim (vải jean)',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Thấp',
                breathability: 'Tốt',
                pattern: 'Denim Night Sky (xanh đen jean), thiết kế đơn giản, cổ điển',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#313344',
                secondaryColor: '#404241',
                heelHeight: 2.5,
                durabilityRating: 7.0,
                releaseYear: 2023
            },
            {
                rootProductId: 86,
                categoryId: 1,
                gender: ShoeGender.MALE,
                upperMaterial: 'Vải Canvas + Vải Suede',
                soleMaterial: 'Cao su',
                liningMaterial: 'Textile mềm',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Thấp',
                breathability: 'Tốt',
                pattern: "Màu Monk's Robe (nâu trầm), upper phối canvas & suede, high-top cổ cao.",
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#4d3d2f',
                secondaryColor: '#bca071',
                heelHeight: 3.0,
                durabilityRating: 7.2,
                releaseYear: 2024
            },
            {
                rootProductId: 87,
                categoryId: 1,
                gender: ShoeGender.UNISEX,
                upperMaterial: 'Vải Canvas + Vải Suede',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải textile mềm ',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Trung bình',
                breathability: 'Tốt',
                pattern: 'Upper màu Offwhite phối suede, đế gum dẻo dai nổi bật',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#eae9df',
                secondaryColor: '#c0bdb7',
                heelHeight: 2.8,
                durabilityRating: 7.2,
                releaseYear: 2023
            },
            {
                rootProductId: 88,
                categoryId: 1,
                gender: ShoeGender.FEMALE,
                upperMaterial: 'Vải Canvas',
                soleMaterial: 'Cao su',
                liningMaterial: 'Vải tổng hợp',
                closureType: 'Dây buộc',
                toeShape: 'Mũi tròn',
                waterResistant: 'Thấp',
                breathability: 'Tốt',
                pattern: 'Insignia Blue - lớp canvas trơn màu xanh navy, thiết kế minimal low-top',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#57617a',
                secondaryColor: '#c7b599',
                heelHeight: 2.8,
                durabilityRating: 7.0,
                releaseYear: 2024
            },
            {
                rootProductId: 89,
                categoryId: 3,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da PU tổng hợp',
                soleMaterial: 'EVA',
                liningMaterial: 'EVA',
                closureType: 'Slip-on (dép kẹp / xỏ ngón)',
                toeShape: 'Mũi hở / không định hình',
                waterResistant: 'Trung bình',
                breathability: 'Tốt',
                pattern: 'Trơn màu xanh nhớt, thiết kế minimal nam tính, dép slip-on dễ xỏ',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#223346',
                secondaryColor: '#31333a',
                heelHeight: 2.0,
                durabilityRating: 6.0,
                releaseYear: 2024
            },
            {
                rootProductId: 90,
                categoryId: 3,
                gender: ShoeGender.MALE,
                upperMaterial: 'Da PU tổng hợp',
                soleMaterial: 'Cao su tổng hợp',
                liningMaterial: 'Cao su tổng hợp',
                closureType: 'Slip-on (dép kẹp / xỏ ngón)',
                toeShape: 'Mũi hở / không định hình',
                waterResistant: 'Trung bình',
                breathability: 'Tốt',
                pattern: 'Trơn màu nâu trung tính, thiết kế đơn giản, nam tính',
                countryOfOrigin: 'Việt Nam',
                primaryColor: '#887774',
                secondaryColor: '#e2bf9d',
                heelHeight: 1.5,
                durabilityRating: 3.8,
                releaseYear: 2024
            }
        ]
    })

    // --- Shoe Feature - Occasion Tag ---
    await prisma.shoeFeatureOccasionTag.createMany({
        data: [
            { shoeFeatureId: 59, occasionTagId: 2 },
            { shoeFeatureId: 59, occasionTagId: 3 },
            { shoeFeatureId: 59, occasionTagId: 6 },
            { shoeFeatureId: 59, occasionTagId: 10 },
            { shoeFeatureId: 60, occasionTagId: 2 },
            { shoeFeatureId: 60, occasionTagId: 3 },
            { shoeFeatureId: 60, occasionTagId: 6 },
            { shoeFeatureId: 60, occasionTagId: 10 },
            { shoeFeatureId: 61, occasionTagId: 2 },
            { shoeFeatureId: 61, occasionTagId: 3 },
            { shoeFeatureId: 61, occasionTagId: 6 },
            { shoeFeatureId: 61, occasionTagId: 7 },
            { shoeFeatureId: 61, occasionTagId: 8 },
            { shoeFeatureId: 61, occasionTagId: 10 },
            { shoeFeatureId: 62, occasionTagId: 2 },
            { shoeFeatureId: 62, occasionTagId: 3 },
            { shoeFeatureId: 62, occasionTagId: 6 },
            { shoeFeatureId: 62, occasionTagId: 7 },
            { shoeFeatureId: 62, occasionTagId: 8 },
            { shoeFeatureId: 62, occasionTagId: 10 },
            { shoeFeatureId: 63, occasionTagId: 1 },
            { shoeFeatureId: 63, occasionTagId: 2 },
            { shoeFeatureId: 63, occasionTagId: 3 },
            { shoeFeatureId: 63, occasionTagId: 7 },
            { shoeFeatureId: 63, occasionTagId: 8 },
            { shoeFeatureId: 63, occasionTagId: 9 },
            { shoeFeatureId: 64, occasionTagId: 1 },
            { shoeFeatureId: 64, occasionTagId: 2 },
            { shoeFeatureId: 64, occasionTagId: 3 },
            { shoeFeatureId: 64, occasionTagId: 7 },
            { shoeFeatureId: 64, occasionTagId: 8 },
            { shoeFeatureId: 64, occasionTagId: 9 },
            { shoeFeatureId: 65, occasionTagId: 1 },
            { shoeFeatureId: 65, occasionTagId: 2 },
            { shoeFeatureId: 65, occasionTagId: 3 },
            { shoeFeatureId: 65, occasionTagId: 7 },
            { shoeFeatureId: 65, occasionTagId: 8 },
            { shoeFeatureId: 65, occasionTagId: 9 },
            { shoeFeatureId: 66, occasionTagId: 1 },
            { shoeFeatureId: 66, occasionTagId: 2 },
            { shoeFeatureId: 66, occasionTagId: 3 },
            { shoeFeatureId: 66, occasionTagId: 7 },
            { shoeFeatureId: 66, occasionTagId: 8 },
            { shoeFeatureId: 66, occasionTagId: 9 },
            { shoeFeatureId: 67, occasionTagId: 1 },
            { shoeFeatureId: 67, occasionTagId: 2 },
            { shoeFeatureId: 67, occasionTagId: 3 },
            { shoeFeatureId: 67, occasionTagId: 7 },
            { shoeFeatureId: 67, occasionTagId: 8 },
            { shoeFeatureId: 67, occasionTagId: 9 },
            { shoeFeatureId: 68, occasionTagId: 2 },
            { shoeFeatureId: 68, occasionTagId: 7 },
            { shoeFeatureId: 68, occasionTagId: 8 },
            { shoeFeatureId: 68, occasionTagId: 9 },
            { shoeFeatureId: 69, occasionTagId: 2 },
            { shoeFeatureId: 69, occasionTagId: 7 },
            { shoeFeatureId: 69, occasionTagId: 8 },
            { shoeFeatureId: 69, occasionTagId: 9 }
        ]
    })

    // --- Shoe Feature - Design Tag ---
    await prisma.shoeFeatureDesignTag.createMany({
        data: [
            { shoeFeatureId: 59, designTagId: 3 },
            { shoeFeatureId: 59, designTagId: 4 },
            { shoeFeatureId: 59, designTagId: 6 },
            { shoeFeatureId: 59, designTagId: 7 },
            { shoeFeatureId: 59, designTagId: 12 },
            { shoeFeatureId: 60, designTagId: 3 },
            { shoeFeatureId: 60, designTagId: 4 },
            { shoeFeatureId: 60, designTagId: 6 },
            { shoeFeatureId: 60, designTagId: 7 },
            { shoeFeatureId: 60, designTagId: 12 },
            { shoeFeatureId: 61, designTagId: 1 },
            { shoeFeatureId: 61, designTagId: 2 },
            { shoeFeatureId: 61, designTagId: 4 },
            { shoeFeatureId: 61, designTagId: 11 },
            { shoeFeatureId: 62, designTagId: 1 },
            { shoeFeatureId: 62, designTagId: 2 },
            { shoeFeatureId: 62, designTagId: 4 },
            { shoeFeatureId: 62, designTagId: 11 },
            { shoeFeatureId: 62, designTagId: 12 },
            { shoeFeatureId: 63, designTagId: 1 },
            { shoeFeatureId: 63, designTagId: 2 },
            { shoeFeatureId: 63, designTagId: 5 },
            { shoeFeatureId: 63, designTagId: 6 },
            { shoeFeatureId: 63, designTagId: 10 },
            { shoeFeatureId: 63, designTagId: 11 },
            { shoeFeatureId: 64, designTagId: 1 },
            { shoeFeatureId: 64, designTagId: 2 },
            { shoeFeatureId: 64, designTagId: 5 },
            { shoeFeatureId: 64, designTagId: 6 },
            { shoeFeatureId: 64, designTagId: 10 },
            { shoeFeatureId: 64, designTagId: 11 },
            { shoeFeatureId: 65, designTagId: 1 },
            { shoeFeatureId: 65, designTagId: 2 },
            { shoeFeatureId: 65, designTagId: 5 },
            { shoeFeatureId: 65, designTagId: 6 },
            { shoeFeatureId: 65, designTagId: 10 },
            { shoeFeatureId: 65, designTagId: 11 },
            { shoeFeatureId: 66, designTagId: 1 },
            { shoeFeatureId: 66, designTagId: 2 },
            { shoeFeatureId: 66, designTagId: 5 },
            { shoeFeatureId: 66, designTagId: 6 },
            { shoeFeatureId: 66, designTagId: 10 },
            { shoeFeatureId: 66, designTagId: 11 },
            { shoeFeatureId: 67, designTagId: 1 },
            { shoeFeatureId: 67, designTagId: 2 },
            { shoeFeatureId: 67, designTagId: 5 },
            { shoeFeatureId: 67, designTagId: 6 },
            { shoeFeatureId: 67, designTagId: 10 },
            { shoeFeatureId: 67, designTagId: 11 },
            { shoeFeatureId: 68, designTagId: 2 },
            { shoeFeatureId: 68, designTagId: 5 },
            { shoeFeatureId: 68, designTagId: 6 },
            { shoeFeatureId: 68, designTagId: 10 },
            { shoeFeatureId: 69, designTagId: 2 },
            { shoeFeatureId: 69, designTagId: 5 },
            { shoeFeatureId: 69, designTagId: 6 },
            { shoeFeatureId: 69, designTagId: 10 }
        ]
    })
}
